empathyco/x

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
scripts/prepare-release.js
scripts/publish-release.js

Please include a summary of the change and which issue is fixed.
After seeing today the proposed release flow we decided to improve it:
1. Manually trigger the `Prepare release` action. This will create a new PR bumping the needed packages versions, and updating its change-logs
2. Review the changes in that PR. If necessary, fix changelogs, version, whatever is needed.
3. When merging the PR (I suggest using the `squash` technique) the `Publish release` action will be automatically invoked.
The `main` branch
This flow has been tested at the [Lerna Repo Playground](https://github.com/javieri-empathy/lerna-repo/)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings

ci: make releases create a new PR instead of committing in main.

---

packages/x-components/src/x-modules/related-tags/components/related-tag.vue
packages/x-components/src/x-modules/related-tags/components/related-tags.vue

Description
Use new structure and content agreed with Edocs (https://hackmd.io/team/empathy-docs?nav=overview)
I changed links to fit the x-components repository
every method is now internal so it is only visible in the code.
change examples
Context
This will prevent conflicts in the future migration to the Empathy Docs portal.
Test
See if there is something missing https://hackmd.io/team/empathy-docs?nav=overview
Check markdowns generated by build step

docs(related-tags): adapt to eDocs guidelines

---

packages/search-types/src/facet/filter/boolean-filter.model.ts
packages/search-types/src/facet/filter/editable-number-range-filter.model.ts
packages/search-types/src/facet/filter/raw-filter.model.ts
packages/search-types/src/named-model.model.ts
packages/search-types/src/schemas/filter.schema.ts

EX-4449
Finally It was just a couple of changes:
1- Make the `BooleanFilter` and the `EditableNumberRangeFilter` to inherit from `FacetFilter`
2-Fix Schemas
3-Delete the `value` field in the `BooleanFilter`. The `id` is what we will use as value from now.

fix(x-types): Fix filters models inheritance.

---

package-lock.json
packages/x-components/src/index.ts
packages/x-components/src/store/x.module.ts
packages/x-components/src/x-modules/facets-next/index.ts
packages/x-components/src/x-modules/facets-next/store/emitters.ts
packages/x-components/src/x-modules/facets-next/store/index.ts
packages/x-components/src/x-modules/facets-next/store/module.ts
packages/x-components/src/x-modules/facets-next/store/types.ts
packages/x-components/src/x-modules/facets-next/wiring.ts
packages/x-components/src/x-modules/facets-next/x-module.ts
packages/x-components/src/x-modules/x-modules.types.ts

EX-3647
Adds the new `facets-next` `x-module`, where the new `facets` approach is going to be developed, with basic content:
- Store state
- Store mutations
- ⚠️ Store getters (not implemented, just defined)

feat(facets-next): add module

---

packages/x-components/src/components/__tests__/staggering-transition-group.spec.ts
packages/x-components/src/components/staggering-transition-group.vue

EX-4504
This solves an issue detected in `Kroger` where, clicking on multiple `related tags` too fast, the user could have more than one `related tag` selected but only the first one is being used to refine the query. 
I've included a new unit test. It can also be tested in any of our views, for example, in the `Layout` view, adding the `StaggeringFadeAndSlide`  animation to the `RelatedTags` component.

fix(animations): disable `StaggeringTransitionGroup` leaving elements listening to click events

---

packages/x-components/src/components/decorators/__tests__/bus.decorators.spec.ts
packages/x-components/src/components/modals/__tests__/base-events-close-button.spec.ts
packages/x-components/src/components/modals/__tests__/base-events-modal-open-button.spec.ts
packages/x-components/src/components/modals/__tests__/base-events-modal.spec.ts
packages/x-components/src/components/modals/base-events-modal-close.vue
packages/x-components/src/components/modals/base-events-modal-open.vue
packages/x-components/src/components/modals/base-events-modal.vue
packages/x-components/src/wiring/events.types.ts
packages/x-components/src/x-installer/api/api.types.ts
packages/x-components/src/x-installer/api/base-api.ts

This PR modifies the current XAPI to use the search function to open X when it's called without query.
To make this event works with the current X components, you have to use de BaseEventsModal instead of the BaseIdModal, this modal will be opened when an event that it's been listened to by it, its called.
Some of the events were renamed to be more accurate.
To test this, you can go to the BaseEventsModal view and change the events to open the modal:
`<BaseEventsModal :eventsToOpenModal=['UserClickedOpenEventsModal, 'UserOpenXProgramatically']>`
EX-3555

feat: modify search function in XAPI to open X

---

packages/x-components/src/router.ts
packages/x-components/src/views/LayoutNext.vue
packages/x-components/src/wiring/__tests__/wires-operators.spec.ts
packages/x-components/src/wiring/wires.operators.ts
packages/x-components/src/x-modules/facets-next/components/__tests__/utils.ts
packages/x-components/src/x-modules/facets-next/components/facets/__tests__/facets.spec.ts
packages/x-components/src/x-modules/facets-next/components/facets/facets.vue
packages/x-components/src/x-modules/facets-next/components/index.ts
packages/x-components/src/x-modules/facets-next/wiring.ts
packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/search/store/emitters.ts

EX-3661
Please include a summary of the change and which issue is fixed.
This PR consists on:
- Include the `Facets.vue` component into the `NextFacets` X-Module.
- Remove the Provided Facets logic from `Facets.vue` component. (This will be included in a new coming soon Provider Component)
- Modify wiring to make the facets work with the new Vuex Store in `NextFacets` X-Module.
- Modify (Temporally) the `Search` X-Module wiring to "send" the API facets to `NextFacets` module.
- Modify the `Facets.vue` component tests to test only the remaining logic.
- Adds new `LayoutNext.vue` view using the new `Facets.vue` component to check it working.

feat(facets-next): add facets component to FacetsNext module

---

packages/x-components/src/x-modules/facets-next/service/__tests__/facets-service.spec.ts

Just adds a similar test for the `FacetsService.setFacets` method, and adds assertion for the new facets property to be set.

test(facets-next): add missing service tests

---

packages/x-components/src/views/LayoutNext.vue
packages/x-components/src/x-modules/facets-next/components/__tests__/clear-filters.spec.ts
packages/x-components/src/x-modules/facets-next/components/__tests__/utils.ts
packages/x-components/src/x-modules/facets-next/components/clear-filters.vue
packages/x-components/src/x-modules/facets-next/components/facets/__tests__/facets-provider.spec.ts
packages/x-components/src/x-modules/facets-next/components/facets/__tests__/facets.spec.ts
packages/x-components/src/x-modules/facets-next/components/filters/__tests__/all-filter.spec.ts
packages/x-components/src/x-modules/facets-next/components/index.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/exclude-filters-with-no-results.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/filters-search.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/selected-filters-list.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/selected-filters.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/sliced-filters.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/__tests__/sorted-filters.spec.ts
packages/x-components/src/x-modules/facets-next/components/lists/exclude-filters-with-no-results.vue
packages/x-components/src/x-modules/facets-next/components/lists/filters-search.vue
packages/x-components/src/x-modules/facets-next/components/lists/selected-filters-list.vue
packages/x-components/src/x-modules/facets-next/components/lists/selected-filters.vue
packages/x-components/src/x-modules/facets-next/components/lists/sliced-filters.vue
packages/x-components/src/x-modules/facets-next/components/lists/sorted-filters.vue

Add `ClearFilters`, `ExcludeFiltersWithNoResults`, `SortedFilters`, `FiltersSearch`,
`SlicedFilters`, `SelectedFilters` and  `SelectedFiltersList` components.
EX-4615
Add all pending components to `NextFacets` X-Module. (Except `HierarchicalFIlter`, which has its own PR).
Also used these new components in the `LayoutNext` view to check them working.
The motivation is to move all pending things from the old `Facets` X-Module to the new `FacetsNext`X-Module, before removing the old and replace it with the new.
Use the `LayoutNext` view to check it working.
**REMARK:** All the facets are multiselect by default. The `MultiSelectFilters` component disappears. Now it is a modifier in the Entities which modifies the facet to be "Single Select":
``` …
```

feat(facets-next): add all remaining components to Facets Next X-Module

---

packages/x-components/src/components/x-component.types.ts
packages/x-components/src/plugins/__tests__/x-plugin-mixin.spec.ts
packages/x-components/src/plugins/x-plugin.mixin.ts

It adds the origin injection in the mixin and also in the generated bus API.
NOTE: Please, remember to add the task reference EX-4636. I forgot it in the commit message.

feat(mixin): add origin injection in the mixin and the bus

---

packages/x-components/src/x-modules/popular-searches/store/actions/fetch-suggestions.action.ts

EX-4697
Since the popular searches and the query suggestions use the same adapter endpoint (suggestions), when a new request is made before the previous one is resolved, this is cancelled. Example:
Open search -> Popular Searches requested
Type a query -> Query Suggestions requested -> Popular Searches Request is cancelled.
To solve this we can pass an identifier to the adapter to distinguish the two different requests to the same endpoint.

fix(popular-searches): fix popular searches and query suggestions canceling requests

---

packages/x-components/src/components/__tests__/base-variable-column-grid.spec.ts
packages/x-components/src/components/__tests__/items-list.spec.ts
packages/x-components/src/components/__tests__/search-items-list.spec.ts
packages/x-components/src/components/base-grid.vue
packages/x-components/src/components/base-variable-column-grid.vue
packages/x-components/src/components/decorators/injection.consts.ts
packages/x-components/src/components/index.ts
packages/x-components/src/components/items-list-injection.mixin.ts
packages/x-components/src/components/items-list.vue
packages/x-components/src/components/search-items-injection.mixin.ts
packages/x-components/src/components/search-items-list.vue
packages/x-components/src/utils/array.ts
packages/x-components/src/utils/types.ts
packages/x-components/src/views/FullApp.vue
packages/x-components/src/views/Layout.vue
packages/x-components/src/views/sort.vue
packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries-list.spec.ts
packages/x-components/src/x-modules/next-queries/components/index.ts
packages/x-components/src/x-modules/next-queries/components/next-queries-list.vue
packages/x-components/src/x-modules/search/components/__tests__/banners-list.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/promoteds-list.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/results-list.spec.ts
packages/x-components/src/x-modules/search/components/banners-list.vue
packages/x-components/src/x-modules/search/components/index.ts
packages/x-components/src/x-modules/search/components/promoteds-list.vue
packages/x-components/src/x-modules/search/components/results-list.vue

Adds the new `NextQueriesList` component. This component allows to insert next queries in an injected list of `SearchItems`. How this component inserts the next queries can be configured using the props.
This is needed to support an awesome grid of search items.
Check use cases, documentation, that the components are properly exported...

feat(next-queries): add `NextQueriesList` component.

---

packages/x-components/src/components/index.ts
packages/x-components/src/x-modules/recommendations/wiring.ts

Just to minor fixes. One is fixing the recommendations wiring, which was using a global wire instead of a namespaced one. The other is just exporting a missing injection constant.

fix: Fix recommendations `setParams` wire. Export `LIST_ITEMS_KEY`.

---

packages/search-adapter/src/empathy/mappers/response/empathy-redirection.mapper.ts
packages/search-adapter/src/empathy/models/entities/empathy-direct.model.ts
packages/search-types/src/named-model.model.ts
packages/search-types/src/redirection.model.ts
packages/search-types/src/schemas/redirection.schema.ts
packages/x-components/src/__stubs__/banners-stubs.factory.ts
packages/x-components/src/__stubs__/facets-stubs.factory.ts
packages/x-components/src/__stubs__/filters-stubs.factory.ts
packages/x-components/src/__stubs__/next-queries-stubs.factory.ts
packages/x-components/src/__stubs__/promoteds-stubs.factory.ts
packages/x-components/src/__stubs__/redirections-stubs.factory.ts
packages/x-components/src/__stubs__/related-tags-stubs.factory.ts
packages/x-components/src/__stubs__/results-stubs.factory.ts
packages/x-components/src/__stubs__/search-response-stubs.factory.ts
packages/x-components/src/adapter/util.ts
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts
packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-components/tests/e2e/cucumber/no-suggestions.feature

BREAKING-CHANGE: `Redirection` now has a compulsory `modelName` property.
EX-4730
Just saves the redirections to the search state. This does not add the logic or the component, only saves the redirections.

feat(search): save `Redirection`'s entities.

---

packages/x-components/src/design-system/components/dropdown/default.scss

EX-4764
Aligns the last button of the dropdown toggle to the end only if it has a previous sibling.

chore(design-system): Fix dropdown toggle icon alignment

---

packages/eslint-plugin-x/README.md

Updated Readme on the eslint-plugin-x package to reference the correct package (@empathyco), was previously mentioning @empathy.

docs(eslint-plugin-x): Update readme to reference the correct package

---

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts
packages/x-components/src/plugins/x-plugin.alias.ts
packages/x-components/src/store/utils/status-store.utils.ts
packages/x-components/src/x-modules/identifier-results/store/module.ts
packages/x-components/src/x-modules/next-queries/store/module.ts
packages/x-components/src/x-modules/popular-searches/store/module.ts
packages/x-components/src/x-modules/query-suggestions/store/module.ts
packages/x-components/src/x-modules/recommendations/store/module.ts
packages/x-components/src/x-modules/related-tags/store/module.ts
packages/x-components/src/x-modules/search/store/module.ts

EX-4951
This PR fixes the No results message flashes on load.
Steps to reproduce:
1- load with a query in URL multiple times
2- Sometimes you'll see the No Results Message flashes momentaneously

fix(x-plugin): Fix no results message flash on load.

---

packages/x-components/src/x-modules/url/store/emitters.ts

EX-4949
This PR fixes URL clear query parameter bug.
Steps to reproduce:
1- search
2- click in clear query
3- the query parameter is still in URL

fix(url): Fix URL clear query issue.

---

packages/x-components/src/x-modules/identifier-results/components/identifier-results.vue

[EX-4980](https://searchbroker.atlassian.net/browse/EX-4980)
Add missing provider in `identifier-results` so extra events (`UserClickedAIdentifierResult`) are emitted when clicking an identifier result.

fix(identifier-results): provide resultClickExtraEvents so BaseResultLink emits them when clicked

---

packages/search-types/src/identifiable.model.ts
packages/search-types/src/schemas/identifiable.schema.ts

Just makes the Identifiable type generic so we can use it with another ID types

feat: Make `Identifiable` type generic

---

packages/x-components/src/components/scroll/base-scroll-to-top.vue
packages/x-components/src/index.ts
packages/x-components/src/store/x.module.ts
packages/x-components/src/wiring/events.types.ts
packages/x-components/src/x-modules/scroll/events.types.ts
packages/x-components/src/x-modules/scroll/index.ts
packages/x-components/src/x-modules/scroll/store/emitters.ts
packages/x-components/src/x-modules/scroll/store/index.ts
packages/x-components/src/x-modules/scroll/store/module.ts
packages/x-components/src/x-modules/scroll/store/types.ts
packages/x-components/src/x-modules/scroll/store/utils.ts
packages/x-components/src/x-modules/scroll/wiring.ts
packages/x-components/src/x-modules/scroll/x-module.ts
packages/x-components/src/x-modules/x-modules.types.ts

Adds a basic scroll x module. The scroll module is needed to solve the problems derived from using observables to keep the state.
Adding a scroll module will also help storing the scroll position in the URL. This is the 1st one of 3 expected PRs.

feat(scroll): add empty `XModule`

---

packages/x-components/src/__stubs__/related-tags-stubs.factory.ts
packages/x-components/tests/e2e/cucumber/related-tags/related-tags.spec.ts
packages/x-components/tests/e2e/cucumber/sliding-panel.feature
packages/x-components/tests/e2e/cucumber/sliding-panel.spec.ts

- `related-tags-stubs.factory.ts` have been modified in order to generate 12 RTs.
- doesn't seem necessary to modify `cy.wait(100)`
- Took advantage from the bug and added check for `sliding-panel-left-button`
Sliding panel e2e test is failing in Jenkins. Reproducible in local if CPU performance is slowdown x4.
CPU performance have been slowdown x6 and test still passes.

[EX-5009] Fix sliding panel test

---

packages/x-components/tests/e2e/cucumber/common-steps.spec.ts

The identifier results data-test is not ok, luckily to us the step that uses this selector was trying to not find the element :trollface: 
```javascript
Then('no identifier results are displayed', () => {
cy.getByDataTest('identifier-result-item').should('not.exist');
});
```

test(e2e): fix invalid `IdentifierResults` `data-test` selector

---

packages/x-components/src/__stubs__/empty-search-response-stubs.factory.ts
packages/x-components/src/__stubs__/index.ts
packages/x-components/src/__stubs__/search-response-stubs.factory.ts
packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts
packages/x-components/src/x-modules/search/store/emitters.ts
packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts

Make a request and check the store state in the search module, you will see there the tagging object stored.
EX-3525

feat(search): add `SearchTaggingChanged`  emitter and save coming `queryTagging` from the search response

---

packages/x-components/src/components/suggestions/__tests__/base-suggestion.spec.ts
packages/x-components/src/components/suggestions/base-suggestion.vue
packages/x-components/src/x-modules/related-tags/components/related-tag.vue
packages/x-components/src/x-modules/search-box/components/search-button.vue
packages/x-components/src/x-modules/search-box/components/search-input.vue
packages/x-components/src/x-modules/search/components/__tests__/partial-query-button.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/spellcheck-button.spec.ts
packages/x-components/src/x-modules/search/components/partial-query-button.vue
packages/x-components/src/x-modules/search/components/spellcheck-button.vue

The goal of this PR is to replace the `BaseEventButton` used in some components for an html button. The purpose of this is to ease the process of passing a `feature` property in the metadata for each component that requires it. Recap of the changes:
- `RelatedTag`
- `SpellcheckButton`
- `PartialQueryButton`
- `SearchButton`
- `BaseSuggestion` (used by `QuerySuggestion`, `HistoryQuery`, `PopularSearch` and `NextQuery`)
The case of the `BaseSuggestion` requires to add a prop for the components that use it to decide which `feature` the events should be emitted with.
Tests have been fixed accordingly.
EXTRA: added the `eventkeyhint` attribute to the `SearchInput` component.
This is part of the tagging development and is required to be able to pass different `feature` properties in the …

feat: replace `BaseEventButton` for an html button

---

packages/x-components/src/views/infinite-scroll-body.vue
packages/x-components/src/x-modules/scroll/components/__tests__/window-scroll.spec.ts
packages/x-components/src/x-modules/scroll/components/main-scroll.vue
packages/x-components/src/x-modules/scroll/components/scroll-to-top.vue
packages/x-components/src/x-modules/scroll/components/scroll.const.ts
packages/x-components/src/x-modules/scroll/components/scroll.vue
packages/x-components/src/x-modules/scroll/components/window-scroll.vue
packages/x-components/tests/unit/main-scroll.spec.ts

EX-5041
This checks the element is not the first node matching the `[data-scroll]` selector, so when the scroll is at the top we don't have the first visible element stored in the URL.
It also uses a constant for the default main scroll, so the scroll to top button works by default with both components, and the scroll id is only needed to be passed if there are more scroll component instances.

feat(scroll): ignore first visible element when it is also the first one observed

---

packages/x-components/cypress.json

Right now, the timeout until one test is considered fail is 30s. Moreover, the number of retries in case of failure is 3. This means a total of 30s x 3 = 1m30s waiting in case a test is failing.
The aim of this task is to avoid wasting time by finding the best possible combination between these two.
**### SOLUTION
7s, 1 retry. Build ran successfully 10/10 times.**
Multiple builds will be launched to determine which is the limit the tests start failing

[EX-5015] E2E tests retries

---

packages/x-components/src/views/Layout.vue
packages/x-components/tests/e2e/cucumber/keyboard-navigation.feature
packages/x-components/tests/e2e/cucumber/keyboard-navigation.spec.ts

Although the first idea was to include keyboard-navigation in all the layout including the grid, the approach changed to make it only work in the Empathize. For consistency, it has been added as well in part of the header (`SearchInput`, `ClearSearchInput `and `SearchButton`). It was not possible to added it to the RTs, though. However, that's not essential (although it is desirable) since it's not mandatory for RTs to be placed just below the `search-box`
As usual, change `cypress.json` file in order to run tests independently. 

[EX-4902] Set keyboard navigation in header and Empathize

---

packages/x-components/src/components/__tests__/snippet-callbacks.spec.ts
packages/x-components/src/components/global-x-bus.vue
packages/x-components/src/components/index.ts
packages/x-components/src/components/snippet-callbacks.vue
packages/x-components/src/x-installer/api/api.types.ts

A new componen has been created called `SnippetCallbacks`, when importing this component and used in a view, it will get all the listeners from the `callbacks` property of the `snippetConfig` and will map them to add the `SnippetCallbackExecuted` emit.
This is part of the development that will allow the user to load its own callbacks that will listen to any desired `XEvents` using the `snippetConfig`.
You can try it by yourself in two simple steps:
1. Add a `callbacks` property in the `snippetConfig` with something like:
```
callbacks: {
UserAcceptedAQuery: (query) => query,
}
```
2. Add the component in the view and put a listener in the `SnippetCallbackExecuted` event:
`    <SnippetCallbacks />
`
```
@XOn('SnippetCallbackExecuted')
printThings(payload: any): void {
console.log('event …
```

feature: Add SnippetCallbacks component.

---

packages/x-components/src/x-modules/search/wiring.ts

This Pr changes wiring in the modules that are setting the saveOrigin using an emitter, for those cases, we have to use a user action, for this change will be: `UserPickedARelatedTag`
EX-5078

feat(search): change `saveOriginWire` to be used when a user interaction event is emitted

---

packages/x-components/src/types/origin.ts
packages/x-components/src/utils/__tests__/origin.spec.ts
packages/x-components/src/utils/origin.ts
packages/x-components/src/x-modules/identifier-results/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts

This PR removes the `location` to be not required. Only the feature will be required.
EX-5077

feat(utils): now `origin` only requires the `feature`

---

packages/x-components/src/x-modules/identifier-results/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/identifier-results/store/__tests__/getters.spec.ts
packages/x-components/src/x-modules/identifier-results/store/actions/fetch-and-save-identifier-results.action.ts
packages/x-components/src/x-modules/identifier-results/store/getters/identifier-results-request.getter.ts
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts
packages/x-components/src/x-modules/search/store/getters/request.getter.ts

EX-5079
❗ ❗ Should we flag this as a `BREAKING-CHANGE` too? ❗ ❗
Move the `origin` from `request.getter` to `fetchAndSave.action` in both `search` and `identifierResults` modules, as changing the origin should not trigger a new search request. Only certain user interactions should trigger new search requests.
Added new unit tests in both actions to check the origin is received properly.

feat: move `origin` from `request.getter` to `fetchAndSave.action`

---

packages/x-components/tests/e2e/cucumber/base-column-pickers.feature
packages/x-components/tests/e2e/cucumber/base-result-image.feature
packages/x-components/tests/e2e/cucumber/filters/clear-filters.feature
packages/x-components/tests/e2e/cucumber/filters/exclude-filters.feature
packages/x-components/tests/e2e/cucumber/filters/filters-search.feature
packages/x-components/tests/e2e/cucumber/filters/multiselect-filters.feature
packages/x-components/tests/e2e/cucumber/filters/simple-filters.feature
packages/x-components/tests/e2e/cucumber/filters/sliced-filters.feature
packages/x-components/tests/e2e/cucumber/history-queries.feature
packages/x-components/tests/e2e/cucumber/identifier-results.feature
packages/x-components/tests/e2e/cucumber/keyboard-navigation.feature
packages/x-components/tests/e2e/cucumber/mocked-responses.spec.ts
packages/x-components/tests/e2e/cucumber/next-queries/next-queries.feature
packages/x-components/tests/e2e/cucumber/partial-results/partial-results.feature
packages/x-components/tests/e2e/cucumber/popular-searches/popular-searches.feature
packages/x-components/tests/e2e/cucumber/query-suggestions/query-suggestions.feature
packages/x-components/tests/e2e/cucumber/related-tags/related-tags.feature
packages/x-components/tests/e2e/cucumber/scroll.feature
packages/x-components/tests/e2e/cucumber/search-box/search-box.feature
packages/x-components/tests/e2e/cucumber/sliding-panel.feature
packages/x-components/tests/e2e/cucumber/sort.feature
packages/x-components/tests/e2e/cucumber/spellcheck.feature
packages/x-components/tests/e2e/cucumber/url/url.feature
packages/x-components/tests/e2e/cucumber/url/url.spec.ts

EX-5127
URL e2e tests where failing some times due to 2 reasons:
- Tracking was not being intercepted
- Search responses were mixed, so some times the `the search request contains the origin` step was doing the assertion over the previous request. This was specially noticeable with a 6x cpu slowdown.

test(e2e): make url tests intercept tracking and wait for each request

---

packages/x-components/src/components/base-rating.vue

This is a very simple PR. It changes the styles of the BaseRating component in order to fit images not only horizontally but vertically also. This happens when using icons that somehow are bigger than the `line-height` and `font-size` being applied by the design tokens.

feat(components): fix 'BaseRating' component styles

---

packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

In a previous feature we included the option to configure callbacks on the snippet config. Currently every option on the snippet config is set as extra params, leading to the problem that this callbacks object is sent on every request to the backend. In order to avoid this I have added a field to the SnippetConfigExtraParams to control which options from the snippet config we want to prevent to be taken as extra params. 
I added some callbacks configuration to the snippet config on the project's demo app. I also added the SnippetConfigExtraParams component to reproduce the bug. Afterwards I have check that with my change the callbacks are not sent anymore. Besides I added a unit test.

fix(extraParams): prevent callbacks option from the snippet config to be taken as extra params EX-5104

---

packages/x-components/src/__stubs__/banners-stubs.factory.ts
packages/x-components/src/__stubs__/promoteds-stubs.factory.ts
packages/x-components/src/__stubs__/redirections-stubs.factory.ts
packages/x-components/src/__stubs__/results-stubs.factory.ts
packages/x-components/src/adapter/mocked-adapter.ts
packages/x-components/src/views/Layout.vue
packages/x-components/src/x-modules/search/components/banner.vue
packages/x-components/src/x-modules/search/components/promoted.vue
packages/x-components/src/x-modules/search/components/redirection.vue
packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/tagging/wiring.ts
packages/x-components/tests/e2e/cucumber/mocked-responses.spec.ts
packages/x-components/tests/e2e/cucumber/tagging/tagging.feature
packages/x-components/tests/e2e/cucumber/tagging/tagging.spec.ts

EX-4963
Forces the query tracking to happen immediately in these situations:
- When a search result is clicked.
- When a promoted is clicked.
- When a banner is clicked.
- When a redirection is triggered.
- When a the user triggers the infinite scroll.
This is needed to ensure that we properly track each search request upon any user interaction with the current search response. Otherwise we might lose certain events, as the user might leave the SERP (like on click events), or load a new page (with the infinite scroll).

feat(tagging): track pending query

---

package-lock.json
packages/x-components/.postcssrc
packages/x-components/.postcssrc.js
packages/x-components/build/rollup.config.ts
packages/x-components/package.json

EX-5162
Apparently our Rollup build was not taking into account the PostCSS configuration that we had in the `.postcssrc` file for Vue files. 
Due to our modern browsers configuration, this is only noticeable in the `FixedHeaderAndAsidesLayout` component, which uses a `mask` CSS  property, which should be transpiled to `-webkit-mask` and it isn't. You can check so by examining the build in any other branch.
The proposed solution changes the `.postcssrc` file to a `.js` file, which should still be autoloaded by webpack or the rest of rollup style plugins, and imports it in `rollup.config.ts`, passing its plugins to `vue-rollup-plugin`. The issue was only with `vue-rollup-plugin` which is [creating an empty array](https://github.com/vuejs/vue-component-compiler/blob/845a310d643ab99b50db1babe …

build: Load PostCSS plugins from rollup build

---

packages/x-components/tests/e2e/cucumber/tagging/tagging.feature
packages/x-components/tests/e2e/cucumber/tagging/tagging.spec.ts

EX-5161
This should fix tagging e2e tests which could fail on slower machines. Previously throttling the tests it could happen that the tracking calls were already made before cypress had time to wait for them, so it couldn't see them.
This also happened in the infinite scroll query tagging test, where some times it was expecting the first query tagging call to be the second one, or it could even fail scrolling down and loading the next page.

test(e2e): fix tagging tests

---

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts
packages/x-components/src/plugins/x-plugin.alias.ts
packages/x-components/src/plugins/x-plugin.types.ts

Add the `<span>{{ $x.selectedSort }}</span>` in the layout next to the sort dropdown.
EX-5165

feat(alias): add selected sort

---

packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/search/index.ts
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/__tests__/getters.spec.ts
packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts
packages/x-components/src/x-modules/search/store/getters/request.getter.ts
packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-components/src/x-modules/search/types.ts

EX-5047
There is a bug with the request pagination, infinite scroll and search input causing multiple requests to be made. The `request` getter depends on `isAppendResults` triggering the getter, thus emitting a new `SearchRequestChanged`.
Added unit tests.

fix(search): rows and start parameters calculations moved from getter to action to avoid multiple requests

---

packages/x-components/src/directives/infinite-scroll/infinite-scroll.ts

EX-5181
We don't know why, but a rootMargin over ~1700000 in the IntersectionObserver doesn't work in Android Chrome

fix(components): Fix infinite scroll not working in Android Chrome.

---

packages/x-components/src/components/currency/base-currency.vue
packages/x-components/src/components/layouts/single-column-layout.vue
packages/x-components/src/design-system/components/suggestion/default.scss
packages/x-components/src/design-system/components/suggestion/default.tokens.scss
packages/x-components/src/design-system/components/tag/default.scss

- BaseCurrency: component doesn't display `NaN` if `value` prop is undefined.
- SingleColumnLayout: allows full height predictive layer.
- SingleColumnLayout: Add z-index:1 to `header` `sub-header` and `toolbar` sections to allow add shadow over `main`.
- Design System: Add token to default `x-suggestion` to configure `align-items`.
- Design System: Fix x-tag.x-filter tokens.
EX-5179

fix: Fix multiple issues.

---

packages/x-components/src/design-system/utilities/box-shadow.scss
packages/x-components/src/design-system/utilities/box-shadow.tokens.scss
packages/x-components/src/views/design-system/design-system-utilities.vue

EX-5184
The new variant is to add shadow to an element, but not to overflow that shadow over the top of the element. 
This is needed in BSH setup.

feat(design-system): Add bottom variant to `x-shadow` utility in the Design System.

---

packages/x-components/src/x-modules/tagging/events.types.ts
packages/x-components/src/x-modules/tagging/store/emitters.ts
packages/x-components/src/x-modules/tagging/store/module.ts
packages/x-components/src/x-modules/tagging/store/types.ts
packages/x-components/src/x-modules/tagging/wiring.ts

EX-5170
Provide a new event _SearchTaggingEmitted_ that can be listened on the snippet config callbacks in order to give the customer the chance to track the query on its own. From now on _SearchTaggingChanged_ only stores the query tagging info in the store with a debounce. Modifying this value on the store will emit _SearchTaggingEmitted_ and also will dispatch the query tracking
Import SnippetCallbacks component and add the callback configuration: 
` 
callbacks: {
SearchTaggingEmitted: payload => console.log(payload)
}
`
Check that the number of track requests is the same as the calls to the callback.

feat(tagging): add new SearchTaggingEmitted event for tracking the query

---

packages/x-components/src/components/sliding-panel.vue
packages/x-components/src/design-system/components/sliding-panel/default.scss
packages/x-components/src/design-system/components/sliding-panel/default.token.scss

BREAKING-CHANGE: Remove tokens `--x-color-background-sliding-panel-middle` and `--x-color-background-sliding-panel-end`.
Fix an issue with the z-index in the sliding panel:
Also changed the gradient styles to use the CSS `mask` instead of linear gradient. This way we can control the gradient color with the same token as the sliding panel background.

fix(design-system): Fix Sliding Panel styles.

---

packages/x-components/src/design-system/components/sliding-panel/default.scss

EX-5240
The problem is when the sliding panel doesn't have elements enough to have scroll, it shows the gradient at the beginning anyway:

chore(desing-system): Fix sliding panel bug.

---

packages/x-components/src/design-system/components/grid/default.scss
packages/x-components/src/design-system/components/result/default.scss

EX-5239
The idea is to stretch the `grid__item`s inside the `x-grid`, to allow set all the items with the same height.

fix(design-system): Fix grid styles to stretch cells.

---

packages/x-components/src/main.ts
packages/x-components/src/views/Layout.vue
packages/x-components/src/views/base-config.ts
packages/x-components/tests/e2e/cucumber/common-steps.spec.ts
packages/x-components/tests/e2e/cucumber/identifier-results/identifier-results.feature
packages/x-components/tests/e2e/cucumber/identifier-results/identifier-results.spec.ts

[EX-5247]
The Identifier Result doesn't work when X-components are served.
The problem is the `baseInstallXOptions` were not used, because it was always overridden by the config coming from URL (empty object {} if not present), then the Identifier Result Regexp was not right.
- Refactored the Identifier Results in the layout.
- Refactored the Identifier Results E2E tests.
[EX-5247]: https://searchbroker.atlassian.net/browse/EX-5247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(identifier-results): Fix default plugin config.

---

packages/x-components/src/components/sliding-panel.vue
packages/x-components/tests/unit/sliding-panel.spec.ts

BREAKING CHANGE: `SlidingPanel` buttons do not have the round variant set by default.
EX-5233
Exposes a prop for adding CSS classes to the buttons inside the `SlidingPanel`. The main use case for this is adding variant classes of our design system.

feat(components): add `buttonClass` prop in `SlidingPanel`

---

packages/x-components/src/x-modules/url/components/url-handler.vue
packages/x-components/tests/e2e/cucumber/url/url.feature
packages/x-components/tests/e2e/cucumber/url/url.spec.ts

EX-5203
Makes the `URLHandler` component use the initial extra params when parsing the URL params. This fixes the issue where selecting an extra param and navigating back (so the default value is selected again), wasn't restoring its value properly.

fix(url): default extra params are now properly restored

---

packages/x-components/src/components/result/__tests__/base-result-add-to-cart.spec.ts
packages/x-components/src/components/result/base-result-add-to-cart.vue

EX-5323
The point of this PR is to allow to add listeners to the `BaseResultAddToCart`. Without this we can't add a listener to the button in the Customer project:
```html
<BaseAddToCart @click="doStuff">Add To Cart</BaseAddToCart>
```

feat(components): Make `BaseResultAddToCart` to use the outter listeners.

---

packages/x-components/src/components/__tests__/snippet-callbacks.spec.ts
packages/x-components/src/components/snippet-callbacks.vue
packages/x-components/src/wiring/events.types.ts

EX-5324
Until now, the event  `SnippetCallbackExecuted`, emitted after a callback execution, only passed the event name and the callback return. But sometimes it's necessary also to know the original payload and metadata.
So this PR is to fix that.

feat(components): Add `payload` and `metadata` to the `SnippetCallbackExecuted` event payload.

---

packages/x-components/src/views/home/Home.vue
packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

With this approach instead of using multiple ExtraParams component, only one SnippetExtraParams component will be used. So to test it, just launch the server and see how the extra params are loaded and emitted correctly, you can try to add more values at home.vue in:
` protected initialExtraParams = { store: 'Portugal' };`
to check that you can add more params and they will be combined with snippet one.
EX-5205

fix: merge extra params with snippet extra params

---

packages/x-components/build-helpers/plugins/polyfills-wrapper.plugin.js
packages/x-components/build-helpers/utils/polyfills.util.js
packages/x-components/src/plugins/x-plugin.ts
packages/x-components/src/x-modules/related-tags/wiring.ts

This PR enhances the rollup plugin polyfills-wrapper to be compatible with dynamic imports. It also modifies the plugin to work with lazy loaded modules. See https://github.com/empathyco/x-archetype/pull/66
This has to be tested along with the archetype branch from https://github.com/empathyco/x-archetype/pull/66.

feat(EX-5278): build archetype in chunks

---

.github/workflows/build.yml

EX-5357
Avoid overlapping multiple executions of the `build` `workflow`.
We've tested this option in a dummy repository and seems to be working as expected.

ci: add `concurrency` option to `build` `workflow`

---

packages/search-adapter/src/empathy/requestors/beacon-tracking.requestor.ts

[EX-5372](https://searchbroker.atlassian.net/browse/EX-5371)
Tracking requests are being blocked by ad blocked (specifically uBlock) because they're of type `ping`. We're using `sendBeacon` for these requests and due to its nature, it's not trivial to know when the request is being blocked.
We opted for detecting when an adblock is present by sending a regular request with `fetch` to an URL that will be blocked. If an ad blocked is present then instead of sending the beacon we use a regular fetch.
This change is aimed to solve issues in clients, so the test done was:
* Take a client's project (`x-massimoduti` for example)
* Add the local `x-adapter` as a dependency
* Override the adapter configuration so it uses the `x-adapter` `BeaconTrackingRequestor`
````javascript
configureAdapter
... …
```

feat(search-adapter): detect adblockers and use fetch instead of beacon for tracking when present

---

packages/x-components/package.json

EX-5396
The CSS imported in a js file is removed from the build of the Archetype and Setup projects due to the treeShaking. To avoid this, we have to indicate in the `sideEffects` property of the `package.json` of the XComponents, what imported files to include even they are not used directly in the code. Like what happens with the CSS:
As you can see in the previous screenshot, the CSS is imported but not used directly in the code. So Rollup take this out from final build when it does the "treeShaking".
The `"**/*.scss.js"` is added to indicate to the build of the projects that use XComponents, to include this files from XComponents. The `.js` is added because what is actually built in XComponents are JavaScript files including the CSS.

fix(build): Fix build side effects to include css.

---

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts
packages/x-components/src/plugins/x-plugin.alias.ts
packages/x-components/src/plugins/x-plugin.types.ts

Go to any component and inside a function write the following code:
`this.$x.scroll['main-scroll'].WHATEVER` check the different values that it is offering. You can print these values to check that everything is working as expected when you use the scroll.
Or you can add it in the scroll.vue component, inside the emitScroll function:
` protected emitScroll(position: number): void {
console.log(this.$x.scroll['main-scroll'].hasReachedStart);
this.$x.emit('UserScrolled', position, this.createEventMetadata());
}`
EX-5249

feat(scroll): add scroll data state to the alias API

---

packages/x-adapter-platform/README.md
packages/x-adapter-platform/package.json
packages/x-adapter-platform/tsconfig.eslint.json
packages/x-adapter-platform/tsconfig.json
packages/x-adapter/README.md
packages/x-adapter/package.json
packages/x-adapter/tsconfig.eslint.json
packages/x-adapter/tsconfig.json

EX-5310
Create new empty `x-adapter` (`@empathyco/x-adapter-next` until we can get rid of the current adapter) and `x-adapter-platform` packages.

chore: create empty `x-adapter` (`x-adapter-next`) and `x-adapter-platform` packages

---

packages/search-types/src/suggestion.model.ts
packages/x-components/src/components/suggestions/base-suggestion.vue
packages/x-components/src/design-system/components/suggestion/default.scss
packages/x-components/src/design-system/components/suggestion/default.tokens.scss
packages/x-components/src/views/design-system/design-system-suggestion-group.vue
packages/x-components/src/views/design-system/design-system-suggestion.vue

[EX-5290](https://searchbroker.atlassian.net/browse/EX-5290)
The curated variant had to be added to the next queries in the design system. To do this be opted to make this general to all suggestions. And in a similar fashion to what was done in [EX-5088](https://searchbroker.atlassian.net/browse/EX-5088).
New sub-sections were added to the Suggestions section in the Design System layout. Any change in the tokens for the curated suggestions will be reflected there and only affect curated suggestions.

feat(design-system): add curated variant to the suggestion

---

packages/x-components/src/views/home/Home.vue
packages/x-components/src/x-modules/facets/components/clear-filters.vue
packages/x-components/src/x-modules/facets/components/facets.mixin.ts
packages/x-components/src/x-modules/facets/components/facets/facets.vue
packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters-list.spec.ts
packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters.spec.ts
packages/x-components/src/x-modules/facets/components/lists/selected-filters-list.vue
packages/x-components/src/x-modules/facets/components/lists/selected-filters.vue
packages/x-components/src/x-modules/facets/facets.mixin.ts
packages/x-components/src/x-modules/facets/index.ts
packages/x-components/src/x-modules/facets/store/getters/selected-filters-by-facet.getter.ts

BREAKING-CHANGE: change the prop facetId to facetsIds in `selected-filters.vue` and `selected-filters-list.vue`, now it will be an array of facets ids instead of just one facet id.
EX-2899
We want to share logic between components that have repeated code. We saw that `selected-filters.vue` and `selected-filters-list.vue` have a prop `facetId` but in the other components is facetsIds, because in these other components we can use an array of facets ids instead just one. So to change that, we change the prop from facetId to facetsIds in those components that are receiving just one facetId to make them work with an array of facets ids. With this change we can reduce the code and share more logic between components.
Running the test and seeing how everything is still working.

feat(facets): add facets mixin to share logic between components

---

packages/x-components/tests/e2e/cucumber/extra-params.feature

The aim of this PR is to create a couple of tests checking that the extra-params are sent in the search request as expected. For this purpose, in `Home.vue` we have 2 different types of extra-params combined:
- SnippetConfigExtraParams: `store = 'Portugal'`
- RenderlessExtraParams: during test execution (2nd scenario) store value is changed from `'Portugal'` to `'Spain'`
The reasons why ExtraParams is not added are the following:
They are not supposed to co-exist. Whether the client uses SnippetConfigExtraParams or ExtraParams.
SnippetConfigExtraParams is build on the top of ExtraParams.
Existing component tests should cover the different scenarios.
Forcing them to co-exist causes a side effect, adding to the URL the extra-param coming from the snippet.
As usual, change line 11 in …

[EX-5377] Add extra-params test

---

packages/x-components/src/x-installer/api/__tests__/default-api.spec.ts
packages/x-components/src/x-installer/api/api.types.ts
packages/x-components/src/x-installer/api/base-api.ts
packages/x-components/src/x-installer/x-installer/x-installer.ts
packages/x-components/src/x-modules/extra-params/components/extra-params.vue
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

EX-5384
Adding a `setSnippetConfig` function in the API in order to modify the `snippetConfig`. The implementation is found in the `XInstaller` but it gets exposed in the API throughout a facade. Also:
- Had to change the payload in the `ExtraParamsInitialized` to be a clone of the object instead. This avoids having this reference in the store, and we can change the `extraParams` properties without `Vuex` complaining.
- Changed the priority of how the `SnippetConfigExtraParams` adds properties in the `extraParams` object.

Feature/EX-5384: Add setSnippetConfig function in the API

---

packages/x-components/tests/e2e/cucumber/filters/clear-filters.spec.ts
packages/x-components/tests/e2e/cucumber/history-queries.feature
packages/x-components/tests/e2e/cucumber/scroll.spec.ts

After running the E2E several times with different throttling, it was observed that 3 different tests were randomly failing in Firefox:
- Clear selected filters → Scenario 3. Remove single filter.
- History queries component → Scenario 6. Number and order of rendered history queries.
- Scroll → Scenario 1. Scroll is kept in the URL.
After analyzing each scenario, minor changes were needed.
As usual, please change line 11 in `cypress.json` for the following to run the tests independently:
`  "testFiles": ["cucumber/**/*.feature"],`

[EX-5525] Review E2E tests in Firefox

---

packages/x-adapter/jest.config.js
packages/x-adapter/package.json
packages/x-adapter/src/index.ts
packages/x-adapter/src/utils/__tests__/interpolate.spec.ts
packages/x-adapter/src/utils/interpolate.ts
packages/x-adapter/tsconfig.json

Adds a small utility to interpolate parameters in the `endpoint` field of each one of the `EndpointAdapter`.

feat(utils): add `interpolate` function

---

packages/x-components/src/x-modules/history-queries/components/__tests__/my-history.spec.ts
packages/x-components/src/x-modules/history-queries/components/history-queries.vue
packages/x-components/src/x-modules/history-queries/components/index.ts
packages/x-components/src/x-modules/history-queries/components/my-history.vue

The component is the same as history-queries component. I was talking with @javieri-empathy about the implementation, he thinks that it is better to leave it as it is, because in the future we will change the components list or we will improve the my-history component, and maybe the template will be different.
If you are not happy with this, we can extend one component with the other one to avoid using the same template again. With this approach, we will lose the data-test and the class.
` export default class MyHistory extends HistoryQueries `
EX-3582

feat(history-queries): add `my-history` component 

---

packages/x-components/src/x-modules/history-queries/events.types.ts
packages/x-components/src/x-modules/history-queries/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/history-queries/store/actions/set-history-queries.action.ts
packages/x-components/src/x-modules/history-queries/store/actions/toggle-history-queries.action.ts
packages/x-components/src/x-modules/history-queries/store/constants.ts
packages/x-components/src/x-modules/history-queries/store/module.ts
packages/x-components/src/x-modules/history-queries/store/types.ts
packages/x-components/src/x-modules/history-queries/wiring.ts

The goal of this PR is to create an action that allows to enable or disable the HistoryQueries feature for the end user of the layer. When disabling, the current history queries will be deleted from the local storage and won't be seen by the end user. No new history queries will be created until the user enables this feature again.
This change will be stored in the localStorage. As we haven't decided yet where to recover this value when the page loads, I set it in the state itself.
The best way to try to emit somehow a `UserToggledHistoryQueries` event in any part of the code. You can pass a `boolean` value to it and see if the history queries are enabled or disabled.
---

feat(history-queries): add toggle to enable/disable the feature

---

packages/x-components/src/components/currency/__tests__/base-currency.spec.ts
packages/x-components/src/components/currency/base-currency.vue
packages/x-components/src/components/result/base-result-previous-price.vue

[EX-5649](https://searchbroker.atlassian.net/browse/EX-5649)
The `base-result-previous-price` was sending a format by default to the `base-currency` component, this format was taking priority over the injected format. Per the task, the priority order for the format to apply should be prop -> injected -> default. Given this, the decision was to move the default value of the format to `base-currency` and adjust the priorities.
Add `base-result-previous-price` to a result in a view, the default format is applied.
Pass a format for the prop. This should be the format applied.
Inject a different format to that result, the format of the prop should still apply.
Remove the prop format, the injected format should apply.

fix(base-currency): format preference goes prop to injected to default

---

packages/x-components/src/x-modules/history-queries/components/clear-history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-query.vue
packages/x-components/src/x-modules/next-queries/components/next-queries-list.vue
packages/x-components/src/x-modules/next-queries/components/next-queries.vue
packages/x-components/src/x-modules/next-queries/components/next-query.vue
packages/x-components/src/x-modules/popular-searches/components/popular-search.vue
packages/x-components/src/x-modules/popular-searches/components/popular-searches.vue
packages/x-components/src/x-modules/query-suggestions/components/query-suggestion.vue
packages/x-components/src/x-modules/query-suggestions/components/query-suggestions.vue
packages/x-components/src/x-modules/related-tags/components/related-tag.vue
packages/x-components/src/x-modules/related-tags/components/related-tags.vue
packages/x-components/src/x-modules/search-box/components/clear-search-input.vue
packages/x-components/src/x-modules/search-box/components/search-button.vue
packages/x-components/src/x-modules/search-box/components/search-input.vue

Hello✖️  team! I prepared some **Live examples** through various components that are working right now in the eDocs portal. 
I would divide them in:
- Examples activated without further changes needed:
- Examples where proposed some context changes (to match new API, juguettos --> Platform API, for example):
- Examples where added the `<script>` tag to match the new format of the examples, included imports, `SearchInput` to test it out, basic data, etc. (but didn't need further changes)
- Examples where proposed important changes to the given example
This is created as a start point facilitated by eDocs to start activating again **Live examples** in the components documentation (and search for improvements by our own).
Our idea is to start delegating this effort in X team, giving you …

docs: activating ready live-examples

---

.gitignore

This just removes the parcel cache generated from running the react-wrapper tests from the version controlled files

chore: add `.parcel-cache` to `.gitignore`

---

packages/x-adapter/src/__tests__/endpoint-adapter.factory.spec.ts
packages/x-adapter/src/endpoint-adapter.factory.ts
packages/x-adapter/src/mappers/schema-mapper.factory.ts
packages/x-adapter/src/types/http-client.types.ts

Show a warning if a schema cannot be applied and remove union type with undefined from return type.
EX-5926

refactor(schema): remove undefined from return type of mapper factory

---

packages/tailwindcss-x/package.json

EX-5939
Tailwind package was trying to be published from the `tailwindcss-x/dist` directory, check [this error for more info](https://github.com/empathyco/x/runs/6112249204?check_suite_focus=true#step:7:145), which doesn't have a valid `package.json`. Now it is published from the `tailwindcss-x` folder.

build: fix publish

---

packages/x-components/src/x-modules/url/components/__tests__/url-handler.spec.ts
packages/x-components/src/x-modules/url/components/url-handler.vue

EX-5207
Normalize `+` characters into `%20` for spaces when updating the `url`
Add a new unit test case

bugfix(url): normalize `+` characters into `%20` for spaces

---

packages/x-components/jest.config.js
packages/x-components/vue-preprocessor.js

We were investigating a little bit, we found this [workaround](https://github.com/vuejs/vue-jest/issues/448) but we should try to find another solution in the future (maybe we can try to find the problem in [vue-jest ](https://github.com/vuejs/vue-jest/tree/master/packages/vue2-jest)and create a pr)
The problem is related to the source maps, they are not linked with the source code.
EX-5325

fix: unnable to add breakpoints in vue components

---

packages/search-adapter/src/empathy/__tests__/adapter/empathy-adapter-search.spec.ts
packages/search-adapter/src/types/response.types.ts
packages/x-components/src/components/__tests__/base-grid.spec.ts
packages/x-components/src/components/__tests__/base-variable-column-grid.spec.ts
packages/x-components/src/views/ResultApp.vue
packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts

EX-5976
The API has changed unexpectedly and when the searched query does not have any banner or promoted, they are not even defined in the response object (previously they were defined as []).
In order to avoid problems in the future or in case this is not rollbacked in the backend, we should make both banners and promoted optional.
Added new unit test case.

feat(search): make `banners` and `promoteds` optionals in `SearchResponse`

---

packages/x-components/src/x-modules/facets/components/filters/__tests__/hierarchical-filter.spec.ts
packages/x-components/src/x-modules/facets/components/filters/__tests__/number-range-filter.spec.ts
packages/x-components/src/x-modules/facets/components/filters/__tests__/simple-filter.spec.ts
packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
packages/x-components/src/x-modules/facets/components/filters/number-range-filter.vue
packages/x-components/src/x-modules/facets/components/filters/simple-filter.vue

EX-5986
Exposed `@Prop() clickEvents` in filters component using a `RenderlessFilter` so the events emitted on clicked are configurable.
Added new unit test cases.

feat(facets): expose `clickEvents` as a `prop` in filters components using a `RenderlessFilter`

---

packages/x-components/src/x-modules/tagging/wiring.ts
packages/x-components/tests/e2e/tagging.feature
packages/x-components/tests/e2e/tagging/tagging.spec.ts

EX-5898
We want to detect `addtocart` as an interaction of the user to improve `findability`, so we also need to track the `click` event when an add to cart button is clicked.
Added new step in the add to cart tagging scenario.

bugfix(tagging): track click event on add to cart click

---

packages/x-components/src/main.ts
packages/x-components/src/x-modules/facets/entities/__tests__/factory.spec.ts
packages/x-components/src/x-modules/facets/entities/filter-entity.factory.ts
packages/x-components/src/x-modules/facets/service/__tests__/facets-service.spec.ts

BREAKING CHANGE: The method `registerFilterModifier` from `FilterEntityFactory` renamed to `registerModifierByFacetId`.
EX-6160
The intention of this PR is to add another option to register `FilterEntityModifier`s by `FilterModelName`.
The current way to register by Facet id is kept but renamed.
The use case is when you don't know the facets, therefore the facets ids, but you need to make single selectable the Hierarchical Filters, for example. This is a real case for Motive.

feat(facets): Add `FilterModify` by `FilterModelName`.

---

packages/x-components/src/x-modules/related-tags/store/actions/set-url-params.action.ts
packages/x-components/tests/e2e/common/common-steps.spec.ts
packages/x-components/tests/e2e/related-tags.feature
packages/x-components/tests/e2e/url/url.spec.ts

EX-6131
Before this PR:
1. Search for something with related tags
2. Select a filter
3. Navigate back
4. Related tags disappear
By just removing the `setRelatedTags` mutation call with an empty array, this works as expected, and if related tags are shared between different queries we should see them animate.
If someone complains about the user being able to select wrong related tags while they are loading between navigations, I would disable them so they are not clickable. However I see this as an edge use case.

fix(related-tags): Related tags are now kept when navigating back.

---

packages/x-adapter/src/__tests__/endpoint-adapter.factory.spec.ts
packages/x-adapter/src/endpoint-adapter.factory.ts
packages/x-adapter/src/types/adapter.types.ts

BREAKING-CHANGE: Split `EndpointAdapter` type into `EndpointAdapter` and `ExtendableEndpointAdapter`.
EX-6121
Allow creating `endpointAdapters` without having to implement the `extends` logic.

feat: add `extendableEndpointAdapterFactory`

---

packages/x-adapter/src/mappers/__tests__/schema-mapper.factory.spec.ts
packages/x-adapter/src/mappers/schema-mapper.factory.ts

EX-6217
applySubsSchemaTransformer implementation allows $context props to only be source property paths. We also need to be able to pass normal values (a number, boolean, string, etc). In order to make things easier, we will only allow these normal values to be passed through functions.## Type of change
Refactored unit test case adding this functionality.

feat(mappers): allow passing raw values to `subSchema.$context` pros using functions

---

packages/x-adapter-platform/src/__tests__/__fixtures__/search.response.ts
packages/x-adapter-platform/src/__tests__/platform.adapter.spec.ts
packages/x-adapter-platform/src/mappers/responses/search-response.mapper.ts
packages/x-adapter-platform/src/schemas/facets/__tests__/utils.spec.ts
packages/x-adapter-platform/src/schemas/facets/index.ts
packages/x-adapter-platform/src/schemas/facets/types.ts
packages/x-adapter-platform/src/schemas/facets/utils.ts
packages/x-adapter-platform/src/schemas/filters/number-filter.schema.ts
packages/x-adapter-platform/src/schemas/filters/simple-filter.schema.ts
packages/x-adapter-platform/src/schemas/index.ts
packages/x-adapter-platform/src/schemas/models/facet.schema.ts
packages/x-adapter-platform/src/types/models/facet.model.ts

[EX-6205](https://searchbroker.atlassian.net/browse/EX-6205)

fix(schemas): flatten hierarchical filters

---

.github/workflows/edocs-synchronization.yml

EX-6255
Added input parameter with two choices to select `all` or `static` and synchronize all the documentation or  just the static. It can be seen working here in [this fork](https://github.com/herrardo/x)
The purpose of the change is to provide a way to only sync the `static-docs` folder instead of all the generated docs. For that a new choice input param has been added to the workflow. Depending on the param two different actions would be called in the [docs-empathy-documentation](https://github.com/empathyco/docs-empathy-documentation/) repository
Regular workflow to sync all docs: https://github.com/empathyco/docs-empathy-documentation/blob/main/.github/workflows/trigger_synchronize_x.yml
Workflow to sync only static docs: https://github.com/empathyco/docs-empathy-documentation/blob/ …

feat(ci): add option to synchronise only the  `static-docs`

---

packages/x-components/src/x-modules/facets/components/facets.mixin.ts
packages/x-components/src/x-modules/facets/components/facets/__tests__/facets.spec.ts
packages/x-components/src/x-modules/facets/components/facets/facets.vue

EX-6433
In the Facets component, besides having a default slot, and a slot by facet id, it also necessary to have an slot by facet type (ModelName), this way we can configure it for dynamic facets, when we don’t know what facet will come, but we do what kind.

feat(facets): Add slot by Facet ModelName.

---

packages/x-adapter-platform/src/endpoint-adapters/tagging.endpoint-adapter.ts
packages/x-adapter-platform/src/mappers/requests/__tests__/tagging-request.mapper.spec.ts
packages/x-adapter-platform/src/mappers/requests/tagging-request.mapper.ts
packages/x-adapter-platform/src/schemas/requests/index.ts
packages/x-adapter-platform/src/schemas/requests/tagging-request.schema.ts
packages/x-adapter/src/http-clients/__tests__/beacon.http-client.spec.ts
packages/x-adapter/src/http-clients/__tests__/fetch.http-client.spec.ts
packages/x-adapter/src/http-clients/__tests__/utils.spec.ts
packages/x-adapter/src/http-clients/beacon.http-client.ts
packages/x-adapter/src/http-clients/fetch.http-client.ts
packages/x-adapter/src/http-clients/types.ts
packages/x-adapter/src/http-clients/utils.ts

EX-6450
Add sendParamsInBody to the x-adapter RequestOptions
The idea is to send parameters in the body instead in the url of the request if this new sendParamsInBody option is true

feat(x-adapter): Add `sendParamsInBody` option to `RequestOptions`

---

packages/x-components/src/components/__tests__/base-switch.spec.ts
packages/x-components/src/components/base-switch.vue
packages/x-components/src/components/index.ts

EX-6004
Adds the `BaseSwitch` component.
- Does not handle its own selected state
- Supports v-model
- 3 sizes (default, sm and lg). This sizes use the closest token values
- Uses CSS variables internally to simplify styling size and background
To test it you can replace the checkbox control of the `Home.vue` **instant search** with the new switch component:
```html
<li class="x-test-controls__item x-list__item">
<label>
search-input - instant
<BaseSwitch v-model="controls.searchInput.instant" id="search-input-is-instant" />
</label>
</li>
```

feat(components): add `BaseSwitch` component.

---

packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md

Adds the type="module" to the x archetype scripts so they can be integrated by the clients.

docs: Add module type to integration script docs

---

packages/x-components/src/x-modules/history-queries/components/my-history.vue

binds `formatTime` function to allow formatting dates when overriding slot content.
EX-6611

feat(my-history): bind `formatTime` to `suggestion-content` slot

---

packages/x-components/src/views/pdp.vue
packages/x-components/src/x-installer/x-installer/__tests__/x-installer.spec.ts
packages/x-components/src/x-installer/x-installer/x-installer.ts
packages/x-components/static-docs/build-search-ui/web-archetype-development-guide.md
packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md

BREAKING-CHANGE: `XAPI` is now available now at `window.InterfaceX`.
EX-6645
Renames X to InterfaceX so it is less likely to collide with customer clients.

feat: Move `XAPI` from `window.X` to `window.InterfaceX`

---

packages/x-translations/src/csv-to-json.ts

[EX-6631](https://searchbroker.atlassian.net/browse/EX-6631)
After the Kenay and Izas setups we found some issues with the `csv-to-json` scripts. 
The first issue was extra `"` on some messages. In this case, the issue didn't come from the script but from the CSV provided by the customers.
The second one was the script inserting `\r` in some points of the JSON and in messages that should be empty. This was caused by the format of the exports of the "Numbers" program. Instead of ending the CSV line with just `\n` it ends them with `\r\n`
Grab the example CSV file `it.messages.csv` from the task and use the script on it (I changed the source file from the script's test to do so). Test the result with and without the change of the PR applied.

fix(translations): Fix '\r' issue on csv-to-json script

---

packages/x-components/src/components/layouts/single-column-layout.vue

It seems that the pointer events are not needed in the aside layout.
I have tested this in the archetype and the Kenay setup and all is working as it should.
This PR fixes the scroll bug of the selected filters in mobile view.
The pointer events are still needed in the predictive layer because it is being always rendered.
To test this:
- Open [this](https://x.staging.empathy.co/x-kenay/index.html?filter=currentPrice%3A200.0-400.0&filter=previousPrice%3A200.0-400.0&filter=height%3A45%2C6%20cm&query=sofa) link in staging in mobile view, the scroll of the selected filters should not be working.
- Make an `npm run install:local` with the new version of X Components in the Kenay setup.
- With the same request, the scroll should be working now.
EX-6595

fix: scrolling problems in single column aside layout

---

packages/x-components/src/x-modules/history-queries/components/__tests__/history-queries-switch.spec.ts
packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue

feat(history-queries): disable `MyHistory` without confirmation when the history queries list is empty

---

packages/x-adapter/src/http-clients/__tests__/fetch.http-client.spec.ts
packages/x-adapter/src/http-clients/fetch.http-client.ts

MOTPRD-7732
This PR modifies the fetch HTTP client to not flatten the parameters object when it is sent in the body of the request.

feat: Do not flatten body params in fetch http client.

---

packages/x-components/src/components/modals/__tests__/base-id-modal-close.spec.ts
packages/x-components/src/components/modals/base-id-modal-close.vue

[EX-6726](https://searchbroker.atlassian.net/browse/EX-6726)
Some cases required closing modals from different parts of the code by elements that weren't always simple buttons. The old `BaseIdModalClose` didn't allow that so we're changing it to make it more configurable and maintain retro compatibility.
Create a new element to close an id modal by using `BaseIdModalClose` and override the slot content. Check that everything is working.
Also, a new test for this functionality was created.

feat(components): make `BaseIdModalClose` rendering configurable

---

packages/x-components/src/x-modules/search-box/components/search-input.vue
packages/x-components/static-docs/build-search-ui/web-how-to-use-x-components-guide.md

EX-6816
Clarifies how the XEvents emission works in X-Components. Suggests using GlobalXBus instead.

docs: clarify how to subscribe to any `XEvent`.

---

packages/search-types/src/result/result.model.ts
packages/x-components/src/components/__tests__/items-list.spec.ts
packages/x-components/src/components/result/__tests__/base-result-current-price.spec.ts
packages/x-components/src/components/result/__tests__/base-result-link.spec.ts
packages/x-components/src/components/result/__tests__/base-result-previous-price.spec.ts
packages/x-components/src/components/result/base-result-current-price.vue
packages/x-components/src/components/result/base-result-image.vue
packages/x-components/src/x-modules/identifier-results/components/__tests__/identifier-results.spec.ts
packages/x-components/src/x-modules/identifier-results/components/identifier-result.vue
packages/x-components/src/x-modules/next-queries/components/__tests__/next-query-preview.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/results-list.spec.ts

EX-6760
BREAKING CHANGE: `Result` model properties are optional, except `id`, `modelName`, and `tagging`. 
In order to support result variants:
- Now the `Result` properties are optional, except `id`, `modelName`, and `tagging`.
- A result variant can contain more variants.
- As result properties now are optional, I'm not defining a variant as a `Partial<Result>`, let me know if you feel it should be a partial result.

feat(result): add variants support

---

packages/x-components/src/x-modules/next-queries/components/__tests__/next-query-preview.spec.ts
packages/x-components/src/x-modules/next-queries/components/next-query-preview.vue

EX-6820
Add `maxItemsToRender` prop to `NextQueryPreview` component to limit the rendered number of items.

feat(next-queries): add `maxItemsToRender` prop to `NextQueryPreview` component

---

packages/x-components/src/x-installer/api/api.types.ts
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

EX-6849
Modifies the `SnippetConfig` types and the `SnippetConfigExtraParams` to support adding a list of queries to preview.

feat: add `queriesPreview` option to snippet config

---

.github/workflows/build.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/release-alpha.yml

[EX-6308](https://searchbroker.atlassian.net/browse/EX-6307)
PRs from outside the project (specifically from forks) we're failing at the build step because they tried to access a token they didn't have access tot. This token isn't necessary for the workflow, so it has been removed.
Fork the repo and open a PR from the fork to main with the fix applied. The workflow should work.

fix: remove unnecessary token from github action allowing PRs from forks

---

.github/workflows/build.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/release-alpha.yml

EX-6308
Given the `main` branch is write protected the `build` workflow will fail on `main` branch on the `release-alpha` step since it is not possible to push the release commit to main. See https://github.com/empathyco/x/runs/7991088722?check_suite_focus=true
I'm adding this token back until we find a better solution.

fix(ci): add `support_token` when checking out repository 

---

packages/x-components/CHANGELOG.md
packages/x-components/package-lock.json
packages/x-components/package.json

EX-6896
After the merge of #669 there was a problem with the `x-components` release `3.0.0-alpha.157` and the version was not updated on the package.json. This PR fixes this.

fix: conflict version

---

packages/x-components/src/components/result/__tests__/result-variants-provider-and-selector.spec.ts
packages/x-components/src/components/result/result-variants-provider.vue

- auto select the first variant of all the levels by default
- add autoSelectDepth prop to limit the auto selection of variants when the provider is rendered
EX-6878

feat(components): variants auto selection

---

.github/actions/release-alpha/action.yml
.github/workflows/build.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/release-alpha.yml

EX-6308 
I have removed the `SUPPORT_TOKEN` from the `git checkout` step on the different workflows since it is not needed. In order to be able to push the alpha release commits to the write protected `main` branch I have configured the [github-push-action](https://github.com/ad-m/github-push-action). This action allows the `release-alpha` action to push to the main branch with the `SUPPORT_TOKEN` so it can bypass the write protection rule.
In case you want to take a look at a working example,  I have tested this configuration here: https://github.com/diegopf/gh-actions-playground. Feel free to fork and submit a silly PR there so we can test the external contributors issue.
I also took the chance to update the [github-checkout-action](https://github.com/actions/checkout) version.
An …

chore(ci): review GitHub action tokens

---

packages/x-components/src/x-modules/queries-preview/config.types.ts
packages/x-components/src/x-modules/queries-preview/events.types.ts
packages/x-components/src/x-modules/queries-preview/index.ts
packages/x-components/src/x-modules/queries-preview/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/queries-preview/store/__tests__/utils.ts
packages/x-components/src/x-modules/queries-preview/store/actions/fetch-and-save-query-preview.action.ts
packages/x-components/src/x-modules/queries-preview/store/actions/fetch-query-preview.action.ts
packages/x-components/src/x-modules/queries-preview/store/index.ts
packages/x-components/src/x-modules/queries-preview/store/module.ts
packages/x-components/src/x-modules/queries-preview/store/types.ts
packages/x-components/src/x-modules/queries-preview/wiring.ts

[EX-6844](https://searchbroker.atlassian.net/browse/EX-6844)
Added wiring and actions to the `queries-preview` module.
- The module's state now stores a dictionary of `QueryPreviewItems`, where each item contains, mainly, the results of a specific query and the request used for the search.
- `fetchQueryPreview` and `fetchAndSaveQueryPreview` actions have been added in order to perform the request and save the results, and the request, used for the search.
- Whenever the `QueryPreviewRequestChange` is emitted, a search will be performed with the passed request.
> The component described by [EX-6845](https://searchbroker.atlassian.net/browse/EX-6845) will be in charge of emitting this event if the `extraParams` change.
- `QueryPreviewRemoved` event will remove the entry of a specific query …

feat(queries-preview): add wiring and actions

---

package-lock.json
packages/react-wrapper/package.json
packages/x-components/build/rollup.config.ts
packages/x-components/package.json

EX-6918
The recent Vue 2.7 release breaks some things. Until we fix them, X-Components is only compatible with the 2.6.x version. To avoid accidental updates, we are setting `Vue` and `Vuex` as `peerDependencies` (we want to make sure we use the version installed by the user project), and setting them also as `devDependencies` with minor versions for our local development.

build(dependencies): fix Vue & Vuex versions

---

packages/x-components/src/views/home/Home.vue
packages/x-components/src/x-modules/next-queries/components/__tests__/next-queries.spec.ts
packages/x-components/src/x-modules/next-queries/components/next-queries.vue

EX-6955
Previously, the grid of the home view was rendering next queries from the state. Each next queries list contained the same queries. It should render the next queries coming from the grid `NextQueriesList` group. This component was also limiting to 3 rendered next queries, which was confusing with the default 4 next queries per group.
This is easily solved by using the `BaseSuggestions` component rather than the `NextQueries` one, which didn't support passing the next queries to render.

fix: Make `Home` grid next queries use grid data rather than state data.

---

packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts

EX-6894
Adds a mutation to update the result info.

feat(search): add `updateResult` mutation

---

packages/x-utils/src/__tests__/object.spec.ts
packages/x-utils/src/object.ts

EX-7103
Adds a rename utility, needed to ease the tailwind package object operations.
This utility for now prefixes and suffixes the first level of the given object keys. Using a mapper function would have been much more powerful, but that brings issues when typing the new object, as functions are much more complex.

feat: Add `rename` utility

---

packages/x-components/src/views/home/Home.vue
packages/x-components/src/x-modules/next-queries/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/next-queries/store/actions/fetch-and-save-next-query-preview.action.ts
packages/x-components/src/x-modules/next-queries/store/actions/fetch-next-query-preview.action.ts
packages/x-components/src/x-modules/next-queries/store/types.ts
packages/x-components/src/x-modules/next-queries/wiring.ts

[EX-6757](https://searchbroker.atlassian.net/browse/EX-6757)
- Modify `fetchAndSaveNextQueryPreviewWire` to send both the `query` and the `location` in the request.
- Update store `fetchAndSaveNextQueryPreview`and `fetchNextQueryPreview` actions & its types.
- Update tests.
- Create a test for an undefined location use case
Enable sending an `origin` for this feature to be tracked.

Add origin to Next Queries Preview

---

package.json
packages/x-components/package.json

Avoids jest from printing console statements (only our logs and in jest for the CI). This should avoid noise and speed up the tests as logging is suprisingly expensive.

ci: silent jest and eslint warnings

---

packages/x-components/src/components/modals/__tests__/base-modal.spec.ts
packages/x-components/src/components/modals/base-modal.vue
packages/x-components/src/services/directional-focus-navigation.service.ts
packages/x-components/src/utils/focus.ts
packages/x-components/src/utils/index.ts

EX-6755
When opening modals (namely the `MyHistory` one) the focus could still be behind the modal, which is weird.
There are new unit tests for the new prop in the `base-modal` component.

fix(base-modal): add prop to allow the modal to move the focus to an element within it on open

---

packages/x-components/src/adapter/e2e-adapter.ts
packages/x-components/src/adapter/mocked-responses.ts
packages/x-components/src/views/adapter.ts
packages/x-components/src/views/base-config.ts
packages/x-components/src/views/home/Home.vue
packages/x-components/src/views/home/types.ts
packages/x-components/tests/e2e/common/mocked-responses.spec.ts

EX-7073
The `e2eAdapter` can't be used outside cypress directly. This adapter makes requests that cypress will intercept and resolve with mocked data. In order to workaround this issue, in this PR I prevent the `e2eAdapter` from using the [mockedFetchHttpClient](https://github.com/empathyco/x/blob/feature/EX-7072-make-adapter-configurable-in-home-view/packages/x-components/src/adapter/e2e-adapter.ts#L12) if we are not in a cypress environment and return the mocked data instead.
Note: if you see an error regarding the `SlidingQueryPreview` complaining about the missing location, this will be fixed in #746

feat: make adapter configurable in home view

---

.github/workflows/codeql-analysis.yml

EX-7144
This PR enables code scanning alerts by analysing the repository code to find security vulnerabilities and coding errors. The tool used for the scanning is [CodeQL](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql) a code analysis engine developed by GitHub.
This new workflow will run on every push to the `main` branch or any PR created against this branch. If an issue is found during a PR check, we will need to handle it within the PR, either by [fixing it or dismissing](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests#viewing-an-alert-on-your-pull-request) the …

ci: enable code scanning

---

packages/x-components/src/components/sliding-panel.vue

fix: hide overflow-y in the sliding panel

---

packages/x-components/src/components/animations/animate-translate/animate-translate.style.scss
packages/x-components/src/components/animations/create-directional-animation-factory.ts

Related to https://github.com/empathyco/x/issues/385.
Translate animations must be extended to support a different direction for enter and leave so the following case is achievable (search input placeholder animation):
https://user-images.githubusercontent.com/72568818/195307148-8a0b52cb-6736-48f6-bf51-caf427c56cc7.mov
This PR is part of a specific issue and how it is used can be found [here](https://github.com/empathyco/x/pull/771/files#diff-4f94a892b7632521d53664a6cb2c3881f76f05e0bb615a6ffdf1ab29375c100aR48).

Add directional origins for translate animations

---

packages/x-components/src/components/animations/animate-translate/animate-translate.style.scss
packages/x-components/src/components/animations/create-directional-animation-factory.ts
packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts
packages/x-components/src/x-modules/search-box/components/search-input.vue
packages/x-components/src/x-modules/search-box/events.types.ts

Related to https://github.com/empathyco/x/issues/385.
In order to implement the new SearchInputPlaceholder component the hover events (mouse enter & leave) must be emitted by the SearchInput so its state is available from any other element/component.
Note: The first approach for the SearchInputPlaceholder was to directly use its hover state but as it is conceived as a span placed in the same space than the input, that would generate conflicts between the mouse events from both elements depending on which one is placed on top of the other.
This PR is part of a specific issue and how it is used can be found [here](https://github.com/empathyco/x/pull/771/files#diff-4f94a892b7632521d53664a6cb2c3881f76f05e0bb615a6ffdf1ab29375c100aR118).

Add search input hover events

---

.github/contributing/components.md

Just an improvement on how examples are formatted inside Contributing > Components.
The current preview can be found [here](https://github.com/empathyco/x/blob/main/.github/contributing/components.md#events).

Improve examples formatting on Contributing - Components

---

packages/x-tailwindcss/src/types.ts

EX-7085
Adds autocomplete functionality to the `theme` function in `TailwindHelpers` so it is easier to use it. It doesn't restrict values, as those can be extended for customers and would result in errors when doing so.
Regarding modifying the `ExtractPath` type to allow `numeric` keys, it wasn't needed, as those keys can also be used as `strings`.
In order to use this autocomplete feature in `x-components`, you can't destructure the TailwindHelpers parameter.
For example, this allows autocompletion:
But this doesn't:

feat(types): add autocomplete to `theme` function in `TailwindHelpers`

---

packages/x-archetype-utils/src/build/webpack/webpack.config.ts
packages/x-archetype-utils/src/index.ts
packages/x-components/vue.config.js

EX-7221
After creating https://github.com/empathyco/x-archetype/pull/181 @tajespasarela suggested to move the webpack fix to the `x-archetype-utils` package.  This PR exports the whole configuration for webpack so we are able to update every customer setup easily.
Besides, I introduce the same fix for the `x-components` development build. See https://github.com/empathyco/x-archetype/pull/181 if you need more context.

ci: export webpack config from `x-archetype-utils`

---

.gitignore
package-lock.json
packages/react-wrapper/.gitignore
packages/react-wrapper/package.json
packages/react-wrapper/tests/demo/index.html
packages/react-wrapper/tests/demo/vite.config.ts
packages/react-wrapper/tsconfig.json
packages/x-tailwindcss/package.json
packages/x-tailwindcss/tsconfig.json

`parcel` was giving some issues recently, autoinstalling polyfills such as `process`. As this is only used to run test, and we are already using Vite for the tailwind plugin package, I prpose to add it also there. As you can see in the package-lock, this removes a big chunk of other dependencies, which normally is a good sign.
There is a breaking change in this PR , and it is that it also changes the compilation to ES6. If you find this an issue, we can compile to ES6 only for vite, and ES5 for the build output. But to match the rest of the mono-repo, I would leave it. Note that the customer using this package does not need support anymore for older browsers with ES5.
This is part of a series of PRs to achieve the update of Cypress to 10.8.0. The [global result can be seen …

feat: replace `parcel` with `vite`

---

packages/x-components/src/components/column-picker/__tests__/base-column-picker-list.spec.ts
packages/x-components/src/components/column-picker/base-column-picker-list.vue
packages/x-components/src/components/sliding-panel.vue

The `base-dropdown` component is not being used in the `archetype`, so we can add the prop there when we need it.
EX-7224

feat: apply dynamic css mixin to sliding panel and column picker list buttons

---

packages/search-types/src/banner.model.ts
packages/search-types/src/promoted.model.ts
packages/search-types/src/schemas/banner.schema.ts
packages/search-types/src/schemas/promoted.schema.ts
packages/x-adapter-platform/src/types/models/banner.model.ts
packages/x-adapter-platform/src/types/models/promoted.model.ts
packages/x-components/src/__stubs__/banners-stubs.factory.ts
packages/x-components/src/__stubs__/promoteds-stubs.factory.ts

[EX-7333](https://searchbroker.atlassian.net/browse/EX-7333)
Position optional on Promoteds and Banners to cover the APIs which don't implement that feature.
Related to [this](https://github.com/empathyco/x/commit/e7393fbce8d0767d3c762aa714fe94e162203a12).

fix: Make Promoted and Banner position optional

---

packages/x-tailwindcss/demo/src/components/xds-button.vue
packages/x-tailwindcss/src/x-tailwind-plugin/components/button/default.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/button/sizes.ts

EX-7369
This PR:
- Changes the naming of the XDS Button from [`xs`, `sm`, `md`, `lg`] to: [ `sm`, `md`, `lg`, `xl`] to make it coherent with the next icon XDS component.
- The default size would be the new `md` so the buttons will be smaller by default.
- Also refactored the way default styles reusing the corresponding variant.
- Fixed the colors in the button showcase to use the new colors naming.

fix(design-system): Change the xds button size variants.

---

packages/x-components/src/views/base-config.ts
packages/x-components/src/x-modules/search/components/__tests__/banner.spec.ts
packages/x-components/src/x-modules/search/components/banner.vue
packages/x-components/src/x-modules/tagging/wiring.ts

EX-7339 
This change is a request from motive where the banners have tagging information. Currently in platform we don't have tagging for banners, so if you wan to test this locally you can by overriding the bannerSchema and mocking the tagging:
```
bannerSchema.$override<PlatformBanner, Partial<Banner>>({
tagging: {
click: {
url: () => 'https://localhost',
params: () => Object.assign({})
}
}
});
```

feat(tagging): track banner clicks

---

packages/x-tailwindcss/demo/src/components/xds-base-showcase.vue
packages/x-tailwindcss/demo/src/components/xds-button.vue
packages/x-tailwindcss/demo/src/components/xds-showcase.vue
packages/x-tailwindcss/demo/src/index.ts
packages/x-tailwindcss/demo/src/types/types.ts
packages/x-tailwindcss/demo/src/utils.ts

EX-7368
This PR:
- Extracts the common part of the `XdsButton` showcase component to a new `XdsBaseShowcase` component to reuse with new components like the icon.

refactor(design-system): Refactor showcase component to make it reusable.

---

packages/x-components/.gitignore
packages/x-components/src/x-installer/x-installer/__tests__/x-installer.spec.ts
packages/x-components/src/x-installer/x-installer/types.ts
packages/x-components/src/x-installer/x-installer/x-installer.ts

[MOTPRD-9239](https://searchbroker.atlassian.net/browse/MOTPRD-9239)
`domElement` in `InstallXOptions` now allows a function in addition to an element selector or a DOM element. With this change, the target element where the Vue application is gonna mount, can be a dynamic element based on the `SnippetConfig`.
At Motive, we are working on encapsulating motive-x under a shadowDOM only if an `isolated` property is activated through the `SnippetConfig`. So at runtime, we want to decide if we have to create a DOM tree for the `shadowRoot` or, on the other hand, we have to create a simple `div` based in the snippet configuration. Something like that: 
```TS
function getDomElement({ isolated }: SnippetConfig): Element {
const xDomElement = document.createElement('div');
if (isolated) {
const …
```

feat(x-installer): allow retrieving the target element for application mounting based on the snippet configuration

---

packages/x-components/src/components/animations/animations.mixin.ts

Remarks section explains why it is needed 😄
```
@remarks `content-visibility` CSS property boosts the rendering performance waiting to be
needed until rendering the content. This behaviour collides with this animation method.
When the `scrollProperty` is evaluated, the content has not been rendered yet and the value
is 0 so nothing is animated. To avoid this behaviour, we change the `content-visibility` to
default value, force a layer repaint and then, evaluate the `scrollProperty` value which
now has value. Then we restore the `content-visibility` value to its previous state.
```
Fixing this issue:
https://user-images.githubusercontent.com/10746604/201149174-598fdfad-7e23-4804-b636-76f16dd46e20.mov

fix(animations): make content-visibility CSS property and createCollapseAnimationMixin work together

---

package-lock.json
packages/x-tailwindcss/package.json

Syncs the `vite` version to 3.2.0 version in every package. The other way we might end up with 2 vite installations with is not ideal.

build(dev-deps): sync `vite` version to 3.2.0

---

packages/x-components/src/views/accessibility-check.vue
packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue

Ensure the component fulfil the following requirements:
**Keyboard Interaction**
- Space: When focus is on the switch, changes the state of the switch.
- Enter (Optional): When focus is on the switch, changes the state of the switch.
**WAI-ARIA Roles, States, and Properties**
- The switch has role switch.
- The switch has an accessible label provided by one of the following:
1. Visible text content contained within the element with role switch.
2. A visible label referenced by the value of aria-labelledby set on the element with role switch.
3. aria-label set on the element with role switch.
- When on, the switch element has state aria-checked set to true.
- When off, the switch element has state aria-checked set to false.
- If the presentation includes additional descriptive static text …

feat: history-queries-switch wai aria adjustments

---

packages/x-bus/package.json

Change new `x-bus` package name to `@empathyco/x-bus` so we can publish it under empathy's domain

fix: make `x-bus` package name scoped

---

packages/x-components/src/components/animations/collapse-height.vue
packages/x-components/src/components/animations/collapse-width.vue
packages/x-components/src/components/animations/cross-fade.vue
packages/x-components/src/components/animations/fade-and-slide.vue
packages/x-components/src/components/animations/fade.vue
packages/x-components/src/components/animations/staggered-fade-and-slide.vue

This change is needed to be able to change the animation of the image on hover without applying the new transition before the image is loaded.
Related to [this](https://github.com/empathyco/x/pull/863) PR.
EX-5970

fix: make appear attribute configurable on animations that have it set to true by default

---

.github/actions/release-alpha/action.yml
.github/workflows/publish-release.yml

The previous implementation of the Github Actions to release a version included creating a new .npmrc file. Now that this file already exists, there is no way to edit it without creating a change in the repo that Lerna will complain about.
The solution is to perform the same operation, which is configure the npm auth, without modifying the .npmrc file. `npm config set` changes the root .npmrc file, so it shouldn't be a problem.
https://docs.npmjs.com/cli/v8/commands/npm-config
https://stackoverflow.com/a/43012838
A different approach would be to ignore the .npmrc file on Lerna checking for pending changes, [here](https://github.com/empathyco/x/blob/main/lerna.json#L4):

fix: Avoid creating npmrc file on Github Actions

---

packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/search/store/emitters.ts
packages/x-components/src/x-modules/search/types.ts

[EX-5167](https://searchbroker.atlassian.net/browse/EX-5167)
Following a similar approach than the `SearchRequestChanged` event, a new `SearchResponseProvided` is emitted every time a search response is received.
This new event will be used [here](https://github.com/empathyco/x/pull/865).

feat: Emit SearchResponseProvided event from Search Module

---

packages/x-components/src/directives/infinite-scroll/infinite-scroll.ts

[MOTPRD-9504](https://searchbroker.atlassian.net/browse/MOTPRD-9504)
`document.getElementById(id)` doesn't enter within Shadow DOM context. To keep this way for a Shadow, we would need something like `document.querySelector('.shadow-container').shadowRoot.getElementById(id)`. As it is too coupling to the implementation, it isn't an acceptable solution.
Instead, we have changed the way how the root element is retrieved. Instead of heading toward the children (from document to root element), we head toward the document from target element (from target element to root element). It is the reason we are using ``element.closest(`#${id}`)``.

fix(infinite-scroll): retrieve root element from target element

---

packages/x-priority-queue/package.json
packages/x-priority-queue/src/__tests__/x-priority-queue.spec.ts
packages/x-priority-queue/src/index.ts
packages/x-priority-queue/src/x-priority-queue.ts
packages/x-utils/src/types/utils.types.ts

EX-7459
Creates a `XPriorityQueue` class that allows to add elements with a defined priority and to retrieve the most prioritised. It also allows to replace elements that are configured as `replaceable`.

feat(priority-queue): add `XPriorityQueue`

---

packages/x-components/src/components/suggestions/base-suggestions.vue
packages/x-components/src/x-modules/next-queries/components/next-queries.vue
packages/x-components/src/x-modules/popular-searches/components/popular-searches.vue
packages/x-components/src/x-modules/popular-searches/config.types.ts
packages/x-components/src/x-modules/popular-searches/store/module.ts
packages/x-components/src/x-modules/query-suggestions/config.types.ts
packages/x-components/src/x-modules/query-suggestions/store/module.ts
packages/x-components/src/x-modules/recommendations/components/recommendations.vue

This configurations now belong to the suggestion components. The recommendations docs where talking about suggestions  (copy & paste :troll:)

chore: Remove unused configs and docs

---

packages/x-components/src/x-modules/recommendations/store/module.ts
packages/x-components/src/x-modules/recommendations/store/types.ts

[MOTPRD-9522](https://searchbroker.atlassian.net/browse/MOTPRD-9522)
In Motive, we are modifying the prices coming from the search based on the shopper location (to apply the configured location taxes). For the search results, we will use the `updateResult` mutation already present in the project (added in https://github.com/empathyco/x/pull/706)
We need the same approach with recommendations, so in this PR we want to introduce the same update mutation for the recommendation store `updateRecommendation`.

feat(recommendations): add updateRecommendation mutation

---

packages/x-components/src/components/result/base-result-image.vue
packages/x-components/tests/unit/base-result-image.spec.ts

[MOTPRD-9540](https://searchbroker.atlassian.net/browse/MOTPRD-9540)
`BaseResultImage` didn't restore its images state when the `result` prop changed. So if the `images` array of the `result` changed, the `BaseResultImage` didn't display the current images. 
This is the case of `ResultVariantsProvider`. The selected variant is merged with the result info and if the variant contains `images`, the `result` provided to the `BaseResultImage` component contains the images of the variant, but they are not reactively referenced.
EXTRA: I would like to do a cypress component test, but I don't know how to change the prop value dynamically. Something like: 
```TS
it('resets images state when `result` prop changes', () => {
const result = createResultStub('Result', { images: …
```

fix(base-result-image): reset images state when results prop changes

---

packages/x-svg-converter/.eslintrc.js
packages/x-svg-converter/.gitignore
packages/x-svg-converter/LICENSE
packages/x-svg-converter/README.md
packages/x-svg-converter/jest.config.js
packages/x-svg-converter/package.json
packages/x-svg-converter/src/__tests__/regex-utils.spec.ts
packages/x-svg-converter/src/__tests__/svg-stub.ts
packages/x-svg-converter/src/__tests__/svg-to-vue.spec.ts
packages/x-svg-converter/src/__tests__/svgs/test_svg_0.svg
packages/x-svg-converter/src/__tests__/svgs/test_svg_1.svg
packages/x-svg-converter/src/regex-utils.ts
packages/x-svg-converter/src/svg-to-vue.ts
packages/x-svg-converter/src/types.ts
packages/x-svg-converter/tsconfig.build.json
packages/x-svg-converter/tsconfig.eslint.json
packages/x-svg-converter/tsconfig.json

[EX-7384](https://searchbroker.atlassian.net/browse/EX-7384)
We needed an easy way to import SVGs from Figma to a Vue component we could use with the XDS. This script should with that.
Create a folder and put some SVGs in it, the run the script as indicated in the README and see the Vue component it generates.

feat: script to import SVGs into Vue components for the XDS

---

packages/x-svg-converter/src/svg-to-vue.ts

We are getting a random error when running the tests for the `x-svg-converter` package. The error occurs at `removeSourceSVG` when trying to remove a file that doesn't exist anymore. This seems to happen only on the CI and not reproducible locally. Checking that the file exist before trying to unlink it should fix this random issue.
Prevent the build from failing randomly.

fix(svg-converter): check if file exist before unlink it

---

.github/workflows/combine-prs.yml

EX-7430
Adding this workflow should help us to review and merge dependabot PRs by only having to review one instead of a few. It will be possible to run this workflow on demand and it will merge all PRs that match a configurable prefix and conditions, see screenshot.
Currently I'm adding the workflow from [combine prs repo](https://github.com/hrvey/combine-prs-workflow#get-started) as it is because I think it fits our needs out of the box but we could enhance it to adapt it to our use case if needed.

ci: add `combine-prs` workflow

---

.github/workflows/build.yml
package.json

Some steps in the CI can use a cache, like install and lint steps.
This PR is done because right now our CI is really slow, with the cache enabled for the install and the eslint steps, we are able to reduce 4-5min the time of the actions. 
[Github actions cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
I read this post: [Speed your CI](https://jongleberry.medium.com/speed-up-your-ci-and-dx-with-node-modules-cache-ac8df82b7bb0). It said that maybe its better to cache `node_module/.cache`instead of the whole `node_modules` but I am not sure. 
After updating the changes, you can check the different times between the 2 actions. The first time that you upload the code, it took:
if you relaunch the same action, the time will be decreased by …

ci: add cache in github actions

---

packages/x-components/src/services/state-machine.service.ts

fix: remove warning when the event is not defined

---

packages/x-components/src/x-modules/scroll/components/main-scroll-item.vue

When a tag is defined on a `main-scroll-item`, it's events are not captured.
The only change made is just adding a `v-on="$listeners"` on `main-scroll-item` component so the events from a potential child is captured on this component and we don't miss them.
At motive, our intention is to handle hovering state via JS on our results, right now we are not able to have this events triggered.
result.vue
```vue
<template>
<ResultVariantsProvider :result="result" :autoSelectDepth="0" #default="{ result }">
<MainScrollItem
@mouseover="hovered = true"
@focusin="hovered = true"
@mouseleave="hovered = false"
@focusout="hovered = false"
tag="article"
...
```      
⚠️ This solution [is a breaking change](https://v3-migration.vuejs.org/breaking-changes/listeners-removed.html) when migrating to Vue3 
It …

feat(main-scroll-item): Capture listeners so we don't miss events

---

packages/x-components/src/components/result/base-result-image.vue
packages/x-components/tests/unit/base-result-image.spec.ts

- search for 'tshirt'
- filter by apparel.
- filter by topwear.
- remove topwear filter.
You will see how the image is not flickering, if you remove the change, the image will flicker again.
EX-7610

fix: image flickering on re-rendering

---

packages/x-components/src/components/modals/base-events-modal-close.vue
packages/x-components/src/components/modals/base-events-modal-open.vue
packages/x-components/src/views/accessibility/wai-base-event-button.vue

`base-events-modal-close` and `base-events-modal-open` are using `base-event-button` component but yet they were no identified for WCAG compliance when modifying all components using `base-event-button`. This PR tries to solve that and make them accessible.
Screen Reader (Chrome extension)

feat: modify base-events-modal-close and base-events-modal-open for WCAG compliance

---

packages/x-adapter-platform/src/schemas/models/banner.schema.ts
packages/x-adapter-platform/src/schemas/models/facet.schema.ts
packages/x-adapter-platform/src/schemas/models/filters/hierarchical-filter.schema.ts
packages/x-adapter-platform/src/schemas/models/filters/number-filter.schema.ts
packages/x-adapter-platform/src/schemas/models/filters/simple-filter.schema.ts
packages/x-adapter-platform/src/schemas/models/next-query.schema.ts
packages/x-adapter-platform/src/schemas/models/partial-results.schema.ts
packages/x-adapter-platform/src/schemas/models/promoted.schema.ts
packages/x-adapter-platform/src/schemas/models/redirection.schema.ts
packages/x-adapter-platform/src/schemas/models/related-tag.schema.ts
packages/x-adapter-platform/src/schemas/models/result.schema.ts
packages/x-adapter-platform/src/schemas/models/suggestion.schema.ts
packages/x-adapter-platform/src/schemas/requests/identifier-results-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/next-queries-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/popular-searches-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/query-suggestions-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/recommendations-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/related-tags-request.schema.ts
packages/x-adapter-platform/src/schemas/requests/search-request.schema.ts
packages/x-adapter-platform/src/schemas/responses/identifier-results-response.schema.ts
packages/x-adapter-platform/src/schemas/responses/next-queries-response.schema.ts
packages/x-adapter-platform/src/schemas/responses/popular-searches-response.schema.ts
packages/x-adapter-platform/src/schemas/responses/query-suggestions-response.schema.ts
packages/x-adapter-platform/src/schemas/responses/recommendations-response.schema.ts
packages/x-adapter-platform/src/schemas/responses/search-response.schema.ts
packages/x-adapter/src/mappers/schema-mapper.factory.ts
packages/x-adapter/src/schemas/__tests__/utils.spec.ts
packages/x-adapter/src/schemas/types.ts
packages/x-adapter/src/schemas/utils.ts

BREAKING CHANGE: `MutableSchema` now receives a `Source` and a `Target` object instead of a `Schema`
BREAKING CHANGE: `$replace`, `$extends` and `$override` function types now reflect the allowed operations more correctly.
EX-7702
Modifies `MutableSchema` types so overriding, extending, and replacing function types reflect correctly the operations made.
- `$replace` should replace **completely** the old schema. That's why in the implementation there are some casts, as this operation is not modelable with TypeScript.
- `$override` should **mutate** the current schema, allowing to add new properties or modifying mappings. Therefore  you are allowed to pass a new `Source` and `Target` generic types that will be combined with the old ones.
- `$extends` works pretty much the same than …

fix: mutable schema types

---

packages/x-components/src/router.ts
packages/x-components/src/views/accessibility/accessibility-check.vue
packages/x-components/src/views/accessibility/wai-base-result-link.vue

WCAG compliance 
**Keyboard Interaction**
- Enter: Executes the link and moves focus to the link target.
- Shift + F10 (Optional): Opens a context menu for the link. → N/A
**WAI-ARIA Roles, States, and Properties**
- The element containing the link text or graphic has role of [link](https://w3c.github.io/aria/#link).
**The link pattern is used when it is necessary for elements other than the HTML `a` element to have link behaviours.**
No changes are needed. Adding `role="link"` to `base-result-link.vue` triggers `vuejs-accessibility` plugin error: 
**The element a has an implicit role of link. Defining this explicitly is redundant and should be avoided  vuejs-accessibility/no-redundant-roles**
Test view was created (accessibility-check/wai-base-result-link)
Tests performed according to …

feat: base-result-link wcag compliance

---

packages/x-archetype-utils/src/home/home-template.html

EX-7806
Links to the docs should have an underline hover effect. Also, to tests this implementation on the `x-archetype`, I've added a `data-test` to the search bar that substitutes the start button we previously had.
Load the HTML in a browser and check the hover effect.

feat: add data-test to searchbar and hover underline to docs links

---

packages/x-components/src/x-modules/history-queries/components/__tests__/history-query.spec.ts
packages/x-components/src/x-modules/history-queries/components/history-query.vue

TO test it, change the history queries component in the predictive layer with this one:
```
<HistoryQueries class="x-list">
<template #suggestion="{ suggestion }">
<HistoryQuery :removeHistoryQueryClass="'x-custom-class'" :suggestion="suggestion">
<template #default="{ query }">
<HistoryIcon  />
<Highlight :text="suggestion.query" :highlight="query" />
</template>
</HistoryQuery>
</template>
</HistoryQueries>
```
EX-7833

feat(history-queries): add dynamic classes to the remove history query button

---

packages/x-components/src/components/suggestions/__tests__/base-suggestions.spec.ts
packages/x-components/src/components/suggestions/base-suggestions.vue

To test it, add the prop `suggestionItemClass` to a base-suggestions component, for example:
`<HistoryQueries :suggestionItemClass="'x-custom'" />`
EX-7834

feat: add dynamic classes to the suggestion item inside the `base-suggestions`

---

packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion-group/default.ts

This will allow the last element of a suggestion group to go to the end of the container.
EX-7845

feat(design-system): modify default styles in the `suggestion-group`

---

packages/x-adapter-platform/src/__tests__/platform.adapter.spec.ts
packages/x-adapter-platform/src/endpoint-adapters/identifier-results.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/next-queries.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/popular-searches.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/query-suggestions.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/recommendations.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/related-tags.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/search.endpoint-adapter.ts
packages/x-adapter-platform/src/endpoint-adapters/tagging.endpoint-adapter.ts

Keep in mind that the tagging endpoint doesn't need the `internal` field.
EX-7780

feat(endpoint-adapters): send internal field in the requests

---

packages/x-tailwindcss/demo/src/components/xds-sliding-panel.vue
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/buttons/default.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/buttons/hover.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/buttons/index.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/buttons/positions.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/default.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/fade/index.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/fade/sizes.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/index.ts

EX-7687
After #1006 and trying to use the new XDS sliding panel in x we saw some potential issues and the need to duplicate css and classes in the sliding panel component from x. In order to avoid those issues, this PR reduces the scope for the XDS sliding panel and makes the design system only care about buttons position and fade. The scroll behaviour for the list will be a responsibility for the consumer of the design system. You can see how this will be used in x in this [branch](https://github.com/empathyco/x/tree/refactor/sliding-panel-xds)

refactor: make sliding panel take care buttons position and fade

---

packages/eslint-plugin-x/lib/configs/jsdoc.js

See https://github.com/gajus/eslint-plugin-jsdoc/pull/828
I'm enabling this option for the jsdoc plugin for eslint in order to avoid issues like we currently have with the [Related tags](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/related-tags/components/related-tags.vue#L54) where the eslint pre commit hook will remove automatically the * for [friends](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/related-tags/components/related-tags.vue#L54)

feat: enable `allowWhitespace` in `jsdoc/no-multi-asterisks`

---

packages/x-components/src/components/result/base-result-fallback-image.vue
packages/x-components/src/components/result/base-result-image.vue
packages/x-components/src/components/result/base-result-placeholder-image.vue

[EX-7836](https://searchbroker.atlassian.net/browse/EX-7836)
While I was implementing the component in the archetype I realized we had duplicated classes:
This PR removes duplicated classes and also updates fallback/placeholder documentation classes to set the project currently used.
[EX-7836]: https://searchbroker.atlassian.net/browse/EX-7836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(feat) Remove duplicates from image placeholder/fallback classes

---

packages/x-tailwindcss/demo/src/components/xds-picture.vue
packages/x-tailwindcss/src/x-tailwind-plugin/components/picture/default.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/picture/overlay.ts
packages/x-tailwindcss/src/x-tailwind-plugin/components/picture/zoom.ts

[EX-7836](https://searchbroker.atlassian.net/browse/EX-7836)
Update XDS picture component to avoid using an `img` tag in XDS, use a `class` instead.
[EX-7836]: https://searchbroker.atlassian.net/browse/EX-7836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(design-system): Use class instead of img tag

---

nx.json

EX-7907
Configure `nx` task runner to have `local caching` and specify the dependants of each task.

chore: configure nx task runner and local caching

---

packages/x-components/src/x-modules/history-queries/components/__tests__/my-history.spec.ts
packages/x-components/src/x-modules/history-queries/components/my-history.vue

Needed to be able to format the timestamp when using the `suggestion` slot instead of the `suggestion-content` one.
EX-7879

feat(history-queries): bind formatTime callback to MyHistory suggestion slot

---

package-lock.json

npm audit was complaining about a high vulnerability in [JSON5](https://github.com/json5/json5/issues/295) which was fixed in version [1.0.2](https://github.com/json5/json5/commit/e0c23fe458a77c0b2cdb271376be5d8d0908133c). This PR comes from running `npm audit fix`

build(deps): update `JSON5` version

---

packages/x-bus/package.json
packages/x-bus/src/x-bus.ts
packages/x-bus/src/x-bus.types.ts

EX-7928
add missing dependency `rxjs`.
`typescript` is messing with the `setTimeout` type, as it has a different definition in `nodejs` than in the `window` object, so we have to narrow it to the `window` one. My only concern is that this code is not `ssr` friendly, as we are using the `window.setTimeout` directly. In case we need to support `ssr`, we might have to wrap the setTimeout function to distinguish the platform we are running the code on.

fix: add missing `rxjs` dependency and narrow `setTimeout` type

---

packages/x-components/src/components/modals/main-modal.vue

EX-7710
The `focusOnOpen` prop is set to true by default in the `BaseModal` component.
In the case of the `MainModal`, it does not make sense, because if there is a focusable element before the `SearchInput`, the user will have to click the input manually to be able to write.
This change is to avoid modifying the prop in all the setups.
Check that the `BaseModal` inside the `MainModal` opens with `focusToOpen` as false. Try changing the prop in `MainModal` to check that the prop is working correctly.

fix(modal): set focusOnOpen for the main-modal to false

---

packages/x-components/src/__stubs__/banners-stubs.factory.ts
packages/x-components/src/components/__tests__/items-list.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/banner.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/banners-list.spec.ts
packages/x-components/src/x-modules/search/components/banner.vue
packages/x-components/tests/e2e/common/mocked-responses.spec.ts
packages/x-components/tests/unit/banner.spec.ts
packages/x-types/src/banner.model.ts

From motive, our intention is to have banners that are not clickable and do not have a title. Right now, the X banner forces any banner to have a URL to redirect to and a title. In this PR we propose a solution to support X banners and the banners Motive needs.
- `url` and `title` are optional.
- If the banner has a URL it will be clickable, triggering the appropriate events, otherwise it will just be an image(with or without title). 
- If there is an error loading the banner image, the banner will be removed from the DOM.
- If the banner does not have a title, the alternative text of the image will be "Banner" and the heading(`h2`) will not be rendered.
We have defined some unit tests at component level using Jest(`x-components/src/x-modules/search/components/__tests__/banner.spec.ts`) …

feat(banner): banner without title and no clickable

---

packages/x-components/src/components/modals/__tests__/base-events-modal.spec.ts
packages/x-components/src/components/modals/__tests__/base-id-modal.spec.ts
packages/x-components/src/components/modals/__tests__/base-modal.spec.ts
packages/x-components/src/components/modals/__tests__/main-modal.spec.ts
packages/x-components/src/components/modals/base-modal.vue
packages/x-components/src/x-modules/search-box/components/search-input-placeholder.vue

EX-8011
Workaround to fix the issue when opening the XArchetype.
To reproduce the issue, go to XArchetype and change the dynamic import of the MainModal to a normal import. Then run the proyect and you won't be able to open X. It is open and immediately closed.
Sometimes the issue is not reproducible due to the code order 🤷🏻

fix(components): Fix open issue when focused on body. Fix `SearchInputPlaceholder` styles.

---

packages/deep-merge/package.json
packages/eslint-plugin-x/package.json
packages/jest-utils/package.json
packages/logger/package.json
packages/react-wrapper/package.json
packages/storage-service/package.json
packages/x-adapter-platform/package.json
packages/x-adapter/package.json
packages/x-archetype-utils/package.json
packages/x-bus/package.json
packages/x-components/package.json
packages/x-priority-queue/package.json
packages/x-svg-converter/package.json
packages/x-tailwindcss/package.json
packages/x-translations/package.json
packages/x-types/package.json
packages/x-utils/package.json
pnpm-lock.yaml

Remove it in each package because it is causing errors when you try to install an individual package.
Leave it in the root package to not allow running the mono repo with npm.
EX-8082

fix(deps): remove `only-allow` pnpm

---

packages/x-adapter-platform/package.json

EX-8105
We are not including the `api-extractor` generated `report` folder to the packed `tarball`, which is what we end up publishing to `npm` as a package. It should be included, as it is later on consumed by other packages when referencing its documentation using the `{@link ...}` annotation.

build: add report folder to packed tarball

---

packages/x-components/src/components/column-picker/__tests__/base-column-picker-list.spec.ts
packages/x-components/src/components/column-picker/base-column-picker-list.vue
packages/x-components/src/views/home/Home.vue
packages/x-components/tests/unit/base-column-pickers.spec.ts
packages/x-tailwindcss/src/x-tailwind-plugin/plugin.ts

BREAKING CHANGE: `base-column-picker-list` structure changes. It now wraps the buttons in a div instead of using `ul` and `li`. Additionally, the class for the selected option has been changed to `x-selected`.
[EX-8144](https://searchbroker.atlassian.net/browse/EX-8144)
After adding the button group to the XDS adapting the column picker list component was a necessary step given that it's the X-Component that uses it.
New test done for the new component slot and structure
[EX-8144]: https://searchbroker.atlassian.net/browse/EX-8144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adapt base-column-picker-list to use the XDS component of button group

---

.github/workflows/build.yml

EX-8149
This change solves one of the issues related to Cypress in the pipeline:
In this case, the problem was caused by a wrong Cypress cache path passed to the `setup pnpm cache` step. 
- We were using the default Cypress cache path (`~/.cache/Cypress`) but it is being overridden by the environment variable `CYPRESS_CACHE_FOLDER` with value `/root/.cache/Cypress` in the docker image. 
> Check [https://github.com/search?q=repo:cypress-io/cypress-docker-images CYPRESS_CACHE_FOLDER&type=code](https://github.com/search?q=repo:cypress-io/cypress-docker-images%20CYPRESS_CACHE_FOLDER&type=code)
- When `pnpm` cache is restored, the `postinstall` of Cypress, which downloads the binary, is not executed and this causes the tests to fail if the binary is not either restored from the cache or …

ci: fix cypress cache path

---

packages/x-components/src/components/scroll/scroll.mixin.ts
packages/x-components/src/views/base-config.ts
packages/x-components/src/x-modules/facets/events.types.ts
packages/x-components/src/x-modules/facets/store/__tests__/getters.spec.ts
packages/x-components/src/x-modules/facets/store/emitters.ts
packages/x-components/src/x-modules/facets/store/getters/facets.getter.ts
packages/x-components/src/x-modules/facets/store/getters/selected-filters-by-facet.getter.ts
packages/x-components/src/x-modules/facets/store/getters/selected-filters-for-request.getter.ts
packages/x-components/src/x-modules/facets/store/getters/selected-filters.getter.ts
packages/x-components/src/x-modules/facets/store/module.ts
packages/x-components/src/x-modules/facets/store/types.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-components/src/x-modules/search/wiring.ts
packages/x-components/src/x-modules/url/wiring.ts

EX-7550
Sometimes the backend doesn't handle the hierarchical filters sent as expected and only filters by the parent. This PR implements the posibility of applying a strategy to filter the filters that are sent to the requests or that are stored in the URL 
The strategy is set to `leaves-only`, which means that only filters without selected children are sent to the request or stored in the URL. Check the request or the url while selecting filters and change the strategy to `all` in the `base-config.ts`.

fix(facets): implement the possibility to set a strategy for what filters are sent to the request. leaves-only strategy also implemented

---

packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md

SessionId duration information
Inform the integration developers and customers about sessionId duration and way of working.
Questions from Customer Success department

docs(integration): add information about sessionId duration

---

.prettierignore

Update prettierignore
Change the prettierignore to ignore CHANGELOG files which is causing some undesired formatting on CHANGELOG, and also possibly the inclusion of many changelog headers
Avoid prettier to modify CHANGELOG files
Manually changing the `x-bus` `CHANGELOG` file in the project with a long line and launching this command `prettier -c packages/x-bus` it shows the file in the list.
After the change, the file is not shown.

fix: fix prettierignore to ignore CHANGELOG files

---

packages/x-components/src/components/animations/cross-fade.vue
packages/x-components/src/components/result/base-result-image.vue

EMP-684
When the functionality to swap between result images on hover was active and the `CrossFade` animation was used, there was an issue with the hovered NQ shrinking and then expanding. The issue was caused by the `CrossFade` animation making the leaving image `absolute` so the element lost the width until the new image loaded. Also added a fix for the hovering functionality after migrating the `BaseResultImage` to vue 3 OptionsAPI.
Make sure you have cache disabled. Set the `BaseResultImage` prop `showNextImageOnHover` to `true`, remove the `x-picture-zoom` class and then navigate to a NQ and hover it. The animation should shrink the image.

fix: cross-fade animation doesn't need min width to work properly

---

packages/x-tailwindcss/demo/src/components/xds-layout.vue
packages/x-tailwindcss/src/x-tailwind-plugin/dynamic-components.ts
packages/x-tailwindcss/src/x-tailwind-plugin/dynamic-components/layout/index.ts
packages/x-tailwindcss/src/x-tailwind-plugin/dynamic-components/layout/layout-container.ts

[EMP-564](https://searchbroker.atlassian.net/browse/EMP-563)
We needed a way to place the empathize aligned to the search box even if they were in different contexts. This new layout allows custom alignment of any element.
New showcase of the layout created
[EMP-564]: https://searchbroker.atlassian.net/browse/EMP-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: layout for custom alignment

---

packages/x-components/src/x-modules/related-tags/components/related-tag.vue

Active element wasn't being removed after deselecting a related tag, causing it to seem hovered.
This bug came out during Conforama setup thanks to the high contrast between colours used.

fix: blur related tag when deselected

---

packages/x-components/build/rollup.config.ts

The `deprecated-full-theme.css` file we are currently exporting doesn't include the old design system tokens so it will not work out of the box. This PR makes the rollup build to include the tokens into the file.

fix: include tokens in deprecated theme css file

---

packages/x-components/src/x-modules/queries-preview/components/query-preview.vue

EMP-717
There was a bug in the `QueryPreview` component where, if used multiple times, only the last query would load.
This doesn't happen if the `QueryPreviewList` component is used.
The bug was caused by the bus canceling the consecutive events and only accepting the last one.
To fix it, I have made the event `QueryPreviewRequestUpdated` emitted by the component not replaceable.

fix(queries-preview): make the QueryPreviewRequestUpdated not replaceable

---

packages/x-components/src/components/result/__tests__/base-result-link.spec.ts
packages/x-components/src/components/result/base-result-link.vue
packages/x-components/src/wiring/wiring.types.ts
packages/x-components/src/x-modules/tagging/wiring.ts

[EMP-864](https://searchbroker.atlassian.net/browse/EMP-864)
With the future inclusion of the `displayClick` event we needed a way of ignoring the click event of the base-result-link in the tagging if we decided so. This PR adds a property to the wiring metadata to do that and check it in the module's wiring.
New tests have been done for the new features of `BaseResultLink`.
[EMP-864]: https://searchbroker.atlassian.net/browse/EMP-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: set configuration for base-result-link to ignore tagging of click

---

packages/x-components/src/x-modules/tagging/wiring.ts

[EMP-929](https://searchbroker.atlassian.net/browse/EMP-929)
We need to track the new type of click in the tagging.
Inject a new event to trigger when the `base-result-link` is clicked that emits a `UserClickedADisplayResult` and see that the tagging tracks it.
[EMP-929]: https://searchbroker.atlassian.net/browse/EMP-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tagging): track displayClick

---

packages/x-components/src/x-installer/api/__tests__/default-api.spec.ts
packages/x-components/src/x-installer/api/api.types.ts
packages/x-components/src/x-installer/api/base-api.ts

EMP-273
You can take a look at how it works on this [archetype branch](https://github.com/empathyco/x-archetype/tree/test/open-search-on-init) (just for testing purposes)

feat: make `XAPI` init method async

---

packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/search/store/actions/set-url-params.action.ts

[EMP-1194](https://searchbroker.atlassian.net/browse/EMP-1195)
There was a bug where the `rows` for a search query was being calculated with the `results.length` of a previous search when loading from URL, sometimes causing errors
Search `beanie hat` -> Scroll to page 2 -> Search `skirt` -> scroll to page 3 at least -> Click the browser "back" button -> It should search for the first page of beanie hats, previously it requested a negative row.
[EMP-1194]: https://searchbroker.atlassian.net/browse/EMP-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(search): ignore page from url when going to a different query

---

packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

[EMP-1500](https://searchbroker.atlassian.net/browse/EMP-1500)
`SnippetConfigExtraParams` wasn't reacting to changes on the `values` prop like it did with the snippet config changes.
Manually change the prop with the vue dev tools.
[EMP-1500]: https://searchbroker.atlassian.net/browse/EMP-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make the snippet-config-extra-params component react to prop changes

---

packages/x-components/src/x-modules/search/store/actions/set-url-params.action.ts

The scroll was not kept when you loaded a page greater than 1. It happens when you don't have a filter and also when you select any. We have solved the problem setting a configuration on the `set-url-params.actions.ts` in the `search` module.
Add this code to the `adapter.ts` file in the `views` folder:
> resultSchema.$override<any, Partial<Result>>({
>   // eslint-disable-next-line @typescript-eslint/no-unsafe-call
>   id: ({ id }) => id.toString()
> });
Then scroll to different pages and reload the page. The scroll should be kept.
[EMP-1017]: https://searchbroker.atlassian.net/browse/EMP-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix: save the number of pages loaded

---

packages/x-components/src/components/base-rating.vue

Add a `max-widht` to `BaseRating` component because if a `x-flex` class is applied the rating will not be filled correctly.
Add `<BaseRating :value="3" />` in the result.vue file.
[EMP-1374]: https://searchbroker.atlassian.net/browse/EMP-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix: fix base rating component

---

packages/x-adapter/src/utils/__tests__/interpolate.spec.ts
packages/x-adapter/src/utils/interpolate.ts

Currently, when we use the `live` env, we can't define it as an empty string (`''`) because the request will fail, it will put two `.` one after the other. This doesn't make much sense. 
We fixed it by modifying the behavior of the `interpolate` function. Now if the value of the `env` is `null`, `undefined` or an empty string (`''`), the request of the live env will work correctly.
Change in the `base-config.ts` file the value of the `env` to an empty string.
For example:
```
// @ts-ignore
env: '' 
```
[EMP-1397]: https://searchbroker.atlassian.net/browse/EMP-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make empty string point to live env

---

packages/x-components/src/components/sliding-panel.vue

After making a search and deleting a query, top clicked sliding panel arrows don’t show up. This is because the variables `isScrollAtStart` and `isScrollAtEnd` were restored both at `true`.
If you want to test it in the **x-archetype** project, you have to remove from the `BaseResultImage` component (in the `result.vue` file) the `showNextImageOnHover` parameter. If not, you can test it for example in **x-conforama-next** project.
Steps to follow:
- Run the **build** in X project. This is going to generate a local file in `src` folder. Example: _empathyco-x-components-3.0.0-alpha.400.tgz_
- In the project that you want to test, go to the `package.json` and in the `"install:local"` script paste the local build file and run it. 
- Finally follow the task steps:
[EMP-750]: …

fix: restore sliding panel state after a search

---

packages/x-components/src/x-modules/device/components/device-detector.vue

Change Vue live examples
The current example is not working: https://docs.empathy.co/develop-empathy-platform/ui-reference/components/device/x-components.device-detector.html#see-it-in-action
Check it in the PR preview that I created by syncing Dynamic Dcos:
https://docs-dev.empathy.co/preview/1378/develop-empathy-platform/ui-reference/components/device/x-components.device-detector.html
Get all vue live examples to work in eDocs

doc(device-detector): fix vue live examples for doc portal

---

packages/x-components/src/views/home/result.vue
packages/x-components/src/x-modules/scroll/components/main-scroll-item.vue
packages/x-components/tests/e2e/scroll.feature
packages/x-components/tests/e2e/scroll/scroll.spec.ts
packages/x-components/tests/unit/main-scroll.spec.ts

[EMP-2021](https://searchbroker.atlassian.net/browse/EMP-2021)
Depending on the setup's header it was possible that, when automatically scrolling to an element in the main scroll, the element was cut by the header. This feature adds a prop to the main-scroll-item to add an offset to the scrolling.
Set the prop and reload a url that has `scroll` attribute.
[EMP-2021]: https://searchbroker.atlassian.net/browse/EMP-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(scroll): add top offset when automatically scrolling to main-scroll-item

---

packages/x-utils/src/__tests__/object.spec.ts
packages/x-utils/src/object.ts

[EMP-2123](https://searchbroker.atlassian.net/browse/EMP-2123)
We needed a way of deeply comparing two objects for certain cases where the Vue watcher wasn't working as expected.
New tests have been created for this feature.
[EMP-2123]: https://searchbroker.atlassian.net/browse/EMP-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: deep comparator for objects

---

packages/x-components/src/x-modules/queries-preview/components/query-preview.vue

EMP-2124
With the new deepEqual we can compare the requests from the query preview component more accurately.
Try a query with semantic queries + query preview and test everything still works the same (the "cortina" query preview works)

feat(query-preview): use deep equal to compare request

---

packages/x-components/src/views/home/Home.vue

EMP-2402
The `DisplayResultsProvider` was messing up with the sliding panel of the semantic queries and making it so it only displayed one result.
Search for a query that returns semantics (`battery` for example) and see that the carrousels have more than one item.

fix: move the display-results-provider to fix semantics sliding panel

---

packages/x-components/src/x-modules/facets/wiring.ts

EMP-2407
The query of the facets module wasn't being updated when a query preview was selected and that caused probles with the events from the emitters not having the correct `oldValue`.
Click a query preview with filters (`cortina` for example) and search for something that doesn't have results (a spellchecked query, `pantlon` for example). Only the spellcheck message should appear. Check removing the new wire and two messages appear doing the same.

fix: set query in facets module from selecting a query preview

---

packages/x-components/src/plugins/__tests__/x-plugin-emitters.spec.ts
packages/x-components/src/plugins/__tests__/x-plugin.spec.ts
packages/x-components/src/x-modules/facets/store/types.ts
packages/x-components/src/x-modules/history-queries/store/types.ts
packages/x-components/src/x-modules/identifier-results/store/types.ts
packages/x-components/src/x-modules/identifier-results/wiring.ts
packages/x-components/src/x-modules/next-queries/store/types.ts
packages/x-components/src/x-modules/query-suggestions/store/types.ts
packages/x-components/src/x-modules/query-suggestions/wiring.ts
packages/x-components/src/x-modules/search-box/store/types.ts
packages/x-components/src/x-modules/search/store/getters/query.getter.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-components/src/x-modules/semantic-queries/store/module.ts
packages/x-components/src/x-modules/semantic-queries/store/types.ts
packages/x-components/src/x-modules/url/store/types.ts

This task is to check in the different modules that all mutations of a query are taking advantage of the setQuery util functionality and import the setQuery & use it if necessary. I noticed that in some tests we weren't using the setQuery function
[EMP-2424]: https://searchbroker.atlassian.net/browse/EMP-2424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: using setQuery util in tests that need it

---

packages/x-components/src/x-modules/facets/wiring.ts
packages/x-components/src/x-modules/history-queries/store/actions/load-history-queries-from-browser-storage.action.ts
packages/x-components/src/x-modules/search/wiring.ts

Legacy HQ (history queries stored in the local storage before the new `selectedFilters` feature was created) caused an error because clicking on them resulted in the utility `groupBy` being called with `undefined`.
Check if you have any legacy HQ in the local storage or create one by removing the `selectedFilters` field from an existing one and the select it.

fix(history-queries): selected filters now working for legacy history queries saved in storage without them

---

packages/eslint-plugin-x/package.json
pnpm-lock.yaml
renovate.json

The package `prettier-plugin-tailwindcss` introduced a breaking change in [0.4.0](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/CHANGELOG.md#added-1) version where it only support prettier 3. 
We can't update to prettier 3 yet because it will break the docs generation, so I'm pinning down the version to 0.3.0.

chore(deps): pin `prettier-plugin-tailwindcss` to 0.3.0 version

---

packages/x-components/src/types/origin.ts

Add better name for ResultFeature values related to recommendations
HAve a clear mapping of the features in the tagging

fix(x-plugin): improve ResultFeature type values

---

packages/x-components/src/components/decorators/injection.consts.ts
packages/x-components/src/x-modules/facets/entities/filter-entity.factory.ts
packages/x-components/src/x-modules/facets/store/__tests__/getters.spec.ts
packages/x-components/src/x-modules/facets/store/constants.ts
packages/x-components/src/x-modules/facets/store/getters/facets.getter.ts
packages/x-components/src/x-modules/facets/store/getters/selected-filters-by-facet.getter.ts
packages/x-components/src/x-modules/history-queries/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/history-queries/store/actions/update-history-queries-with-search-response.action.ts
packages/x-components/src/x-modules/search/store/module.ts

Create `UNKNOWN_FACET_KEY` constant to identify filters without `facetId` (`RawFilter`).
BREAKING CHANGES:
- The `'__unknown-facet__'`  value for a `facetId` is deprecated: it has been replaced by the `UNKNOWN_FACET_KEY` constant, whose value is `'__unknown__'`.
Right now we’re identifying unknown facets giving them either` __unknown__` or` __unknown-facet__` as id.
We should unify this and use a constant instead of a plain string.
[EMP-2674]: https://searchbroker.atlassian.net/browse/EMP-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(facets): Unify __unknown__ and __unknown-facet__ in a constant

---

.github/workflows/prepare-release.yml

This PR removes the test and lint steps from the workflow for creating a new stable release. Currently, these steps run on every push and PR. Since the prepare release workflow is launched against the main branch, where these steps have already been executed, there's no need to run them again, especially considering this workflow will only create a PR and this new PR will execute them.

ci: remove lint and test steps

---

.github/workflows/publish-release.yml

This PR makes the publish-release workflow to follow the same approach for running tests as the build workflow.

ci: use cypress action to run e2e

---

packages/x-components/src/x-installer/api/__tests__/default-api.spec.ts
packages/x-components/src/x-installer/api/api.types.ts
packages/x-components/src/x-installer/api/base-api.ts
packages/x-components/src/x-installer/x-installer/__tests__/x-installer.spec.ts
packages/x-components/src/x-installer/x-installer/x-installer.ts

Provide a method `InterfaceX.getSnippetConfig()` that returns the init params of the snippet for both cases of initialization:
* window.initX
* InterfaceX.init()
Customers, kams, devs, etc... are always asking us how to get the snippetConfig configuration of any setup. With this new method they can obtain the configuration quickly and easily, regardless of the way they initialized the project.
If you run the `serve` script in your local and run `InterfaceX.getSnippetConfig()` in the console of the devtools, you should obtain an object with the snippetConfig configuration.
[EMP-3012]: https://searchbroker.atlassian.net/browse/EMP-3012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(installer): implementation of snippet config getter

---

packages/x-adapter-platform/src/__tests__/__fixtures__/search.response.ts
packages/x-adapter-platform/src/mappers/__tests__/url.spec.ts
packages/x-adapter-platform/src/mappers/responses/__tests__/__snapshots__/search-response.mapper.spec.ts.snap
packages/x-adapter-platform/src/mappers/url.utils.ts
packages/x-adapter-platform/src/schemas/models/result.schema.ts
packages/x-adapter-platform/src/schemas/responses/search-response.schema.ts
packages/x-adapter-platform/src/types/responses/search-response.model.ts
packages/x-components/src/__stubs__/empty-search-response-stubs.factory.ts
packages/x-components/src/__stubs__/search-response-stubs.factory.ts
packages/x-components/src/adapter/mocked-responses.ts
packages/x-components/src/x-modules/search/store/actions/save-search-response.action.ts
packages/x-components/src/x-modules/search/store/emitters.ts
packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-types/src/response/search-response.model.ts

[EMP-3239](https://searchbroker.atlassian.net/browse/EMP-3239)
A new field for the display tagging will be added to the search response to be used on the recommendations. This PR handles that new field for the search response types and the search module.
[EMP-3239]: https://searchbroker.atlassian.net/browse/EMP-3239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(search): handle display tagging from search response

---

packages/x-components/src/composables/index.ts
packages/x-components/src/composables/use-register-x-module.ts

Every x component uses the [x-component.mixin.ts](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/x-component.mixin.ts) to register the related x module. Currently when a component is imported the x module is registerd. We need to check if this is needed or is it okay to register the module when the component is instantiated. Within this task we should create a new composable that is able to receive a `AnyXModule` and register it in the XPlugin via. I have created the composable and tried it out in different cases, if you register the module in the setup() it can be accessed from the template, created() and mounted(). 
[EMP-3104]: …

feat: creating useRegisterXModule composable

---

packages/x-components/src/composables/index.ts
packages/x-components/src/composables/use-store.ts

[EMP-3452](https://searchbroker.atlassian.net/browse/EMP-3452)
Vuex 3 does not have a store composable and we need a way to get access to the store in the components using the composition API. We have created a `useStore` composable.
You can use the `useStore` composable in an existing component with the `defineComponent` syntax OR you can create a test component and access there to the `useStore` composable.
Example of test component:
```
<template>
<div>
<span>{{ test }}</span>
</div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import { useStore } from '../composables';
export default defineComponent({
setup() {
const $store = useStore();
const test = $store.state.x.historyQueries.historyQueries;
return {
test
};
}
});
</script>
```
[EMP-3452]: …

feat: create useStore composable

---

packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview-list.spec.ts

[EMP-3403](https://searchbroker.atlassian.net/browse/EMP-3402)
Just uncommented the tests that should fail and now they are passing, also tested with another query with no results, `fbguadjrhvgw`.
I have compared my local branch (`feature/EMP-3079-allow-queries-preview-with-same-query-but-different-filters-or-params`) which was not updated with the [last changes that were merged](https://github.com/empathyco/x/pull/1392):
Here is a screenshot: On the left side the code in the updated branch, on the right side my local & not updated branch (where tests failed):
It seems that the reactivity was broken as the query preview key variable was not reassigned, so there weren't new queries to make more requests. Setting the key as a computed property was the solution.
@diegopf or @CachedaCodes …

Query Previews stop requesting when one fails

---

packages/x-components/src/views/home/Home.vue
packages/x-components/src/views/home/display-result-provider.vue
packages/x-components/src/wiring/events.types.ts
packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
packages/x-components/src/x-modules/queries-preview/store/__tests__/actions.spec.ts
packages/x-components/src/x-modules/queries-preview/store/actions/fetch-and-save-query-preview.action.ts
packages/x-components/src/x-modules/queries-preview/store/types.ts
packages/x-components/src/x-modules/tagging/wiring.ts

Carrousel previews are tagged with a new event “displayclicked” but this info doesn’t impact the CTR or Findability metric therefore queries are growing but CTR and Findability are suffering.
When a user clicks on a product in the carousel the query event with the origin has to be sent and the click and displayClick events.
Click on a result of a query preview. The first time you click on a result in one carousel 3 events should be sent (click, displayClick and query). Suppose you click on another result of the same carousel, only 2 events will be sent (click and displayClick). In that case, the tagging module has stored the queryTaggingInfo of the carousel. If you try to click in another carousel, the 3 events will be sent again.
[EMP-3521]: …

feat(tagging): send query event when a result from a QP is clicked

---

packages/x-components/src/composables/__tests__/use-no-element-render.spec.ts
packages/x-components/src/composables/index.ts
packages/x-components/src/composables/use-no-element-render.ts

[EMP-3540](https://searchbroker.atlassian.net/browse/EMP-3540)
Vue 3 is removing the ability to extend Vue components and replacing it with composables. Due to this, components like `LocationProvider` need a way to use the NoElement rendering. We have to create a composable for that.
Create a clone component of `NoElement` and implement the composable instead. Test that the component behaves the same as the other one.
[EMP-3540]: https://searchbroker.atlassian.net/browse/EMP-3540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(composables): create useNoElementRender composable

---

packages/x-components/src/components/base-switch.vue

In order to migrate X components to vue3, we need to use the 2.7 sintax.
You can use this test component to see if the switch still works correctly (review the import of the component according to your context)
```
<template>
<div>
<BaseSwitch @change="value = !value" :value="value" />
</div>
</template>
<script>
import { BaseSwitch } from '../../components';
export default {
name: 'BaseSwitchDemo',
components: {
BaseSwitch
},
data() {
return {
value: false
};
}
};
</script>
```
Also test the v-model sintax:   `<BaseSwitch v-model="value" />`
[EMP-3376]: https://searchbroker.atlassian.net/browse/EMP-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: migrate base-switch to use defineComponent sintax

---

packages/x-components/src/components/animations/cross-fade.vue
packages/x-components/src/composables/index.ts
packages/x-components/src/composables/use-hybrid-inject.ts

[EMP-3558](https://searchbroker.atlassian.net/browse/EMP-3558)
The regular vue 3 `inject` doesn't work with the `XProvide`, so this utility composable functions as a stepping stone for the migration between the two. It works with any of them and it should be removed when the migration to vue 3 is completed.
Create a injected test vue component and a provider test vue component. Wrap the injected test component in the provider. Now, the injected test component should use the composable and the provider component should do the providing.
Create the provider component so it uses the `@XProvider` decorator and has a dynamic property that provides to its children (for example, a property that changes with a button). The injected test component should pick it up correctly and change …

feature(composable): create utility composable useHybridInject

---

packages/x-components/src/components/base-rating.vue

In order to migrate X components to vue3, we need to use the 2.7 sintax.
Tested using this component in a test view: https://docs.empathy.co/develop-empathy-platform/ui-reference/components/base-components/x-components.base-rating.html
[EMP-3377]: https://searchbroker.atlassian.net/browse/EMP-3377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: migrating base-rating component using defineComponent sintax

---

packages/x-components/src/components/location-provider.vue

[EMP-3541](https://searchbroker.atlassian.net/browse/EMP-3541)
For the vue 3 migration we need to migrate components to 2.7
Follow the docs in the component to tests that the feature still works correctly
[EMP-3541]: https://searchbroker.atlassian.net/browse/EMP-3541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-3541]: https://searchbroker.atlassian.net/browse/EMP-3541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: migrate location-provider component to vue 2.7

---

packages/x-components/src/composables/use-hybrid-inject.ts

[EMP-3636](https://searchbroker.atlassian.net/browse/EMP-3636)
`useHybridInject` and vue's regular `inject` weren't behaving the same, so we made some changes in the composable.
Handling reactiveness wasn't working as expected.
Use `useHybridInject` to inject the snippet config, wrap that call in a `ref` and try to watch changes in the `filters` property when changing its array value.
[EMP-3636]: https://searchbroker.atlassian.net/browse/EMP-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change useHybridInject so it works more like vue inject

---

packages/x-components/src/x-modules/next-queries/store/__tests__/getters.spec.ts
packages/x-components/src/x-modules/next-queries/store/getters/next-queries-query.getter.ts
packages/x-components/src/x-modules/next-queries/store/getters/request.getter.ts
packages/x-components/src/x-modules/next-queries/store/index.ts
packages/x-components/src/x-modules/next-queries/store/module.ts
packages/x-components/src/x-modules/next-queries/store/types.ts
packages/x-components/src/x-modules/next-queries/wiring.ts

Make Next Queries requests take into account when a query is selected along with a related tag:
* Make NQ `storeModule` have a RTs array in the state to save the selected RTs
* Make NQ `storeModule` have a mutation to update the RTs in the state
* Make NQ `storeModule` have a query getter to concat the query with the RTs (if selected)
* Make NQ `request` use the query getter.
* Make NQ wiring react to the event `SelectedRelatedTagsChanged` & call `setRelatedTags` mutation
Currently, the Next Queries module doesn’t take into account the selected related tags. This creates some weird scenarios like having NQ when searching for novela negra but not having NQ when searching for `novela` and …

Fix:  Next Queries not being calculated when using Related Tags

---

packages/x-components/src/components/__tests__/page-loader-button.spec.ts
packages/x-components/src/components/page-loader-button.vue

A component to request the new page instead of the regular infinite scroll that we usually have. It will be placed below the results list, which will need to avoid passing the `v-infinite-scroll` directive to not collide with this page loader behaviour.
For the Carrefour setup we will need a component to request the new page instead of the regular infinite scroll that we usually have.
Add the component in the `Home` view, below the results list, and remove the `v-infinite-scroll` directive from the `ResultsList`:
```
<LocationProvider location="results">
<ResultsList>
..... // current code
</ResultsList>
</LocationProvider>
<LocationProvider location="results">
<PageLoaderButton …
```

Feature: Create load next page component

---

packages/x-components/src/composables/__tests__/use-alias-api.spec.ts
packages/x-components/src/composables/index.ts
packages/x-components/src/composables/use-alias-api.ts
packages/x-components/src/composables/use-getter.ts
packages/x-components/src/composables/use-state.ts

The [x-plugin.alias.ts](https://github.com/empathyco/x/blob/main/packages/x-components/src/plugins/x-plugin.alias.ts) is just a proxy to get some data from the store. Currently is using the $store property of the component instance. We should get rid of that dependency and instead make use of the useStore/useState/useGetter composable we already have. 
To test it, you can create a `Test` component, access to `useAliasApi` composable and check the reactivity of the props.
The `Test` component could be something like this:
```
<template>
<div>
<span>{{ scroll }}</span>
<span>{{ historyQueries[0].query }}</span>
</div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import { useAliasApi } from '../composables';
export default defineComponent({
setup() {
const xAliasAPI …
```

refactor: create alias api composable

---

packages/x-components/src/composables/use-hybrid-inject.ts

[EMP-3798](https://searchbroker.atlassian.net/browse/EMP-3798)
useHybridInject doesn’t work well with arrays, we need to add a check to make list dynamic using ref
[EMP-3798]: https://searchbroker.atlassian.net/browse/EMP-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make arrays reactive with ref in useHybridInject

---

packages/x-components/src/__tests__/utils.ts
packages/x-components/src/components/modals/__tests__/base-id-modal-close.spec.ts
packages/x-components/src/components/modals/__tests__/base-id-modal-open.spec.ts
packages/x-components/src/components/result/__tests__/base-result-link.spec.ts
packages/x-components/src/components/result/__tests__/base-result-rating.spec.ts
packages/x-components/src/components/result/__tests__/result-variants-provider-and-selector.spec.ts
packages/x-components/src/components/suggestions/__tests__/base-suggestion.spec.ts
packages/x-components/src/composables/use-x-bus.ts
packages/x-components/src/x-modules/history-queries/components/__tests__/history-query.spec.ts
packages/x-components/src/x-modules/next-queries/components/__tests__/next-query.spec.ts
packages/x-components/src/x-modules/popular-searches/components/__tests__/popular-search.spec.ts
packages/x-components/src/x-modules/query-suggestions/components/__tests__/query-suggestion.spec.ts
packages/x-components/src/x-modules/semantic-queries/components/__tests__/semantic-query.spec.ts

This PR refactors the use-xbus composable to first try to reuse the same from the XPlugin and fallback to the default x-bus implementation if the XPlugin has not been instantiated.

feat: make `useXBus` get bus from `XPlugin`

---

packages/_vue3-migration-test/src/App.vue
packages/_vue3-migration-test/src/components/index.ts
packages/_vue3-migration-test/src/components/test-base-event-button.vue
packages/_vue3-migration-test/src/main.ts
packages/_vue3-migration-test/src/router.ts
packages/x-components/src/components/__tests__/base-event-button.spec.ts
packages/x-components/src/components/animations/animate-width.vue
packages/x-components/src/components/animations/fade.vue
packages/x-components/src/components/base-event-button.vue
packages/x-components/src/components/column-picker/__tests__/base-column-picker-list.spec.ts
packages/x-components/src/views/home/Home.vue
packages/x-components/src/x-modules/facets/components/__tests__/clear-filters.spec.ts
packages/x-components/src/x-modules/facets/components/filters/__tests__/all-filter.spec.ts
packages/x-components/src/x-modules/history-queries/components/__tests__/clear-history-queries.spec.ts
packages/x-components/src/x-modules/history-queries/components/__tests__/remove-history-query.spec.ts
packages/x-components/src/x-modules/search-box/components/__tests__/clear-search-input.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/sort-list.spec.ts
packages/x-components/src/x-modules/search/components/__tests__/sort-picker-list.spec.ts

Migrate `base-event-button` component to Composition API
⚠️ Pending to migrate animations used in the `vue3` package to support `INSTANCE_LISTENERS: false` needed for this PR -> ✅ Solved here: https://github.com/empathyco/x/pull/1457/commits/ae291b4397284879d65f98b7ce41b88095c0069a
https://vuejs.org/guide/components/attrs#nested-component-inheritance
2nd round: Recovered `INSTANCE_LISTENERS: 'suppress-warning'` until Vue3 ecosystem integration (build and testing)
EMP-3965

refactor(base-event-button): migrate base-event-button component to Composition API

---

packages/x-adapter/src/http-clients/__tests__/fetch.http-client.spec.ts
packages/x-adapter/src/http-clients/fetch.http-client.ts
packages/x-adapter/src/http-clients/types.ts

From Play we need to perform Search requests that must necessarily include some specific parameters in the body, even if their values are empty (`''`).
These parameters are used to preview products and attributes boosts so the empty value tells the Search service that no boosts must be applied in the response even if they exist in the database.
This way there would be three different scenarios depending on the value of these parameters:
1. No parameters are sent -> Search must apply the boosts stored in the database (default behaviour).
2. Parameters with specific values (not empty) are sent -> Search must ignore the boosts stored in the database AND apply the ones specified in the parameters.
3. [NEW] Parameters with empty values are sent -> Search must just ignore the boosts stored in …

feat: Support empty params on adapter's requests

---

packages/_vue3-migration-test/src/App.vue
packages/_vue3-migration-test/src/components/test-base-event-button.vue
packages/x-components/src/components/__tests__/global-x-bus.spec.ts
packages/x-components/src/components/column-picker/base-column-picker-dropdown.vue
packages/x-components/src/components/column-picker/base-column-picker-list.vue
packages/x-components/src/components/global-x-bus.vue
packages/x-components/src/composables/__tests__/use-x-bus.spec.ts
packages/x-components/src/composables/use-$x.ts
packages/x-components/src/composables/use-x-bus.ts
packages/x-components/src/views/pdp.vue
packages/x-components/src/x-modules/search/components/banners-list.vue

`useXBus.on` function registers the subscriptions itself to be able to unsubscribe once the component is unmounted.
`useXBus.emit` now returns the emission promise.
Highlights: 
- No more needed `KeepAlive` in the `_vue3` package since components doesn't have active subscriptions once the component is unmounted.
-  Now, the boolean `withMetada` is required `$x.on('ColumnsNumberProvided', false)`. It is because improve type safe when `$x.on` and conditional metadata
- `useXbus` has improved the type infer. No more needed type assertions to retrieve payload with or without `metadata`. Like: https://github.com/empathyco/x/compare/EMP-4083-usexbus-unmounted?expand=1#diff-1c8a891163d5ec75f3348e5d88e9c5a8560fc77b7d7b3ee9f682be58ae209d90R23 or …

feat(use-x-bus): unsubscribe from bus events when component is unmounted

---

packages/x-components/src/components/global-x-bus.vue
packages/x-components/src/components/no-element.ts
packages/x-components/src/composables/__tests__/use-no-element-render.spec.ts
packages/x-components/src/composables/use-no-element-render.ts
packages/x-components/src/x-modules/facets/components/preselected-filters.vue

This PR refactors the `useNoElementRender` composable to return the full VNodes array from the default slot, instead of just the first VNode. The former approach only works for Vue 2 where components can only have one single root node. However, Vue 3 allows having multiple root nodes for a component and it will break the `NoElement` usage. 
Thanks to the composition API is posible to use a render function that returns multiple VNodes via the return of the setup method. See [declaring render functions](https://vuejs.org/guide/extras/render-function#declaring-render-functions)
Once this PR is merged we could rollback some changes from #1460 and save the extra div that were needed here for `BannersList`, `ResultsList`, `PromotedsList` and `NextQueriesList`

refactor(noElement): use the full array of VNodes from the default slot

---

packages/_vue3-migration-test/src/x-modules/empathize/test-empathize.vue
packages/x-components/src/x-modules/empathize/components/empathize.vue

The empathize content could be dynamic and change from having something to show to not multiple times. The current approach is not reactive and will lead to scenarios where the empathize is open with nothing to show

fix: avoid showing empty empathize

---

packages/x-components/src/x-modules/history-queries/components/clear-history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue
packages/x-components/src/x-modules/history-queries/components/history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-query.vue
packages/x-components/src/x-modules/history-queries/components/my-history.vue
packages/x-components/src/x-modules/history-queries/components/remove-history-query.vue
packages/x-components/src/x-modules/history-queries/x-module.ts

- `xComponentMixin(historyQueriesXModule)` mixin is executed as soon as the component is imported, before mounting it.
- `useRegisterXModule(historyQueriesXModule)` composable is executed once the component is mounted.
- Sometimes in setups, we need to check some state values before mounting the component (`v-if`). So using the composable, the `XModule` has not been registered when the check is executed because the component has not been mounted yet.
Registering it as soon as we can, in the `XModule` creation itself.
- Every component must have an import of its `XModule` to assign the `xModule` name to itself.
> A module code is evaluated only the first time when imported.
If the same module is imported into multiple other modules, its code is executed only once, upon the first import. …

fix(history-queries): ensuring history-queries x-module registration before using components

---

packages/_vue3-migration-test/src/router.ts
packages/_vue3-migration-test/src/x-modules/history-queries/components/index.ts
packages/_vue3-migration-test/src/x-modules/history-queries/components/test-history-queries.vue
packages/_vue3-migration-test/src/x-modules/history-queries/components/test-my-history.vue
packages/_vue3-migration-test/src/x-modules/history-queries/index.ts
packages/_vue3-migration-test/src/x-modules/index.ts
packages/x-components/src/composables/__tests__/use-getter.spec.ts
packages/x-components/src/x-modules/history-queries/components/clear-history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue
packages/x-components/src/x-modules/history-queries/components/history-queries.vue
packages/x-components/src/x-modules/history-queries/components/history-query.vue
packages/x-components/src/x-modules/history-queries/components/my-history.vue
packages/x-components/src/x-modules/history-queries/components/remove-history-query.vue
packages/x-components/src/x-modules/history-queries/x-module.ts

Migrate history-queries x-module to composition API.
Components to migrate: 
- `HistoryQuery`
- `HistoryQueries`
- `ClearHistoryQueries`
-  `HistoryQueriesSwitch`
- `MyHistory`
- `RemoveHistoryQuery`
[EMP-416]: https://searchbroker.atlassian.net/browse/EMP-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: migrate history queries x module to composition api

---

packages/_vue3-migration-test/package.json
packages/_vue3-migration-test/src/main.ts
packages/_vue3-migration-test/src/router.ts
packages/_vue3-migration-test/src/x-modules/index.ts
packages/_vue3-migration-test/src/x-modules/query-suggestions/components/index.ts
packages/_vue3-migration-test/src/x-modules/query-suggestions/components/test-query-suggestions.vue
packages/_vue3-migration-test/src/x-modules/query-suggestions/index.ts
packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts
packages/x-components/src/x-modules/query-suggestions/components/__tests__/query-suggestion.spec.ts
packages/x-components/src/x-modules/query-suggestions/components/__tests__/query-suggestions.spec.ts
packages/x-components/src/x-modules/query-suggestions/components/query-suggestion.vue
packages/x-components/src/x-modules/query-suggestions/components/query-suggestions.vue
packages/x-components/src/x-modules/query-suggestions/x-module.ts
pnpm-lock.yaml

[EMP-4163]: https://searchbroker.atlassian.net/browse/EMP-4163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Migrate `query suggestions` module to composition api

---

packages/x-components/src/x-modules/search/events.types.ts
packages/x-components/src/x-modules/search/store/module.ts
packages/x-components/src/x-modules/search/store/types.ts
packages/x-components/src/x-modules/search/wiring.ts
packages/x-components/tests/e2e/reload-search.feature
packages/x-components/tests/e2e/reload-search/reload-search.spec.ts

We need a way to *refresh* the results displayed on the search layer.
This requirement comes from the Backroom's next functionality, boost&bury of single products by query. After boosting or burying a product, we need a way to re-do the current search and refresh the results to see the change applied.
The idea is to emit the event `ReloadSearchRequested` through the x-bus and trigger a mutation on the state that triggers the search request.

feat: add the capability to reload the current search

---

packages/_vue3-migration-test/src/main.ts
packages/_vue3-migration-test/src/router.ts
packages/_vue3-migration-test/src/x-modules/identifier-results/components/index.ts
packages/_vue3-migration-test/src/x-modules/identifier-results/components/test-identifier-results.vue
packages/_vue3-migration-test/src/x-modules/identifier-results/index.ts
packages/_vue3-migration-test/src/x-modules/identifier-results/x-module.ts
packages/_vue3-migration-test/src/x-modules/index.ts
packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts
packages/x-components/src/x-modules/identifier-results/components/identifier-result.vue
packages/x-components/src/x-modules/identifier-results/components/identifier-results.vue
packages/x-components/src/x-modules/identifier-results/x-module.ts

[EMP-4312]: https://searchbroker.atlassian.net/browse/EMP-4312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Migrate `identifier-results` x-module to composition API

---

packages/x-components/src/x-modules/facets/components/facets/facets-provider.vue

[EMP-4315]: https://searchbroker.atlassian.net/browse/EMP-4315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Migrate `facets provider` component to use Composition API

---

packages/_vue3-migration-test/src/components/extra-params/test-renderless-extra-param.vue
packages/_vue3-migration-test/src/components/index.ts
packages/_vue3-migration-test/src/router.ts
packages/x-components/src/x-modules/extra-params/components/__tests__/renderless-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/renderless-extra-param.vue

feat(renderless-extra-param): migrate to composition API

---

packages/_vue3-migration-test/src/x-modules/facets/components/test-filters.vue
packages/x-components/src/x-modules/facets/components/filters/__tests__/editable-number-range-filter.spec.ts
packages/x-components/src/x-modules/facets/components/filters/editable-number-range-filter.vue
packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
packages/x-components/src/x-modules/facets/components/filters/number-range-filter.vue

```
feat(filters)!: migrate editableNumberRangeFilter, hierarchicalFilter and numberRangeFilter to composition API
BREAKING-CHANGE: use cssClasses prop to pass classes through the component in Vue 3 instead of class or :class when using hierarchicalFilter or numberRangeFilter components
```

feat: Migrate filters components to Composition API

---

packages/_vue3-migration-test/src/x-modules/scroll/test-scroll.vue
packages/_vue3-migration-test/src/x-modules/scroll/x-module.ts
packages/x-components/src/components/no-element.ts
packages/x-components/src/x-modules/scroll/components/main-scroll-item.vue
packages/x-components/src/x-modules/scroll/components/main-scroll.vue

Obtain observed container element reliably to work with any Vue version
With the following code, we are able to retrieve the root element of a renderless component in both Vue 2 and Vue 3:
```TS
onMounted(() => {
containerRef.value = getCurrentInstance()?.proxy?.$el;
});
...
return () => slots.default?.()[0];
```
In Vue 2 and Vue 3:
- `slots.default?.()` -> Gives an array of `vNodes` | `[0]` Gets the `vNode` root and renders it 
IF we would return the full array of `vNodes` `return () => slots.default?.()`:
- In Vue 2: Renders the `vNodes` as it is without problem, and we can get the root element with `getCurrentInstance()?.proxy?.$el`. Only if the default slot has a single node, otherwise, Vue will throw an error 
`[Vue warn]: Multiple root nodes returned from render function. Render …

fix(main-scroll): obtain observed container element reliably to work with any Vue version

---

packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview-list.spec.ts
packages/x-components/src/x-modules/queries-preview/components/query-preview-list.vue

This PR addresses a bug in the `QueryPreviewList` component that prevents it from loading the next list of queries if the new collection partially overlaps with the previous one. The issue occurs due to the resetting of the `queriesStatus`, which causes queries that were already loaded to get stuck in a loading state. This prevents the necessary actions from being triggered to load the remaining queries.
Added a unit test for this scenario and it can be tested manually by changing using some queries to preview and then adding a new one to the collection:
```ts
let queriesPreviewInfo: QueryPreviewInfo[] = [{ query: 't-shirt' }];
queriesPreviewInfo = [{query: 't-shirt'}, {query: 'jeans'}];
```

fix(queryPreviewList): repeated query loading issue

---

packages/x-components/src/services/directional-focus-navigation.service.ts
packages/x-components/src/utils/__tests__/html.spec.ts
packages/x-components/src/utils/html.ts
packages/x-components/src/x-modules/empathize/components/empathize.vue

This pull request addresses the issues with the `BaseKeyboardNavigation` component when the Shadow DOM is enabled. The following changes have been made to ensure seamless keyboard navigation and event handling within Shadow DOM boundaries. 
These changes should be tested along with `x-archetype` with Shadow DOM enabled. You can check that the predictive layer in the empathize component is now reachable with the keyboard. An additional unit test for retrieving the active element as added.

fix(BaseKeyboardNavigation): navigation with Shadow DOM enabled

---

packages/_vue3-migration-test/src/x-modules/facets/components/test-facets.vue
packages/x-components/src/components/modals/base-id-modal-close.vue
packages/x-components/src/components/result/__tests__/result-variants-provider-and-selector.spec.ts
packages/x-components/src/components/result/result-variants-provider.vue
packages/x-components/src/views/home/display-result-provider.vue
packages/x-components/src/x-modules/extra-params/components/__tests__/renderless-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/renderless-extra-param.vue
packages/x-components/src/x-modules/facets/components/lists/__tests__/selected-filters.spec.ts
packages/x-components/src/x-modules/facets/components/lists/exclude-filters-with-no-results.vue
packages/x-components/src/x-modules/facets/components/lists/selected-filters.vue
packages/x-components/src/x-modules/facets/components/lists/sorted-filters.vue

`NoElement` component is gonna be an issue in terms of attribute inheritance on Vue3 because `Fragment` creation to support multiple root nodes. To solve it, there is a workaround we can achieve. This is to manage the `vNodes` creation in the render function in the components themselves (moreover, without generating breaking changes). 
To do it, we must refactor them in two steps:
- Components which will work in both Vue version because they don't have fallback content in the slots (this PR)
- Components which won't work in both Vue versions because they require additional `props` in the `h` function, and they are breaking-change in the Vue migration (future PR once we have Vue3 officially)
Components refactored in this PR to get rid of using `NoElement` component:
- …

refactor(no-element): towards getting rid of no-element component

---

packages/x-components/src/components/base-grid.vue
packages/x-components/src/components/global-x-bus.vue
packages/x-components/src/components/snippet-callbacks.vue
packages/x-components/src/views/home/Home.vue

This PR makes just the necessary changes to make the internal demo app to be working again:
- Refactors the home component to drop the MultiColumnMaxWidthLayout deprecated component. 
- Removes the animations until they are working with vue 3
- BREAKING-CHANGE: refactors the GlobalXBus to use a prop to receive the listeners instead of relying on attributes.

Make internal demo app functional

---

packages/_vue3-migration-test/src/x-modules/facets/components/test-filters.vue
packages/x-components/src/components/animations/animate-width.vue
packages/x-components/src/components/animations/collapse-height.vue
packages/x-components/src/components/animations/collapse-width.vue
packages/x-components/src/components/animations/cross-fade.vue
packages/x-components/src/components/animations/fade-and-slide.vue
packages/x-components/src/components/animations/fade.vue
packages/x-components/src/components/animations/staggered-fade-and-slide.vue
packages/x-components/src/components/base-event-button.vue
packages/x-components/src/components/modals/base-events-modal-close.vue
packages/x-components/src/components/modals/base-events-modal-open.vue
packages/x-components/src/components/modals/close-main-modal.vue
packages/x-components/src/components/modals/open-main-modal.vue
packages/x-components/src/components/panels/base-id-toggle-panel-button.vue
packages/x-components/src/components/result/base-result-add-to-cart.vue
packages/x-components/src/components/suggestions/base-suggestion.vue
packages/x-components/src/store/x.module.ts
packages/x-components/src/views/home/aside.vue
packages/x-components/src/views/home/result.vue
packages/x-components/src/x-modules/facets/components/facets/facets-provider.vue
packages/x-components/src/x-modules/facets/components/filters/renderless-filter.vue
packages/x-components/src/x-modules/facets/components/lists/selected-filters.vue
packages/x-components/src/x-modules/queries-preview/components/query-preview-button.vue
packages/x-components/src/x-modules/scroll/components/main-scroll-item.vue
packages/x-components/src/x-modules/scroll/components/scroll.vue
packages/x-components/src/x-modules/search-box/components/search-input.vue

This PR resolves several warnings when running the internal demo app:
- Initial warning about overwriting the store modules.
- Warnings about `v-on="listeners"` deprecation.
- Removal of `v-bind="attrs"` and `inheritAttrs=false`, because Vue3 implemented by default the [attributes inheritance](https://vuejs.org/guide/components/attrs). 
- Fixing warning on `attrs` inheritance in RenderlessFilter.
- Fixing some components that throw warnings because the render function was incorrect.

refactor(components): remove warnings first batch

---

packages/x-components/src/directives/infinite-scroll.ts

Getting xBus from `XPlugin` instead `useXBus` composable.
As it is a directive and not a component, the composable uses `inject` and `onBeforeUnmount` which are not allowed out of component context, throwing the following warnings

fix(infinite-scroll): getting xBus from XPlugin instead useXBus composable

---

packages/x-components/src/components/modals/main-modal.vue

Currently, when some customers want to implement features without leaving the search engine (ex. opening pop-ups), their flow is broken due to the `UserClickedOutOfMainModal` event being fired.
A recent example is Tous, trying to open a modal when the add2Cart button is clicked, or Carrefour, with their wishlist integration. 
1. in `Home.vue`:
```
<MainModal
:animation="modalAnimation"
:openEvents="['UserClickedOpenX', 'UserOpenXProgrammatically', 'MyCustomXEvent']"
:outOfModalClickEvent="null"
>.........</MainModal>
```
2. Check devTools events' props are updated accordingly.
3. Change change `x-modal` styles to check that clicking out of the modal doesn't close it, + query & results are not being cleared (so the `UserClickedOutOfMainModal` event is not being fired):
```
.x-modal { …
```

feature: Make Main Modal events configurable via props

---

packages/x-components/src/components/result/__tests__/result-variants-provider-and-selector.spec.ts
packages/x-components/src/components/result/result-variants-provider.vue
packages/x-components/src/wiring/events.types.ts
packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
packages/x-components/src/x-modules/queries-preview/store/module.ts
packages/x-components/src/x-modules/queries-preview/store/types.ts

Currently, if we are working with results with variants, we cannot update the result information when switching variants in the preview queries.
That's why it was necessary to carry out this task, which involves modifying the payload of the UserSelectedAResultVariant event to send the hash of the preview query of the result to be modified, and creating a mutation in the queriesPreview module to update the result with the new information.
Try in primor setup to install this x version locally and change variants in a query preview result.
And add this code in the `plugin.options.ts`:
```
queriesPreview: {
wiring: {
UserSelectedAResultVariant: {
updateResultVariantWire
}
}
},
```
```
const updateResultVariantWire = createWireFromFunction<XEventPayload<'UserSelectedAResultVariant'>>(
({ …
```

feat: update result information in the QPs

---

packages/x-components/src/x-modules/search/store/module.ts

Fix issue with emitters and `no-deep` watchers for arrays in Vue3 https://v3-migration.vuejs.org/breaking-changes/watch.html

fix(search): replace results state to append new results instead of pushing them

---

packages/x-archetype-utils/package.json
packages/x-archetype-utils/rollup.config.mjs
packages/x-archetype-utils/src/__tests__/i18n.plugin.spec.ts
packages/x-archetype-utils/src/i18n/i18n.plugin.ts
packages/x-archetype-utils/src/i18n/i18n.types.ts
pnpm-lock.yaml

Updates vue related deps for `@empathyco/x-archetype-utils`. This package contains the custom i18n plugin used in x-archetype. 
Update vue18n to 9.14.0 and make the necessary adjustments.
BREAKING CHANGE: This package now is only compatible with vue 3

feat: bump vue18n version

---

.github/workflows/release-alpha.yml

Small change to be able to select the branch to release from. This will allow us to create a release from the vue 3 RC branch and do proper testing in the archetype or other setups.

ci: allow to select branch to release from

---

packages/x-archetype-utils/src/build/rollup/rollup.config.ts

Replace `injectCss` X function for `(css) => window.xCSSInjector.addStyle({ source: css });` anonymous function at setup build time. The anonymous function executes the custom CSS injector `xCSSInjector` to inject styles.
Setup build example with `ShadowRoot` activated
Setup bundle example

feat(rollup): update replace config to align CSS injector with Vue 3

---

packages/x-archetype-utils/package.json
packages/x-components/package.json

BREAKING CHANGE:
@empathyco/x-components v6 and @empathyco/x-archetype-utils v2 are only compatible with Vue 3 and if you are looking for the Vue 2 versions, take look at the main brach.

feat: bump packages versions

---

packages/x-components/src/components/__tests__/base-switch.spec.ts
packages/x-components/src/components/base-switch.vue
packages/x-components/src/x-modules/history-queries/components/__tests__/history-queries-switch.spec.ts
packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue

`HistoryQueriesSwitch` was not migrated correctly to Vue3 and was not working. It was required to change the `v-model` prop default name which changed in Vue3 (`value` to `modelValue`)
We are also introducing the BREAKING CHANGE of removing the event `change` in favor of the `update:modelValue` in the `BaseSwitch` component to follow the Vue3 naming.
Source: https://v3-migration.vuejs.org/breaking-changes/v-model.html

fix(history-queries-switch): migrate value to modelValue

---

packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue

This PR checks if the extra params object has really changed to avoid unnecessary event emissions. 
In some customers, when a snippetConfig callback is executed, `ExtraParamsProvided` and `ExtraParamsChanged` events are fired even if they have not changed (and, as a consequence all the rest of the chained events that react to ExtraParamsChanged event emission). 
An [open PR](https://github.com/empathyco/x-primor/pull/143) can be used to see the implementation when a callback is executed & check: 
* No events are emitted if the `extraParams` object has not changed
* No unnecessary endpoint calls (regarding chained events).
[RST-2269]: https://searchbroker.atlassian.net/browse/RST-2269?atlOrigin=eyJpIjoiNWRkNTljNzYx …

fix: Snippet config extra params reactivity

---

packages/x-components/build/tools/inject-css.js

This PR enhances our default css injector to prevent it from breaking builds in SSR mode where the document object might not be available

fix: avoid breaking ssr builds

---

packages/x-components/package.json

This pull request includes a minor update to the `packages/x-components/package.json` file to ensure compatibility with the latest version of Vue.
Dependencies update:
* [`packages/x-components/package.json`](diffhunk://#diff-a01ad56f8bacdc7b865e92dfbad7968f847e98320952533ce6c6db4b479deec0L88-R88): Updated the `vue` peer dependency from version `~3.4.31` to `^3.5.12` to support newer versions of Vue.

build: use vue latest version as peer dependency

---

packages/x-types/src/index.ts
packages/x-types/src/response/search-response.model.ts
packages/x-types/src/stats.model.ts

feat: add stats to search response

---

packages/x-components/src/components/items-list.vue
packages/x-components/src/components/result/base-result-image.vue
packages/x-components/src/types/animation-prop.ts
packages/x-components/src/utils/options-api.ts
packages/x-components/src/x-modules/facets/components/facets/facets.vue
packages/x-components/src/x-modules/facets/components/lists/selected-filters-list.vue
packages/x-components/src/x-modules/search/components/results-list.vue

`animationProp` was a constant used in somewhen, but with Vue3 we have a type created `AnimationProp`.
This PR removes the old constant and refactors where it was used.
It also simply the `AnimationProp` type to improve the usability, compiling it as
```TS
* String for 'ul'
* Object for `DefineComponent` type
* Function for `() => NoElement`
```

fix(animation-prop): decommission old animation-prop.ts and generalize the new one

---

packages/x-components/src/x-installer/x-installer/types.ts

Allow `installExtraPlugins` to return a Promise in the type.
The implementation/usage already allows it
https://github.com/empathyco/x/blob/48cedcd9087dc546f2f716aa41802743eb34989a/packages/x-components/src/x-installer/x-installer/x-installer.ts#L246-L250

fix(types): update installExtraPlugins to support Promise return type

---

packages/x-components/src/components/modals/__tests__/base-modal.spec.ts
packages/x-components/src/components/modals/base-modal.vue
packages/x-components/src/views/home/Home.vue

Include the possibility to update the `referenceSelector`, which determines the position of the empathy modal.

feat: make reference selector reactive

---

packages/x-tailwindcss/src/x-tailwind-plugin/components/layout/item.ts

This pull request includes a minor change to the `item` function in the `layout/item.ts` file. The change involves updating class selectors to ensure proper styling.
* [`packages/x-tailwindcss/src/x-tailwind-plugin/components/layout/item.ts`](diffhunk://#diff-e44d3287b5a4e2d2fefef7123da81f40b1c88c700365e48fb858cdc6bb3009a1L30-R30): Changed the class selectors from `.layout-overlap` and `.layout-overlap-from-top` to `.x-layout-overlap` and `.x-layout-overlap-from-top` for better specificity and consistency.

fix(x-tailwindcss): use complete class name in css rule for layout items

---

packages/x-components/src/x-modules/extra-params/components/__tests__/extra-params.spec.ts
packages/x-components/src/x-modules/extra-params/components/extra-params.vue

This PR gives more priority to the `values` prop over `params` state in the `ExtraParamsProvided` payload
MotiveMarket renders the `ExtraParams` component with each area changing, passing a new `values` prop each time. The store state has already `params` of the previous `area`, so emits `ExtraParamsProvided` XEvent with old `area` because in the merge, `params` from the state has more priority.

fix(extra-params): give more priority to values prop over params state in the ExtraParamsProvided payload
