empathyco/x

packages/logger/LICENSE, packages/logger/README.md
EX-3909
Include LICENSE and README file
To add clarity to each package we should have always a LICENSE file and an updated README.
`main`
No tests
=> docs: Add LICENSE and README files

packages/get-safe-property-chain/CHANGELOG.md, packages/get-safe-property-chain/LICENSE, packages/get-safe-property-chain/README.md, packages/get-safe-property-chain/package.json
=> docs: Add LICENSE and update package.json files

.github/CONTRIBUTING.md, packages/storage-service/LICENSE, packages/storage-service/package.json
=> docs: add `LICENSE` and update `package.json`

packages/deep-merge/package.json, packages/eslint-plugin-x/package.json, packages/get-safe-property-chain/package.json, packages/logger/package.json, packages/storage-service/package.json
=> chore: improve package.json repository field

packages/search-types/CHANGELOG.md, packages/search-types/LICENSE, packages/search-types/README.md, packages/search-types/package.json
Updates the search-type project with the shape of the rest of the monorepo packages.
=> feat: update `search-types` package information

.github/CONTRIBUTING.md, packages/search-adapter/LICENSE, packages/search-adapter/README.md, packages/search-adapter/api-extractor.json, packages/search-adapter/package.json
Updates the  `x-adapter` package information to match the rest of the ecosystem.
=> feat: update `search-adapter` package information

packages/x-components/tests/e2e/specs/cucumber/common-steps.spec.ts, packages/x-components/tests/e2e/specs/cucumber/popular-searches.spec.ts
=> chore: fix e2e tests

packages/x-components/src/__stubs__/banners-stubs.factory.ts, packages/x-components/src/x-modules/search/components/__tests__/banner.spec.ts, packages/x-components/src/x-modules/search/components/banner.vue, packages/x-components/src/x-modules/search/components/index.ts
Adds the Banner component
Add the example into a view and check that everything is working fine.
=> feat(search): add Banner component

packages/x-components/cypress.json, packages/x-components/package.json, packages/x-components/tests/e2e/cucumber/common-steps.spec.ts, packages/x-components/tests/e2e/cucumber/search-box.feature, packages/x-components/tests/e2e/cucumber/search-box.spec.ts
Increase timeout in cypress test
=> chore: fix e2e testing

packages/x-components/src/components/layouts/layout.vue, packages/x-components/src/design-system/components/layout/default.scss, packages/x-components/src/design-system/components/layout/default.tokens.scss, packages/x-components/src/directives/infinite-scroll/infinite-scroll.ts, packages/x-components/src/views/Layout.vue
EX-4489
This PR fixes the infinite scroll bug in Chrome, changing the threshold to 0.99
Also fixes the position of the scroll-to-top inside the `layout.vue` component
=> fix(infinite-scroll): fix infinite scroll threshold and scroll to top layout

packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts, packages/x-components/src/x-modules/search/store/module.ts, packages/x-components/src/x-modules/search/store/types.ts
EX-4492
Fix the repeated banners and promoted on page load
=> fix(banners): fix repeated banners and promoted on page load

packages/search-types/src/facet/filter/hierarchical-filter.model.ts
EX-4493
Update the model of the HierarchicalFilter children
=> chore(facets): fix HierarchicalFilter children model

packages/x-components/build/rollup.config.ts, packages/x-components/src/design-system/components/layout/default.scss, packages/x-components/src/design-system/components/layout/default.tokens.scss, packages/x-components/src/design-system/components/list/default.scss, packages/x-components/src/design-system/components/option-list/bottom.scss, packages/x-components/src/design-system/components/option-list/bottom.tokens.scss, packages/x-components/src/design-system/components/option-list/default.scss, packages/x-components/src/design-system/components/suggestion-group/default.scss, packages/x-components/src/design-system/components/suggestion-group/default.tokens.scss, packages/x-components/src/design-system/components/suggestion/default.tokens.scss, packages/x-components/src/design-system/components/typography/default.scss, packages/x-components/src/design-system/components/typography/default.tokens.scss
EX-4497
Fix some wrong renamed tokens
=> chore(design-system): fix undefined tokens

.github/CONTRIBUTING.md, README.md
EX-4538
Change broken links to main packages
*It seems redundant, but it could work as an extra security layer to avoid errors*
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
See how your change affects other areas of the code, etc.
=> docs: Update README broken links

packages/x-components/src/index.ts, packages/x-components/src/store/x.module.ts, packages/x-components/src/x-modules/tagging/x-module.ts, packages/x-components/src/x-modules/url/config.types.ts, packages/x-components/src/x-modules/url/events.types.ts, packages/x-components/src/x-modules/url/index.ts, packages/x-components/src/x-modules/url/store/emitters.ts, packages/x-components/src/x-modules/url/store/index.ts, packages/x-components/src/x-modules/url/store/module.ts, packages/x-components/src/x-modules/url/store/types.ts, packages/x-components/src/x-modules/url/wiring.ts, packages/x-components/src/x-modules/url/x-module.ts, packages/x-components/src/x-modules/x-modules.types.ts
=> Add new empty module

packages/x-components/CHANGELOG.md
Feel free to suggest more changes
EX-4586
=> chore: fix changelog

packages/search-adapter/src/types/requests.types.ts
=> Update search request type to include the new extra params

packages/x-components/src/views/FullApp.vue, packages/x-components/src/x-modules/extra-params/components/renderless-extra-param.vue, packages/x-components/src/x-modules/search/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/search/store/getters/request.getter.ts, packages/x-components/src/x-modules/search/store/module.ts, packages/x-components/src/x-modules/search/store/types.ts, packages/x-components/src/x-modules/search/wiring.ts
=> Reset search state when extra params change

packages/x-components/src/x-modules/next-queries/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/next-queries/store/getters/request.getter.ts, packages/x-components/src/x-modules/next-queries/store/module.ts, packages/x-components/src/x-modules/next-queries/store/types.ts, packages/x-components/src/x-modules/next-queries/wiring.ts
[EX-4624](https://searchbroker.atlassian.net/browse/EX-4624)
Adds extra params to the Next Queries request
=> feat(next-queries): nq extra params & state reset when they change

packages/x-components/src/x-modules/related-tags/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/related-tags/store/getters/request.getter.ts, packages/x-components/src/x-modules/related-tags/store/module.ts, packages/x-components/src/x-modules/related-tags/store/types.ts, packages/x-components/src/x-modules/related-tags/wiring.ts, packages/x-components/src/x-modules/search/wiring.ts
=> Related Tags: Add new extra params event in the wiring and update the state

packages/x-components/src/x-modules/recommendations/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/recommendations/store/getters/request.getter.ts, packages/x-components/src/x-modules/recommendations/store/module.ts, packages/x-components/src/x-modules/recommendations/store/types.ts, packages/x-components/src/x-modules/recommendations/wiring.ts
=> feat(recommendations): recommendations extra params and state reset on change

packages/x-components/src/x-modules/popular-searches/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/popular-searches/store/getters/request.getter.ts, packages/x-components/src/x-modules/popular-searches/store/module.ts, packages/x-components/src/x-modules/popular-searches/store/types.ts, packages/x-components/src/x-modules/popular-searches/wiring.ts
=> feat(popular-searches): add extra params feature to popular searches

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/plugins/x-plugin.alias.ts, packages/x-components/src/plugins/x-plugin.types.ts
=> feat(spellcheck): add spellchecked query to Alias API

packages/x-components/src/design-system/components/list/background.scss, packages/x-components/src/design-system/components/row/background.scss
=> feat(design-system): add lists background colors to Design System

packages/x-components/src/components/animations/collapse-from-top.vue, packages/x-components/src/components/animations/index.ts, packages/x-components/src/components/animations/translate-from-right.vue, packages/x-components/src/components/modals/base-modal.vue
EX-4696
This PR adds new TranslateFromRight animation, and also adds enter animation to BaseModal component overlay item.
=> feat(animations): add new TranslateFromRight animation

packages/x-components/src/design-system/components/shadow/shadow.scss, packages/x-components/src/design-system/components/shadow/shadow.tokens.scss, packages/x-components/src/views/design-system.vue
EX-4739
Design System "Utility Class" to add box shadows
=> feat(design-system): add `Shadow` component

packages/x-components/src/components/layouts/multi-column-max-width-layout.vue, packages/x-components/src/design-system/components/list/default.scss, packages/x-components/src/design-system/components/list/gap.scss, packages/x-components/src/design-system/components/list/gap.tokens.scss, packages/x-components/src/design-system/components/list/padding.scss, packages/x-components/src/design-system/components/list/padding.tokens.scss
=> fix(design-system): fix multiple issues in Design System

packages/x-components/src/design-system/base/size.tokens.scss, packages/x-components/src/design-system/components/button/secondary.scss, packages/x-components/src/design-system/components/list/default.scss, packages/x-components/src/design-system/components/list/gap.scss, packages/x-components/src/design-system/components/list/gap.tokens.scss, packages/x-components/src/design-system/components/list/padding.scss, packages/x-components/src/design-system/components/list/padding.tokens.scss, packages/x-components/src/design-system/utilities/background-color.scss, packages/x-components/src/design-system/utilities/border-color.scss, packages/x-components/src/design-system/utilities/border-radius.scss, packages/x-components/src/design-system/utilities/border-width.scss, packages/x-components/src/design-system/utilities/box-shadow.scss, packages/x-components/src/design-system/utilities/font-color.scss, packages/x-components/src/design-system/utilities/margin.scss, packages/x-components/src/design-system/utilities/padding.scss
=> chore(design-system): fix multiple issues in Design System

packages/x-components/src/design-system/utilities/margin.scss, packages/x-components/src/design-system/utilities/padding.scss
=> chore(design-system): fix utilities 00 cases

packages/x-components/src/x-modules/facets/service/facets.service.ts, packages/x-components/src/x-modules/facets/store/module.ts, packages/x-components/src/x-modules/facets/store/types.ts
=> refactor(facets): fix facets performance issues

packages/x-components/package.json, packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts
=> style: format with prettier

packages/x-components/src/plugins/__tests__/x-plugin.spec.ts, packages/x-components/src/plugins/x-emitters.ts, packages/x-components/src/plugins/x-plugin.ts
EX-4836
This PR is only to refactor and clean the code. It doesn't change any feature or behaviour.
The motivation is to separate the emitters logic to add more complicated options for the emitters. The idea is to add more options or operators to the emitters in a future task.
All tests and build checks must pass, as nothing change in the features or behaviour.
=> chore(x-plugin): refactor and clean the code  

.github/CONTRIBUTING.md
EX-4890
Add License information to Contributing.md due to legal aspects propsed by Empathy's legal advisor
Be leggally correct
Checking the output file
=> docs(contributing): add license

packages/x-components/src/components/__tests__/auto-progress-bar.spec.ts, packages/x-components/src/views/Layout.vue, packages/x-components/tests/e2e/cucumber/common-steps.spec.ts, packages/x-components/tests/e2e/cucumber/sort.feature, packages/x-components/tests/e2e/cucumber/sort.spec.ts
EX-4953
Just fixes several issues  related with testing that I've found that are breaking our CI in different branches
=> Fix cypress requests

packages/x-components/cypress.json, packages/x-components/src/adapter/mocked-adapter.ts, packages/x-components/src/adapter/real-adapter.ts, packages/x-components/src/adapter/util.ts, packages/x-components/src/components/index.ts, packages/x-components/src/components/layouts/multi-column-max-width-layout.vue, packages/x-components/src/design-system/components/option-list/default.scss, packages/x-components/src/views/Layout.vue, packages/x-components/src/views/base-config.ts, packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue, packages/x-components/src/x-modules/search/components/index.ts, packages/x-components/tests/e2e/cucumber/sort.feature
EX-4964
This PR has some Fixes detected on archetype update.
You can test it using the branch https://github.com/empathyco/x-archetype/tree/feature/EX-4947-add-redirections of the archetype.
=> chore: fixes for archetype

packages/x-components/.eslintrc.js, packages/x-components/package-lock.json, packages/x-components/package.json, packages/x-components/src/plugins/__tests__/x-plugin-emitters.spec.ts, packages/x-components/src/x-modules/tagging/index.ts, packages/x-components/src/x-modules/tagging/service/__tests__/session.service.spec.ts, packages/x-components/src/x-modules/tagging/service/__tests__/utils/mock-storage.service.ts, packages/x-components/src/x-modules/tagging/service/index.ts, packages/x-components/src/x-modules/tagging/service/session.service.ts, packages/x-components/src/x-modules/tagging/service/types.ts
EX-4875
This PR adds a new session id service, which allows us to get and remove the current session id.
In order to see the new property in the `localstorage` you should register the tagging module in the `Layout` and add the `wireServices` in the tagging wiring.
=> feat(tagging): add `SessionService` [EX-4875]

packages/x-components/src/types/origin.ts, packages/x-components/src/utils/__tests__/origin.spec.ts, packages/x-components/src/utils/index.ts, packages/x-components/src/utils/origin.ts, packages/x-components/src/x-modules/identifier-results/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/identifier-results/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/identifier-results/store/actions/save-origin.action.ts, packages/x-components/src/x-modules/identifier-results/store/getters/identifier-results-request.getter.ts, packages/x-components/src/x-modules/identifier-results/store/index.ts, packages/x-components/src/x-modules/identifier-results/store/module.ts, packages/x-components/src/x-modules/identifier-results/store/types.ts, packages/x-components/src/x-modules/identifier-results/wiring.ts
EX-4873
After adding the query origin in the search module, this PR does the same but this time in the identifier results module.
=> feat(identifier-results): add query origin in the identifier results search

packages/x-components/src/design-system/components/list/default.scss, packages/x-components/src/design-system/components/suggestion/default.scss
=> feat(design-system): add new classes for sku inside suggestions

packages/x-components/src/x-modules/search-box/components/__tests__/search-input.spec.ts, packages/x-components/src/x-modules/search-box/components/search-input.vue, packages/x-components/tests/e2e/cucumber/history-queries.feature, packages/x-components/tests/e2e/cucumber/query-suggestions/query-suggestions.feature, packages/x-components/tests/e2e/cucumber/search-box/search-box.feature
This PR focus the search input after the user has clicked the clear input button
[EX-2242](https://searchbroker.atlassian.net/browse/EX-2242)
A new unit test was added and the e2e tests were refactored accordingly to remove a step to focus the search input which is not necessary anymore.
=> feat(searchBox): focus search input after clicking clear search button

packages/x-components/package.json
`package.json` modification in order to run Cypress component tests during the builds.
Launch `test` command and verify all tests are run
=> [EX-5106] Update package.json for Cypress component test

packages/x-components/cypress.json, packages/x-components/src/views/Layout.vue, packages/x-components/src/x-modules/tagging/wiring.ts, packages/x-components/tests/e2e/cucumber/tagging/tagging.feature, packages/x-components/tests/e2e/cucumber/tagging/tagging.spec.ts
EX-5163
This PR adds the `location` parameter injected by the `LocationProvider` component, to the result tagging event (click).
- E2E test
- Manual test
=> feat(tagging): Include 'location' parameter to track result events.

packages/x-components/src/design-system/base/colors.tokens.scss, packages/x-components/src/design-system/base/size.tokens.scss, packages/x-components/src/design-system/components/typography/accent.token.scss, packages/x-components/src/design-system/utilities/background-color.scss, packages/x-components/src/design-system/utilities/border-color.scss, packages/x-components/src/design-system/utilities/border-radius.scss, packages/x-components/src/design-system/utilities/border-width.scss, packages/x-components/src/design-system/utilities/box-shadow.scss, packages/x-components/src/design-system/utilities/box-shadow.tokens.scss, packages/x-components/src/design-system/utilities/font-color.scss, packages/x-components/src/design-system/utilities/margin.scss, packages/x-components/src/design-system/utilities/padding.scss, packages/x-components/src/design-system/variables.scss, packages/x-components/src/views/design-system/design-system-utilities.vue
EX-5171
Add new token colors: Accent, Enable, Disable
Add this new colors to tokens and to Desing System Utilities
These new colors are necessary for BSH setup.
Also refactored a little bit how the utilities classes are generated and the examples in the Design Syste view.
=> feat(desing-system): Add new color tokens.

packages/search-adapter/src/empathy/mappers/response/empathy-next-query.mapper.ts, packages/search-adapter/src/empathy/mappers/response/empathy-related-tag.mapper.ts, packages/search-adapter/src/empathy/models/entities/empathy-next-query.model.ts, packages/search-types/src/query-signals/next-query.model.ts, packages/search-types/src/schemas/next-query.schema.ts
=> feat(next-queries): add curated prop

packages/x-components/src/components/icons/grid-2-rows.vue, packages/x-components/src/components/icons/index.ts, packages/x-components/src/views/design-system/design-system-icon.vue
EX-5238
Add the Grid2RowsIcon to desing system. Necesary for BSH setup
=> feat(desing-system): Add `Grid2RowsIcon` component.

packages/x-components/src/design-system/components/input-group/default.scss, packages/x-components/src/design-system/components/list/default.scss, packages/x-components/src/design-system/components/option-list/bottom.scss, packages/x-components/src/design-system/components/option-list/bottom.tokens.scss, packages/x-components/src/design-system/components/option-list/default.scss, packages/x-components/src/design-system/components/option-list/default.tokens.scss, packages/x-components/src/design-system/components/typography/default.scss, packages/x-components/src/design-system/variables.scss, packages/x-components/src/views/design-system/design-system-utilities.vue
EX-5242
- Add new transparent color to Desing System utilities
- Fix Option List bottom component, to fix alignment with thick border bottom
=> fix(desing-system) Fix Option List Bottom component and add transparent color to Design System.

packages/x-components/src/design-system/components/grid/default.scss, packages/x-components/src/design-system/components/input-group/default.scss, packages/x-components/src/design-system/utilities/flex.scss, packages/x-components/src/design-system/utilities/font-size.scss, packages/x-components/src/design-system/utilities/line-height.scss, packages/x-components/src/design-system/utilities/text-decoration.scss, packages/x-components/src/design-system/utilities/text-transform.scss, packages/x-components/src/views/design-system/design-system-utilities.vue, packages/x-components/src/views/design-system/design-system.vue
- Flex utilities
- Font Size utilities
- Line Height utilities
- Text Decoration utilities
- Text Transform utilities
EX-5241
=> feat(design-system): Add more utility classes.

packages/x-components/src/components/result/index.ts
=> chore(components): Export BaseResultRatingComponent.

packages/x-components/src/design-system/components/tag/default.scss, packages/x-components/src/design-system/components/tag/default.tokens.scss, packages/x-components/src/design-system/components/tag/ghost.scss, packages/x-components/src/design-system/components/tag/ghost.tokens.scss, packages/x-components/src/views/design-system/design-system-tag.vue
Added curated tags tokens.
EX-5089
=> feat(design-system): add curated tags

packages/x-components/src/x-modules/facets/wiring.ts, packages/x-components/src/x-modules/history-queries/wiring.ts, packages/x-components/src/x-modules/identifier-results/wiring.ts, packages/x-components/src/x-modules/next-queries/wiring.ts, packages/x-components/src/x-modules/query-suggestions/wiring.ts, packages/x-components/src/x-modules/search-box/wiring.ts, packages/x-components/src/x-modules/search/wiring.ts, packages/x-components/src/x-modules/url/wiring.ts
=> refactor: change to the top of the wiring the ParamsLoadedFromUrl event

packages/x-components/src/x-modules/tagging/components/tagging.vue, packages/x-components/static-docs/build-search-ui/README.md, packages/x-components/static-docs/build-search-ui/web-archetype-development-guide.md, packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md, packages/x-components/static-docs/build-search-ui/web-use-x-components-guide.md, packages/x-components/static-docs/build-search-ui/web-x-components-integration-guide.md, packages/x-components/static-docs/build-search-ui/x-architecture/README.md
Sanity Checks
Fix bugs that Luisa found on this document https://searchbroker.atlassian.net/wiki/spaces/ED/pages/3639738373/Sanity+check+notes for the first 3 sections:
- Integration links
- Callout Syntaxis
- Breaking Space
Correct links and update callout viz.
=> docs: sanity checks

packages/x-components/src/components/decorators/__tests__/debounce.decorators.spec.ts, packages/x-components/src/components/decorators/debounce.decorators.ts, packages/x-components/src/components/sliding-panel.vue
=> fix(decorators): pending `debounced` execution is cancelled when the component is destroyed 

packages/x-utils/src/__tests__/object.spec.ts, packages/x-utils/src/__tests__/typeguards.spec.ts, packages/x-utils/src/index.ts, packages/x-utils/src/object.ts, packages/x-utils/src/typeguards.ts
=> feat(typeguards): add isFunction

packages/x-utils/src/__tests__/typeguards.spec.ts, packages/x-utils/src/typeguards.ts
=> feat(typeguards): add `isArray`

packages/x-adapter/src/mappers/schema-mapper.factory.ts, packages/x-adapter/src/schemas/__tests__/utils.spec.ts, packages/x-adapter/src/schemas/index.ts, packages/x-adapter/src/schemas/schemas.types.ts, packages/x-adapter/src/schemas/utils.ts
Create a new type MutableSchema and a function makeSchemaMutable that allows to create a new MutableSchema from a Schema. MutableSchemas have two additionally methods that allow us to either replace or override the original schema.
=> feat(schemas): make schemas mutables [EX-5435]

packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts, packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue
=> feat(extra-params): makes excludedExtraParams configurable

packages/search-adapter/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-components/package-lock.json, packages/x-components/package.json
[EX-5995](https://searchbroker.atlassian.net/browse/EX-5995)
=> chore: adjust packages versions

packages/eslint-plugin-x/lib/configs/jest.js, packages/eslint-plugin-x/lib/configs/jsdoc.js
=> fix(eslint): disable some rules

README.md
EX-6048
Fix links and update roadmap
Keep the roadmap up to date to give visibility to external devs
=> docs: Fix links and update roadmap

packages/x-components/static-docs/build-search-ui/README.md, packages/x-components/static-docs/build-search-ui/web-archetype-development-guide.md, packages/x-components/static-docs/build-search-ui/web-archetype-integration-guide.md, packages/x-components/static-docs/build-search-ui/web-how-to-use-x-components-guide.md, packages/x-components/static-docs/build-search-ui/web-x-components-development-guide.md
EX-6125
Correct links, formatting and typos
Have better doc in eDocs.
=> docs: fix links and minor typos

packages/x-components/.eslintrc.js, packages/x-components/src/components/base-dropdown.vue, packages/x-components/src/components/modals/base-modal.vue, packages/x-components/src/views/design-system/design-system-input-group.vue, packages/x-components/src/views/design-system/design-system-input.vue, packages/x-components/src/views/design-system/design-system-picture.vue, packages/x-components/src/views/design-system/design-system-result.vue, packages/x-components/src/views/home/Home.vue, packages/x-components/src/x-modules/facets/components/filters/editable-number-range-filter.vue, packages/x-components/src/x-modules/facets/components/lists/filters-search.vue, packages/x-components/src/x-modules/search-box/components/search-input.vue
All accessibility warnings introduced by the eslint accessibility plugin are fixed now. Therefore, from now on, any piece of code not complying these rules will through an error.
Also literal have been extracted from the code and set as attributes.
You can remove the changes in `.vue` files while keeping the new `.eslintrc.js` file and analyse the errors and how they were solved.
=> feat: fix rest of warnings for accessibility

package-lock.json, packages/search-types/src/request/request.model.ts, packages/x-components/src/x-modules/identifier-results/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/identifier-results/store/getters/identifier-results-request.getter.ts, packages/x-components/src/x-modules/next-queries/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/next-queries/store/getters/request.getter.ts, packages/x-components/src/x-modules/popular-searches/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/popular-searches/store/getters/request.getter.ts, packages/x-components/src/x-modules/query-suggestions/store/__tests__/getter.spec.ts, packages/x-components/src/x-modules/query-suggestions/store/getters/request.getter.ts, packages/x-components/src/x-modules/recommendations/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/recommendations/store/getters/request.getter.ts, packages/x-components/src/x-modules/related-tags/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/related-tags/store/getters/request.getter.ts, packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/search/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/search/store/actions/reset-state.action.ts, packages/x-components/src/x-modules/search/store/getters/request.getter.ts, packages/x-components/tests/e2e/common/common-steps.spec.ts, packages/x-components/tests/e2e/extra-params.feature, packages/x-components/tests/e2e/url.feature
EX-6078
Wrap all the extra params into its an `extraParams` key in `ExtraParamsRequest`.
=> feat: support new `extraParams` request model

packages/x-adapter/src/http-clients/__tests__/utils.spec.ts, packages/x-adapter/src/http-clients/utils.ts, packages/x-utils/src/__tests__/object.spec.ts, packages/x-utils/src/object.ts
EX-6293
feat: Add support for object params in HTTP Clients.
=> feat: Add support for object params in HTTP Clients.

packages/x-adapter/src/utils/__tests__/interpolate.spec.ts, packages/x-adapter/src/utils/interpolate.ts
=> feat: Add suppport to interpolate deep paramteres in the endpoint.

packages/x-adapter/jest.config.js, packages/x-adapter/src/mappers/__tests__/combine-mappers.spec.ts, packages/x-adapter/src/mappers/combine-mappers.ts, packages/x-adapter/src/mappers/index.ts, packages/x-adapter/src/mappers/schema-mapper.factory.ts, packages/x-adapter/src/types/mapper.types.ts
=> feat(mappers): add `combineMappers` util

packages/x-components/src/x-modules/identifier-results/events.types.ts, packages/x-components/src/x-modules/identifier-results/store/actions/fetch-and-save-identifier-results.action.ts, packages/x-components/src/x-modules/identifier-results/store/types.ts, packages/x-components/src/x-modules/next-queries/events.types.ts, packages/x-components/src/x-modules/next-queries/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/next-queries/store/actions/fetch-and-save-next-queries.action.ts, packages/x-components/src/x-modules/next-queries/store/types.ts, packages/x-components/src/x-modules/popular-searches/events.types.ts, packages/x-components/src/x-modules/popular-searches/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/popular-searches/store/actions/fetch-and-save-suggestions.action.ts, packages/x-components/src/x-modules/popular-searches/store/types.ts, packages/x-components/src/x-modules/query-suggestions/events.types.ts, packages/x-components/src/x-modules/query-suggestions/store/__tests__/getter.spec.ts, packages/x-components/src/x-modules/query-suggestions/store/actions/fetch-and-save-suggestions.action.ts, packages/x-components/src/x-modules/query-suggestions/store/types.ts, packages/x-components/src/x-modules/recommendations/events.types.ts, packages/x-components/src/x-modules/recommendations/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/recommendations/store/actions/fetch-and-save-recommendations.action.ts, packages/x-components/src/x-modules/recommendations/store/types.ts, packages/x-components/src/x-modules/related-tags/events.types.ts, packages/x-components/src/x-modules/related-tags/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/related-tags/store/actions/fetch-and-save-related-tags.action.ts, packages/x-components/src/x-modules/related-tags/store/types.ts, packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts, packages/x-components/src/x-modules/search/store/types.ts, packages/x-components/src/x-modules/search/types.ts
=> chore: Revert Request types to old in X Components.

packages/search-types/src/request/next-queries-request.model.ts, packages/search-types/src/request/related-tags-request.model.ts, packages/search-types/src/request/request.model.ts, packages/x-components/src/adapter/mocked-adapter.ts
=> fix: Fix Request types.

packages/x-components/src/__tests__/adapter.dummy.ts, packages/x-components/src/__tests__/utils.ts, packages/x-components/src/adapter/e2e-adapter.ts, packages/x-components/src/plugins/x-plugin.ts, packages/x-components/src/views/base-config.ts, packages/x-components/src/x-installer/x-installer/x-installer.ts, packages/x-components/src/x-modules/extra-params/components/__tests__/snippet-config-extra-params.spec.ts, packages/x-components/src/x-modules/extra-params/components/snippet-config-extra-params.vue, packages/x-components/src/x-modules/identifier-results/events.types.ts, packages/x-components/src/x-modules/identifier-results/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/identifier-results/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/identifier-results/store/actions/fetch-and-save-identifier-results.action.ts, packages/x-components/src/x-modules/identifier-results/store/actions/fetch-identifier-results.action.ts, packages/x-components/src/x-modules/identifier-results/store/getters/identifier-results-request.getter.ts, packages/x-components/src/x-modules/identifier-results/store/types.ts, packages/x-components/tests/e2e/common/mocked-responses.spec.ts
=> feat(identifier-results): use platform adapter

packages/x-components/src/__tests__/utils.ts, packages/x-components/src/x-modules/related-tags/events.types.ts, packages/x-components/src/x-modules/related-tags/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/related-tags/store/__tests__/getters.spec.ts, packages/x-components/src/x-modules/related-tags/store/actions/fetch-and-save-related-tags.action.ts, packages/x-components/src/x-modules/related-tags/store/actions/fetch-related-tags.action.ts, packages/x-components/src/x-modules/related-tags/store/getters/request.getter.ts, packages/x-components/src/x-modules/related-tags/store/types.ts, packages/x-components/tests/e2e/common/mocked-responses.spec.ts
=> feat(related-tags): use the platform adapter

packages/x-components/src/__tests__/utils.ts, packages/x-components/src/x-modules/tagging/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/tagging/store/actions/track.action.ts
=> feature(tagging): use platform adapter

packages/search-types/src/request/request.model.ts, packages/x-adapter-platform/src/types/requests/request.types.ts
=> refactor(search-types): make extra params optional

packages/x-components/README.md
The link on here was not updated and it redirected to a page that didn't exist
=> Fixed broken link on here

.gitignore, package-lock.json, packages/x-adapter-platform/api-extractor.json, packages/x-adapter-platform/package.json
[EX-6384](https://searchbroker.atlassian.net/browse/EX-6384)
=> docs(api-extractor): add API extractor to `x-adapter-platform`

packages/x-components/src/x-modules/identifier-results/components/__tests__/identifier-results.spec.ts, packages/x-components/src/x-modules/identifier-results/components/identifier-results.vue
=> feat: add maxItemsToRender to identifier results

packages/x-components/src/views/home/Home.vue, packages/x-components/src/views/home/aside.vue, packages/x-components/src/views/home/types.ts, packages/x-components/tests/e2e/filters-search/filters-search.spec.ts
EX-6525
Move aside to its own component in Home view, to reduce the size of the Home view.
=> refactor: Move aside to its own component in Home view.

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/plugins/x-plugin.alias.ts, packages/x-components/src/plugins/x-plugin.types.ts
=> feat: add full history queries to alias API

packages/x-components/src/components/layouts/fixed-header-and-asides-layout.vue, packages/x-components/src/components/layouts/single-column-layout.vue, packages/x-components/src/views/layouts/fixed-header-and-asides-layout.vue, packages/x-components/src/views/layouts/single-column-layout.vue
EX-6614 
Adds a new slot to be used as an aside and fully customized by the user. The idea is to be able to put different content on the aside.
=> feat(components): add new slot to `SingleColumnLayout` and `FixedHeaderAndAsidesLayout`

packages/x-components/src/views/home/Home.vue, packages/x-components/tests/e2e/common/common-steps.spec.ts, packages/x-components/tests/e2e/re-open.feature, packages/x-components/tests/e2e/search-box/search-box.spec.ts
=> feat(e2e): check that search modal will open again after close it the first. time

README.md
Update roadmap, core team and contributors.
Make the README file to be up to date.
Update the roadmap and core team, to add Abraham, as they were outdated
=> docs: update roadmap, core team, and contributors

packages/x-components/src/index.ts, packages/x-components/src/store/x.module.ts, packages/x-components/src/wiring/events.types.ts, packages/x-components/src/x-modules/extra-params/x-module.ts, packages/x-components/src/x-modules/queries-preview/events.types.ts, packages/x-components/src/x-modules/queries-preview/index.ts, packages/x-components/src/x-modules/queries-preview/store/emitters.ts, packages/x-components/src/x-modules/queries-preview/store/index.ts, packages/x-components/src/x-modules/queries-preview/store/module.ts, packages/x-components/src/x-modules/queries-preview/store/types.ts, packages/x-components/src/x-modules/queries-preview/wiring.ts, packages/x-components/src/x-modules/queries-preview/x-module.ts, packages/x-components/src/x-modules/x-modules.types.ts
EX-6638
Create an empty results-preview module with all boilerplate code
=> feat: create `queriesPreview` module

packages/x-archetype-utils/.eslintrc.js, packages/x-archetype-utils/LICENSE, packages/x-archetype-utils/README.md, packages/x-archetype-utils/jest.config.js, packages/x-archetype-utils/package.json, packages/x-archetype-utils/src/__tests__/sample.spec.ts, packages/x-archetype-utils/src/index.ts, packages/x-archetype-utils/tsconfig.cjs.json, packages/x-archetype-utils/tsconfig.esm.json, packages/x-archetype-utils/tsconfig.json
=> Create archetype utils package

packages/x-components/src/components/animations/__tests__/disable-animation-mixin.spec.ts, packages/x-components/src/components/animations/disable-animation.mixin.ts, packages/x-components/src/components/animations/fade-and-slide.vue, packages/x-components/src/components/animations/index.ts, packages/x-components/src/components/animations/staggered-fade-and-slide.vue, packages/x-components/src/components/decorators/injection.consts.ts, packages/x-components/src/x-modules/scroll/components/main-scroll.vue
=> feat(components): add disable animation mixin

packages/x-adapter/src/http-clients/__tests__/fetch.http-client.spec.ts, packages/x-adapter/src/http-clients/fetch.http-client.ts, packages/x-utils/src/__tests__/object.spec.ts, packages/x-utils/src/object.ts
=> feat(x-adapter): clean empty params

packages/x-components/tailwind.config.js, packages/x-tailwindcss/src/types.ts
EX-7041
Little things forgotten in the other PR 🙏🏻
=> feat: Improve tailwindcss types.

packages/x-components/src/types/origin.ts, packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview.spec.ts, packages/x-components/src/x-modules/queries-preview/components/query-preview.vue
[EX-7077](https://searchbroker.atlassian.net/browse/EX-7077) 
With this change, the `QueryPreview` feature can be defined by customers in the `snippetConfig` and we will be able to track this new `origin` in the search request. To do so:
- The `queryOrigin` prop has been replaced by the `queryFeature` 
- `queryFeature` now includes `customer` as a type to identify the queryPreviews that can be defined by customers in their `snippetConfig` file)
- The `origin` now is sent to the request by retrieving the `queryFeature` and the injected `location`.
- The `LocationProvider`component will have to be wrapping each part of the application we want its origin to be tracked (to inject the location automatically in each search request).
- `QueryPreview` tests have been updated adding the …
=> Feature: Add origin to Query Preview

packages/x-components/src/components/modals/base-modal.vue
=> fix: scroll restore on `BaseModal`

packages/x-tailwindcss/src/x-tailwind-plugin/plugin.ts
EX-7129
Plugin creation function wasn't very clear without documentation, so one was added.
=> feat: improve documentation in x-tailwind plugin

.github/contributing/commits.md
Update Commits optional scope in contributing guidelines
Have updated modules
=> docs(contributing): update commit optional scope

packages/x-components/src/components/animations/animate-clip-path/animate-clip-path.factory.ts, packages/x-components/src/components/animations/animate-clip-path/animate-clip-path.style.scss, packages/x-components/src/components/animations/animate-scale/animate-scale.factory.ts, packages/x-components/src/components/animations/animate-scale/animate-scale.style.scss, packages/x-components/src/components/animations/animate-translate/animate-translate.factory.ts, packages/x-components/src/components/animations/animate-translate/animate-translate.style.scss, packages/x-components/src/components/animations/create-directional-animation-factory.ts
[EX-7195](https://searchbroker.atlassian.net/browse/EX-7195)
Extending https://github.com/empathyco/x/pull/773 (already merged) in order to support the new directional animation origins on clip-path and scale animations too.
Apart from that, some minor refactors are included in the animation styles trying to improve its readability.
=> Complete animation origins with direction

packages/x-components/src/x-modules/related-tags/components/related-tags.vue, packages/x-components/tests/e2e/common/mocked-responses.spec.ts
[EX-7236](https://searchbroker.atlassian.net/browse/EX-7236)
=> fix(related-tags): Use query instead of tag as key to ensure unique values

packages/x-adapter-platform/src/__tests__/__fixtures__/search.response.ts, packages/x-adapter-platform/src/__tests__/platform.adapter.spec.ts, packages/x-adapter-platform/src/mappers/responses/__tests__/search-response.mapper.spec.ts, packages/x-adapter-platform/src/schemas/facets/__tests__/utils.spec.ts, packages/x-adapter-platform/src/schemas/facets/types.ts, packages/x-adapter-platform/src/schemas/facets/utils.ts, packages/x-adapter-platform/src/schemas/models/facet.schema.ts, packages/x-adapter-platform/src/types/models/facet.model.ts
[EX-6373](https://searchbroker.atlassian.net/browse/EX-6373)
=> Add facets type field on Platform adapter

packages/x-components/src/design-system/components/picture/zoom.scss, packages/x-components/src/design-system/components/picture/zoom.tokens.scss, packages/x-components/src/views/home/result.vue
EX-6315
Adds a variant of the picture css component that zooms on hover.
=> feat(design-system): add zoom effect

packages/search-types/src/banner.model.ts, packages/search-types/src/promoted.model.ts, packages/search-types/src/schemas/banner.schema.ts, packages/search-types/src/schemas/promoted.schema.ts, packages/x-adapter-platform/src/schemas/models/banner.schema.ts, packages/x-adapter-platform/src/schemas/models/promoted.schema.ts, packages/x-adapter-platform/src/types/models/banner.model.ts, packages/x-adapter-platform/src/types/models/promoted.model.ts, packages/x-components/src/__stubs__/banners-stubs.factory.ts, packages/x-components/src/__stubs__/promoteds-stubs.factory.ts, packages/x-components/src/x-modules/search/components/__tests__/banner.spec.ts, packages/x-components/src/x-modules/search/components/__tests__/promoted.spec.ts, packages/x-components/src/x-modules/search/components/banner.vue, packages/x-components/src/x-modules/search/components/promoted.vue
[EX-7293](https://searchbroker.atlassian.net/browse/EX-7293), [EX-7294](https://searchbroker.atlassian.net/browse/EX-7294) (both subtasks added in together as they are dependent).
=> feat: Add position on Banner and Promoted models

packages/x-components/src/x-modules/empathize/components/empathize.vue
I write the prop default value properly and  rename event to be a typed XEvent . 
- [Fixes ](https://github.com/empathyco/x/issues/751)
=> Rename event to be a typed XEvent

packages/x-components/jest.setup.ts, packages/x-components/package.json, packages/x-components/src/components/base-grid.vue, packages/x-components/src/wiring/events.types.ts, packages/x-components/tests/unit/base-grid.spec.ts
[EX-7291](https://searchbroker.atlassian.net/browse/EX-7291)
=> feat: Emit ColumnsNumberRendered event on BaseGrid

packages/x-components/tsconfig.json
=> fix: remove `resize-observer-browser` types from tsconfig

packages/x-tailwindcss/demo/src/components/icons/check-alt.vue, packages/x-tailwindcss/demo/src/components/icons/check-fill.vue, packages/x-tailwindcss/demo/src/components/icons/check.vue, packages/x-tailwindcss/demo/src/components/icons/curated-fill.vue, packages/x-tailwindcss/demo/src/components/icons/curated.vue, packages/x-tailwindcss/demo/src/components/icons/option.vue, packages/x-tailwindcss/demo/src/components/xds-base-showcase.vue, packages/x-tailwindcss/demo/src/components/xds-button.vue, packages/x-tailwindcss/demo/src/components/xds-icon.vue, packages/x-tailwindcss/demo/src/components/xds-showcase.vue, packages/x-tailwindcss/demo/src/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/background-colors.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/colors.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/sharp.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/icon/stroke-widths.ts, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts
EX-7113
This PR:
- Add the Design System Icon component
- Add icons to the DS Button Showcase
- Made some changes in the DS Theme: `letterSpacing`, `fontFamily` & `strokeWidth`
=> feat(desing-system): Add icon component to Design System.

packages/x-bus/.eslintrc.js, packages/x-bus/README.md, packages/x-bus/jest.config.js, packages/x-bus/package.json, packages/x-bus/src/__tests__/x-bus.spec.ts, packages/x-bus/src/index.ts, packages/x-bus/tsconfig.cjs.json, packages/x-bus/tsconfig.esm.json, packages/x-bus/tsconfig.json
=> chore: create empty `x-bus` package

.npmrc
[EX-7036](https://searchbroker.atlassian.net/browse/EX-7036)
=> feat: Add npmrc file with engine-strict

packages/x-adapter-platform/src/schemas/models/filters/__tests__/number-filter.spec.ts, packages/x-adapter-platform/src/schemas/models/filters/number-filter.schema.ts
=> fix: number filter schema to map the right values

packages/x-priority-queue/.eslintrc.js, packages/x-priority-queue/README.md, packages/x-priority-queue/jest.config.js, packages/x-priority-queue/package.json, packages/x-priority-queue/src/__tests__/x-priority-queue.spec.ts, packages/x-priority-queue/src/index.ts, packages/x-priority-queue/tsconfig.cjs.json, packages/x-priority-queue/tsconfig.esm.json, packages/x-priority-queue/tsconfig.json
=> chore: create `x-priority-queue` package

packages/x-components/CHANGELOG.md
Adding missing breaking change on last X Components version
=> chore: add breaking change to the CHANGELOG

packages/x-tailwindcss/demo/src/components/xds-button.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/disabled.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/link.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/outlined.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/tight.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/utils/background-on-hover.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/utils/no-background.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/button/utils/no-horizontal-padding.ts, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts, packages/x-tailwindcss/src/x-tailwind-plugin/utils/map-colors.ts
EX-7508
Finally the `Subtle` variant will be named `Tight`
=> feat(design-system): Add `Subtle` and `Link` variants to the `Button` XDS component.

packages/x-tailwindcss/demo/src/components/xds-base-showcase.vue, packages/x-tailwindcss/demo/src/components/xds-suggestion.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/ghost.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/outlined.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/utils/common-ghost-and-tag-styles.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/utils/padding-by-size.ts
=> feat(desing-system): Add `ghost` variant for `suggestion` in X Design System

README.md
Update Roadmap and customer examples
Change the Roadmap section to adapt to the current status of the project and anticipate some features.
Change the customers because to be up to date with new customers.
Transparency
=> docs: update roadmap and customer examples

packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/plugins/x-plugin.alias.ts, packages/x-components/src/plugins/x-plugin.types.ts
=> refactor(plugin): Rename `inputStatus` to `searchBoxStatus` in Alias API

packages/x-components/CHANGELOG.md
Adds a missing breaking change
=> chore: add missing breaking change for `Highlight` component

packages/x-svg-converter/src/__tests__/svg-to-vue.spec.ts
=> fix(svg-converter): change sourcePath method resolve

packages/x-components/src/x-modules/recommendations/store/emitters.ts
[MOTPRD-9525](https://searchbroker.atlassian.net/browse/MOTPRD-9525)
In Motive, we would like to have the existing `RecommendationChanged`event fired. So we could be aware when recommendations have been changed. This need emerge in the context described in https://github.com/empathyco/x/pull/891, we are modifying the prices coming from the search based on the shopper. That approach is also being applied to recommendations.
=> feat(recommendations): emit RecommendationsChanged

packages/x-tailwindcss/demo/src/components/xds-typography.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/text1/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title1/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title1/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title2/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title2/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title3/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title3/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title4/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title4/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/typography/title4/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts
=> feat(design-system): modify typography component

.github/workflows/edocs-preview.yaml, packages/x-components/static-docs/build-search-ui/web-x-components-development-guide.md
=> docs: Using new docs video reference component

packages/x-components/src/x-modules/extra-params/components/extra-params.vue, packages/x-components/src/x-modules/next-queries/components/__tests__/next-query-preview.spec.ts, packages/x-components/src/x-modules/next-queries/components/next-query-preview.vue, packages/x-components/src/x-modules/next-queries/events.types.ts, packages/x-components/src/x-modules/next-queries/wiring.ts, packages/x-components/src/x-modules/queries-preview/events.types.ts, packages/x-components/src/x-modules/queries-preview/wiring.ts
EX-7580
This renames the agreed events to match the new shape.
=> feat: Rename lifecycle hook events

packages/x-tailwindcss/demo/src/components/xds-input.vue, packages/x-tailwindcss/demo/src/components/xds-showcase.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/colors.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/line.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/sizes.ts
EX-7494
[Designs](https://www.figma.com/file/9a1DMgqIHt5ZZBvS2waaOs/X-DS?node-id=2391%3A30127&t=Tta6YAV5SbCWakqB-0)
=> feat(desing-system): add input component to XDS

packages/x-components/src/x-modules/url/components/url-handler.vue
Fixes a typo in the `UrlHandler` docs.
No tests have been performed since it's a trivial change.
=> fix: Fix typo in UrlHandler docs

packages/x-adapter/LICENSE, packages/x-adapter/README.md
[EX-6046](https://searchbroker.atlassian.net/browse/EX-6046).
=> Create Readme for x-adapter

packages/x-tailwindcss/src/x-tailwind-plugin/components/button/link.ts
=> fix(components): set the correct value to `x-button-link` `display` property

packages/x-tailwindcss/src/x-tailwind-plugin/components/suggestion/default.ts
=> feat(design-system): Add justify start to suggestion

packages/x-archetype-utils/src/home/home-template.html
EX-7809
* Remove an extra `>`
* Replace the search icon for the one used in the archetype
* Fix the button and it's background color
=> fix: remove extra '>', fix search button

package-lock.json, packages/x-priority-queue/src/__tests__/x-priority-queue.spec.ts, packages/x-priority-queue/src/index.ts, packages/x-priority-queue/src/x-priority-queue.ts, packages/x-priority-queue/src/x-priority-queue.types.ts
=> feat: improve types

packages/x-components/src/components/__tests__/base-variable-column-grid.spec.ts, packages/x-components/src/components/base-grid.vue, packages/x-components/src/design-system/components/grid/default.scss, packages/x-components/src/views/layouts/fixed-header-and-asides-layout.vue, packages/x-components/src/views/layouts/multi-column-layout.vue, packages/x-components/src/views/layouts/single-column-layout.vue, packages/x-components/tests/unit/base-grid.spec.ts
BREAKING CHANGE: Rename `x-grid` class to `x-grid-list`.
EX-7481
=> feat(components): rename `x-grid` class to `x-grid-list`

packages/x-priority-queue/src/__tests__/x-priority-queue.spec.ts, packages/x-priority-queue/src/x-priority-queue.ts, packages/x-priority-queue/src/x-priority-queue.types.ts
=> feat: improve generics types

packages/x-components/src/x-modules/history-queries/components/__tests__/history-query.spec.ts, packages/x-components/src/x-modules/history-queries/components/history-query.vue
=> feat(history-queries): add dynamic classes to the history query suggestion

packages/x-components/src/components/modals/__tests__/base-events-modal.spec.ts, packages/x-components/src/components/modals/__tests__/base-id-modal.spec.ts, packages/x-components/src/components/modals/__tests__/base-modal.spec.ts, packages/x-components/src/components/modals/__tests__/main-modal.spec.ts, packages/x-components/src/components/modals/base-events-modal.vue, packages/x-components/src/components/modals/base-id-modal.vue, packages/x-components/src/components/modals/base-modal.vue, packages/x-components/src/components/modals/main-modal.vue
=> feat(components): add content class to modals

package.json, packages/deep-merge/package.json, packages/eslint-plugin-x/package.json, packages/jest-utils/package.json, packages/logger/package.json, packages/react-wrapper/package.json, packages/storage-service/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-archetype-utils/package.json, packages/x-bus/package.json, packages/x-components/package.json, packages/x-priority-queue/package.json, packages/x-svg-converter/package.json, packages/x-tailwindcss/package.json, packages/x-translations/package.json, packages/x-types/package.json, packages/x-utils/package.json
Please relax the engine version constraints which only allows node 16 to support higher versions, like node 18 (lts/hydrogen) that we are starting to use in Motive.
=> chore(runtime): allow next node versions

packages/x-components/static-docs/build-search-ui/web-x-components-development-guide.md
We have change the ids of the videos on eDocs (as we changed the hosting), and we have to correct this to make it work again. 
Using preview
=> fix(docs): correcting video-reference id

.github/actions/release-alpha/action.yml, .github/workflows/publish-release.yml
=> fix(ci): release action to use npm

README.md
Readme update
Set clear information about monorepo tools and installation
=> docs: update installation info, roadmap, and core members

packages/x-tailwindcss/demo/src/components/xds-layout-fixed-header.vue, packages/x-tailwindcss/demo/src/components/xds-layout-single-column.vue, packages/x-tailwindcss/demo/src/components/xds-layout-two-columns.vue, packages/x-tailwindcss/demo/src/components/xds-showcase.vue
=> feat(design-system): add single column and fixed header layouts showcases

packages/x-svg-converter/package.json
=> chore: make the svg-converter package public

packages/x-components/Jenkinsfile
Remove leftover code from when this project was private and used Jenkins as CI.
Code cleanup.
=> Delete unused Jenkinsfile

packages/x-components/src/components/sliding-panel.vue, packages/x-tailwindcss/demo/src/components/xds-scroll.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components/layout/container.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/layout/item.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/layout/utils.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/default.ts
=> feat(desing-system): Add layout `stack` util.

packages/x-archetype-utils/src/home/home-template.html
=> fix: Update home styles to match `inputGroup`.

packages/x-components/package.json, pnpm-lock.yaml
=> chore(deps-dev): bump  from 2.1.5 to 2.2.0

packages/x-tailwindcss/src/x-tailwind-plugin/components/scroll/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts
=> fix(design-system): Fix X Design System `Scroll` component appearing in mobile.

packages/x-tailwindcss/src/x-tailwind-plugin/components/scroll/default.ts
=> fix(design-system): Fix scroll in the Design System.

packages/x-tailwindcss/src/x-tailwind-plugin/components/sliding-panel/fade/sizes.ts
=> fix(design-system): fix wrong sliding panel spacing value

packages/x-tailwindcss/src/x-tailwind-plugin/components/input-group/sizes.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/input/sizes.ts
=> fix(design-system): modify font-size by default in input and input-group

packages/x-components/static-docs/experience-search-and-discovery/related-tags.md
Explanation on how to create curated RTs using the Playboard is already released. We need to update X Components related info to talk about RT curation and config options supported by the related X Components.
Now, RTs related functional doc includes info on the option of distinguish cirated RTs in the commerce store so that shoppers can identify whether a RT has been willfully created or just organically generated by other shoppers behavior.
Doc has been tested locally to check all layout components work and display correctly and links to other services/sections in public doc work well.
=> docs(related-tags): added curation options

packages/x-components/src/components/animations/fade.vue
Live example was not rendered due to a typo
=> fix(edocs-live-examples): Live example was not rendered

packages/eslint-plugin-x/prettier-config.js
=> fix(build): Fix issue with prettier-plugin-tailwindcss.

packages/x-tailwindcss/src/x-tailwind-plugin/components/tag/default.ts
=> feat(desing-system): add padding top and bottom 0 to tag

packages/eslint-plugin-x/package.json, packages/x-components/package.json, packages/x-components/src/components/items-list.vue, packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/plugins/x-plugin.alias.ts, packages/x-components/src/plugins/x-plugin.types.ts, packages/x-components/src/tailwind/plugin-options.js, packages/x-components/src/tailwind/plugin-options.ts, packages/x-components/tailwind.config.ts, packages/x-components/tsconfig.eslint.json, packages/x-tailwindcss/package.json, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts, pnpm-lock.yaml
Add `itemClass` prop to `ItemsList`.
Add `isHistoryQueriesEnabled` to `AliasApi`.
Add default border width to XDS theme.
Update Tailwind version to 3.3.0
EX-8130
=> feat: Minor improvements.

packages/x-components/package.json, packages/x-components/src/composables/create-use-device.composable.ts, packages/x-components/src/composables/index.ts, packages/x-components/src/composables/use-$x.ts, packages/x-components/src/index.ts, packages/x-components/src/utils/string.ts, packages/x-components/tests/unit/useDevice.spec.ts, pnpm-lock.yaml
=> feat:(composables): Add `createUseDevice` composable factory.

packages/x-tailwindcss/demo/src/components/xds-facet-filter.vue, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/ghost.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/index.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/simple.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/underline.ts, packages/x-tailwindcss/src/x-tailwind-plugin/theme.ts
=> feat(design-system): add simple filter variant

packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/default.ts, packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/ghost.ts
=> fix: styles for default and ghost variant

packages/x-components/src/x-modules/facets/components/filters/__tests__/hierarchical-filter.spec.ts, packages/x-components/src/x-modules/facets/components/filters/hierarchical-filter.vue
EMP-120
Adds a new dynamic prop to be able to style the filter element itself.
=> feat: add `filterItemClass` prop to `HierarchicalFilter`

packages/x-components/src/main.ts, packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/plugins/x-plugin.alias.ts, packages/x-components/src/plugins/x-plugin.types.ts, packages/x-components/src/views/home/Home.vue, packages/x-components/src/views/home/result.vue, packages/x-components/src/x-modules/search/components/__tests__/fallback-disclaimer.spec.ts, packages/x-components/src/x-modules/search/components/fallback-disclaimer.vue, packages/x-components/src/x-modules/search/components/index.ts, packages/x-components/src/x-modules/search/events.types.ts, packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/search/store/actions/reset-request-on-refinement.action.ts, packages/x-components/src/x-modules/search/store/actions/save-search-response.action.ts, packages/x-components/src/x-modules/search/store/emitters.ts, packages/x-components/src/x-modules/search/store/module.ts, packages/x-components/src/x-modules/search/store/types.ts, packages/x-components/src/x-modules/search/wiring.ts, packages/x-components/tests/e2e/common/mocked-responses.spec.ts, packages/x-components/tests/e2e/fallback-disclaimer.feature, packages/x-components/tests/e2e/fallback-disclaimer/fallback-disclaimer.spec.ts, packages/x-components/tests/e2e/history-queries.feature, packages/x-components/tests/e2e/search-box.feature
Some e2e tests are failing, I disabled some of them because I think that its the problem that causes the CI stops abruptly and doesn't show the error in the log.
EX-8080
=> feat(search): add fallback disclaimer component

packages/x-components/src/x-modules/facets/components/lists/__tests__/sliced-filters.spec.ts, packages/x-components/src/x-modules/facets/components/lists/sliced-filters.vue, packages/x-components/src/x-modules/history-queries/components/__tests__/my-history.spec.ts, packages/x-components/src/x-modules/history-queries/components/my-history.vue
=> feat(sliced-filters): add dynamic prop to show more/less buttons

packages/x-components/src/x-modules/facets/entities/index.ts
EMP-460
The sticky filter modifier wasn't exported.
=> feat: export sticky modifier

packages/x-components/src/components/modals/__tests__/base-modal.spec.ts, packages/x-components/src/components/modals/base-modal.vue, packages/x-components/src/design-system-deprecated/components/modal/default.scss, packages/x-components/src/design-system-deprecated/components/modal/default.tokens.scss
=> feat(components): add overlayClass prop to BaseModal component

packages/x-components/static-docs/build-search-ui/web-archetype-development-guide.md, packages/x-components/static-docs/build-search-ui/web-how-to-use-x-components-guide.md, packages/x-components/static-docs/build-search-ui/web-x-components-development-guide.md, packages/x-components/static-docs/experience-search-and-discovery/README.md, packages/x-components/static-docs/experience-search-and-discovery/empathize.md, packages/x-components/static-docs/experience-search-and-discovery/facets-and-filters.md, packages/x-components/static-docs/experience-search-and-discovery/history-queries.md, packages/x-components/static-docs/experience-search-and-discovery/id-results.md, packages/x-components/static-docs/experience-search-and-discovery/my-history.md, packages/x-components/static-docs/experience-search-and-discovery/next-queries.md, packages/x-components/static-docs/experience-search-and-discovery/popular-searches.md, packages/x-components/static-docs/experience-search-and-discovery/product-results-ui.md, packages/x-components/static-docs/experience-search-and-discovery/query-suggestions.md, packages/x-components/static-docs/experience-search-and-discovery/recommendations.md, packages/x-components/static-docs/experience-search-and-discovery/related-tags.md, packages/x-components/static-docs/experience-search-and-discovery/search-box.md, packages/x-components/static-docs/experience-search-and-discovery/serp-ui.md, packages/x-components/static-docs/experience-search-and-discovery/web-local-storage.md
Adding `meta_title` tag in docs to define titles for SEO & Holon search purposes, where applicable. Also adjusted page and sidebar titles.
Need to adjust and adapt doc titles for a better performance of holon search. Taking advantage of this also to improve SEO performance.
=> docs(titles): adjusting page, seo, and sidebar titles

packages/x-components/src/x-modules/search/components/__tests__/banner.spec.ts, packages/x-components/src/x-modules/search/components/__tests__/promoted.spec.ts, packages/x-components/src/x-modules/search/components/banner.vue, packages/x-components/src/x-modules/search/components/promoted.vue
EMP-596
We needed more precision when modifying the styles of the banner and the promoteds.
New unit tests for each component
=> feat: add dynamic props for title to promoteds and banner

.github/workflows/build.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml, .github/workflows/release-alpha.yml, package.json, packages/deep-merge/package.json, packages/eslint-plugin-x/package.json, packages/jest-utils/package.json, packages/logger/package.json, packages/react-wrapper/package.json, packages/storage-service/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-archetype-utils/package.json, packages/x-bus/package.json, packages/x-components/package.json, packages/x-priority-queue/package.json, packages/x-svg-converter/package.json, packages/x-tailwindcss/package.json, packages/x-translations/package.json, packages/x-types/package.json, packages/x-utils/package.json, pnpm-lock.yaml
=> chore(deps): update node to v18

.github/workflows/build.yml
=> ci: modify release job

.github/actions/release-alpha/action.yml, .github/workflows/build.yml
=> ci: fix release

.github/actions/release-alpha/action.yml
=> ci: fix npm auth config

.github/actions/release-alpha/action.yml, .github/workflows/build.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml, .github/workflows/release-alpha.yml, package.json, packages/deep-merge/package.json, packages/eslint-plugin-x/package.json, packages/jest-utils/package.json, packages/logger/package.json, packages/react-wrapper/package.json, packages/storage-service/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-archetype-utils/package.json, packages/x-bus/package.json, packages/x-components/package.json, packages/x-priority-queue/package.json, packages/x-svg-converter/package.json, packages/x-tailwindcss/package.json, packages/x-translations/package.json, packages/x-types/package.json, packages/x-utils/package.json, pnpm-lock.yaml
=> chore(deps): revert update node to v18

.github/workflows/build.yml
=> ci: set node 16 release container

.github/workflows/publish-release.yml
This PR updates the npm token in our configuration due to an issue encountered when uploading packages to npm.
We were facing problems uploading a package to npm after upgrading Node.js from version 16 to version 18. It is suspected that the issue could be related to changes in the npm token structure. This PR aims to address and resolve this issue.
=> Update Token NPM env var

.github/actions/release-alpha/action.yml, .github/workflows/build.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml, .github/workflows/release-alpha.yml, package.json, packages/deep-merge/package.json, packages/eslint-plugin-x/package.json, packages/jest-utils/package.json, packages/logger/package.json, packages/react-wrapper/package.json, packages/storage-service/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-archetype-utils/package.json, packages/x-bus/package.json, packages/x-components/package.json, packages/x-priority-queue/package.json, packages/x-svg-converter/package.json, packages/x-tailwindcss/package.json, packages/x-translations/package.json, packages/x-types/package.json, packages/x-utils/package.json, pnpm-lock.yaml
BREAKING CHANGE: minimum node version required is 18.
=> chore(deps): update node to 18

packages/x-adapter-platform/src/__tests__/platform.adapter.spec.ts, packages/x-adapter-platform/src/endpoint-adapters/semantic-queries.endpoint-adapter.ts, packages/x-components/src/views/adapter.ts
The purpose is to have the correct URL for the semantic endpoint.
This is the correct semantics final URL: https://api.staging.empathy.co/semantics-api/search_single/oysho?lang=en&q=dress
=> fix(platform-adapter): change semantics url path

packages/x-components/src/x-modules/search/components/redirection.vue
The error in the console is not showing anymore, now when you click on a related tags while redirecting it cancels the redirection.
Manually tested recreating the steps to show the error as described in the issue. That error is not happening anymore
=> fix(search): Redirection didn't cancel when a related tag was clicked

.github/actions/install/action.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml, .github/workflows/release-alpha.yml
https://github.com/pnpm/pnpm/pull/7013 Solved on release 8.7.1
As  the bug in pnpm is resolved, we are setting the major version that takes the latest version available
=> fix: change pnpm version due to bug resolution

packages/x-components/src/x-modules/experience-controls/components/__tests__/experience-controls.spec.ts
EMP-2183
Testing for the new experience controls component
New tests created for this feature.
=> feat(experience-controls): tests for the experience-controls component

packages/x-components/src/x-modules/experience-controls/events.types.ts, packages/x-components/src/x-modules/experience-controls/store/actions/fetch-and-save-controls.action.ts, packages/x-components/src/x-modules/experience-controls/store/actions/fetch-and-save-experience-controls.action.ts, packages/x-components/src/x-modules/experience-controls/store/actions/fetch-controls.action.ts, packages/x-components/src/x-modules/experience-controls/store/actions/fetch-experience-controls.action.ts, packages/x-components/src/x-modules/experience-controls/store/emitters.ts, packages/x-components/src/x-modules/experience-controls/store/getters/experience-controls-results-request.getter.ts, packages/x-components/src/x-modules/experience-controls/store/module.ts, packages/x-components/src/x-modules/experience-controls/store/types.ts, packages/x-components/src/x-modules/experience-controls/wiring.ts
Update the module for the adapter that has been created
N/A
=> feat(xcontrol): update the xperience-controls

packages/x-components/src/store/utils/config-store.utils.ts
EMP-2327
We will now need to change the configs in the module programatically. This utils can be used by any module to do so.
Import this utils to a module that has config in the state, similarly to what we are doing with the status.
=> feat: utils for the mutation of states with config

packages/x-adapter-platform/src/__tests__/__fixtures__/experience-controls.response.ts, packages/x-adapter-platform/src/mappers/requests/__tests__/experience-controls-request.mapper.spec.ts, packages/x-adapter-platform/src/mappers/responses/__tests__/experience-controls-response.mapper.spec.ts
[EMP-2235](https://searchbroker.atlassian.net/browse/EMP-2235)
[EMP-2235]: https://searchbroker.atlassian.net/browse/EMP-2235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> X Controls adapter tests

packages/x-components/src/design-system-deprecated/design-system.md
There was this file called design-system.md that described the old design system, so it needs to be moved to the design-system-deprecated folder.
=> refactor: move file design-system.md to design-system-deprecated folder

packages/x-components/src/components/column-picker/base-column-picker-list.vue
=> fix(docs): typo in vue file docs import

packages/x-components/package.json, pnpm-lock.yaml
Update `@vueuse/core` to latest version to fix a [circular dependency warning](https://github.com/vueuse/vueuse/pull/3683)
=> feat: update `@vueuse/core` to 10.7.1

README.md
=> docs: update readme roadmap

packages/x-components/src/x-modules/tagging/store/__tests__/actions.spec.ts, packages/x-utils/package.json, packages/x-utils/src/services/__tests__/session.service.spec.ts, packages/x-utils/src/services/session.service.ts, pnpm-lock.yaml
[EMP-3416](https://searchbroker.atlassian.net/browse/EMP-3416)
Check is we get rid of NanoId package to use Browser Crypto UUID.
We use nanoid package only to generate the sessionId, so there is no problem with removing that dependency and using UUID. Nanoid is indeed 2 times faster than UUID, but we don't use it too much, so I think it will not cause performance issues.
[EMP-3099]: https://searchbroker.atlassian.net/browse/EMP-3099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-3099]: https://searchbroker.atlassian.net/browse/EMP-3099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-3416]: …
=> refactor: change sessionId creation logic from nanoId to UUID

packages/x-archetype-utils/src/home/home-template.html
Using x-archetype with an iOS device, when a user clicks the home page search box to open X there is an unexpected zoom. In order to fix this we should change de font size of that input to 16px
[EMP-3496]: https://searchbroker.atlassian.net/browse/EMP-3496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: set home search input font size to 16px

packages/x-components/src/components/animations/animate-width.vue
In order to do the migration to Vue3 we need to migrate components to use a proper sintax. In this case I have migrated the animate-width component.
It has been tested creating this test view to use the animate-width animation:
```
<template>
<div>
<button @click="visible = !visible">Toggle</button>
<AnimateWidth>
<div v-if="visible" style="width: 300px">Element to animate</div>
</AnimateWidth>
</div>
</template>
<script>
import AnimateWidth from '../../components/animations/animate-width.vue';
export default {
components: {
AnimateWidth
},
data() {
return {
visible: true
};
}
};
</script>
```
[EMP-3383]: https://searchbroker.atlassian.net/browse/EMP-3383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> feat: migrating animate-width component

packages/x-components/src/components/panels/base-tabs-panel.vue, packages/x-components/src/x-modules/facets/components/filters/renderless-filter.vue, packages/x-components/src/x-modules/history-queries/components/history-queries-switch.vue, packages/x-components/src/x-modules/next-queries/components/next-queries-list.vue, packages/x-components/src/x-modules/tagging/components/tagging.vue
Following TW best practices, terms such as “disabled” should be avoided in content. So, any reference to enable/disable should be removed and replaced with the appropriate form of “activate/deactivate” in the UI reference. 
[EMP-3539]: https://searchbroker.atlassian.net/browse/EMP-3539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: replace enable/disable with activate/deactivate

.github/workflows/edocs-dynamic-sync.yml
EPDocs have been moved to a new repository: `docs-framework`. So this action should be called from that repository from now on.
=> fix: updating edocs-dynamic-sync.yml to use the new eDocs repository

packages/x-components/src/components/index.ts
In order to use the pageLoaderButton component in client setups we need to export it.
=> feat: export pageLoaderButton component

packages/x-components/src/views/home/Home.vue, packages/x-components/src/x-modules/queries-preview/components/__tests__/query-preview-list.spec.ts, packages/x-components/src/x-modules/queries-preview/components/query-preview-list.vue, packages/x-components/tests/e2e/common/common-steps.spec.ts
The origin of this change is to allow a QueryPreviewList consumer to specify some attributes related to the list itself, not the items.
The specific case, at Backroom, we want to "tag" the query preview list, to watch all the results there. 
HTML generated
As you can see, the tag is inserted on every child instead of the ul itself.
The solution was to proivde each QueryPreview item with their known properties, and let the others be inherited to the root component.
TIP: inheritAttrs: false is dangerous, we are losing the control from the things a consumer can be inserting on the component. In fact, we were always inserting a useless `animation` prop on every QueryPreview due to …
=> fix(query-preview-list): enable inherit attrs

packages/x-adapter-platform/src/__tests__/platform.adapter.spec.ts, packages/x-adapter-platform/src/endpoint-adapters/experience-controls.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/identifier-results.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/next-queries.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/popular-searches.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/query-suggestions.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/recommendations.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/related-tags.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/search.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/semantic-queries.endpoint-adapter.ts, packages/x-adapter-platform/src/endpoint-adapters/utils.ts
Platform Test is a useful environment for development purposes so it would be nice to support it here so other projects (Backroom) can make use of it.
=> feat: Support Platform Test environment

packages/x-components/src/components/base-dropdown.vue, packages/x-components/src/components/modals/base-modal.vue, packages/x-components/src/components/scroll/base-scroll.vue
Issue performed while updating `x` dependencies in motive-x
- `Main`
In `motive-x`
- My code follows the **[style guidelines](./CONTRIBUTING.md#style-guides)** of this project.
- I have performed a **self-review** on my own code.
- I have **commented** my code, particularly in hard-to-understand areas.
- I have made corresponding changes to the **[documentation](./CONTRIBUTING.md#documentation-style-guide)**.
- My changes generate **no new warnings**.
- I have added **tests** that prove my fix is effective or that my feature works.
- New and existing **unit tests pass locally** with my changes.
=> fix(animation): fix Expected Object, got Function on animations props

packages/_vue3-migration-test/src/components/index.ts, packages/_vue3-migration-test/src/components/test-base-keyboard-navigation.vue, packages/_vue3-migration-test/src/router.ts, packages/x-components/src/components/__tests__/base-keyboard-navigation.spec.ts, packages/x-components/src/components/base-keyboard-navigation.vue
Migrate the `base-keyboard-nav` component to composition API.
[EMP-4158]: https://searchbroker.atlassian.net/browse/EMP-4158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(keyboard-navigation): migrate keyboard-navigation to composition API

packages/_vue3-migration-test/src/components/index.ts, packages/_vue3-migration-test/src/components/modals/test-base-id-modal.vue, packages/_vue3-migration-test/src/router.ts, packages/x-components/src/components/layouts/fixed-header-and-asides-layout.vue, packages/x-components/src/components/modals/base-id-modal.vue
Migrate `BaseIdModal` component to the composition API
[EMP-4194]: https://searchbroker.atlassian.net/browse/EMP-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(base-id-modal): migrate to composition API

packages/_vue3-migration-test/src/router.ts, packages/_vue3-migration-test/src/x-modules/search/components/index.ts, packages/_vue3-migration-test/src/x-modules/search/components/test-partial-results-list.vue, packages/_vue3-migration-test/src/x-modules/search/x-module.ts, packages/x-components/src/x-modules/search/components/partial-query-button.vue, packages/x-components/src/x-modules/search/components/partial-results-list.vue
Migrate `PartialQueryButton` and `PartialResultsList`
[EMP-4198]: https://searchbroker.atlassian.net/browse/EMP-4198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate PartialQueryButton and PartialResultsList

.github/workflows/build.yml, .github/workflows/edocs-dynamic-sync.yml, .github/workflows/publish-release.yml, .github/workflows/release-alpha.yml
There was a security breach on https://oi.empathy.co/ which exposed one of our GitHub tokens with access to the organisations private repositories. The token is `SUPPORT_TOKEN`, so now we have to remove this token from our workflows and replace it with `create-github-app-token` action that generates tokens under demand.
Documentation: https://developer.empathy.co/ci-cd/github-actions.html#interact-with-github-private-resources-from-a-github-workflow
Example: https://github.com/empathyco/platform-motive-helm-charts/blob/a44f5bf359ca59c8fbe5bdafc678bde4959a4491/.github/workflows/version-updater.yaml#L43-L61
=> feat: remove SUPPORT_TOKEN and use create-github-app-token

packages/_vue3-migration-test/src/main.ts, packages/_vue3-migration-test/src/router.ts, packages/_vue3-migration-test/src/x-modules/index.ts, packages/_vue3-migration-test/src/x-modules/recommendations/index.ts, packages/_vue3-migration-test/src/x-modules/recommendations/test-recommendations.vue, packages/_vue3-migration-test/src/x-modules/recommendations/x-module.ts, packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/x-modules/recommendations/components/recommendations.vue, packages/x-components/src/x-modules/recommendations/x-module.ts
Migrate `Recommendations` component to compositon API.
[EMP-4306]: https://searchbroker.atlassian.net/browse/EMP-4306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(recommendations): migrate recommendations component to composition api

packages/_vue3-migration-test/src/main.ts, packages/_vue3-migration-test/src/router.ts, packages/_vue3-migration-test/src/x-modules/index.ts, packages/_vue3-migration-test/src/x-modules/popular-searches/index.ts, packages/_vue3-migration-test/src/x-modules/popular-searches/test-popular-searches.vue, packages/_vue3-migration-test/src/x-modules/popular-searches/x-module.ts, packages/x-components/src/plugins/__tests__/x-plugin-alias.spec.ts, packages/x-components/src/x-modules/popular-searches/components/popular-search.vue, packages/x-components/src/x-modules/popular-searches/components/popular-searches.vue, packages/x-components/src/x-modules/popular-searches/x-module.ts
Migrate popular-searches x-module to composition API.
Components to migrate:
- `PopularSearches`
- `PopularSearch` 
[EMP-4316]: https://searchbroker.atlassian.net/browse/EMP-4316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate popular-searches module and add it to the playground

packages/x-components/src/x-modules/queries-preview/components/query-preview-button.vue
Migrate `QueryPreviewButton` to composition API
[EMP-4322]: https://searchbroker.atlassian.net/browse/EMP-4322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate `QueryPreviewButton` to composition API

packages/_vue3-migration-test/src/components/index.ts, packages/_vue3-migration-test/src/components/tagging/test-tagging.vue, packages/_vue3-migration-test/src/router.ts, packages/x-components/src/x-modules/tagging/components/__tests__/tagging.spec.ts, packages/x-components/src/x-modules/tagging/components/tagging.vue, packages/x-components/src/x-modules/tagging/x-module.ts, packages/x-components/tests/e2e/re-open.feature
=> feat(tagging): migrate to composition API

packages/x-components/src/x-modules/device/components/__tests__/device-detector.spec.ts, packages/x-components/src/x-modules/device/components/device-detector.vue, packages/x-components/src/x-modules/device/x-module.ts
Migrate device-detector component to composition API
To test it you can add this component to the `App.vue` file and check it in the X demo.
[EMP-4398]: https://searchbroker.atlassian.net/browse/EMP-4398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate device-detector component

packages/_vue3-migration-test/src/components/test-search.vue, packages/x-components/src/x-modules/search/components/fallback-disclaimer.vue
[EMP-4431](https://searchbroker.atlassian.net/browse/EMP-4431)
[EMP-4431]: https://searchbroker.atlassian.net/browse/EMP-4431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(fallback-disclaimer): migration to composition api

packages/x-components/src/x-modules/url/components/url-handler.vue, packages/x-components/src/x-modules/url/x-module.ts, packages/x-components/tests/e2e/url.feature
[EMP-4452]: https://searchbroker.atlassian.net/browse/EMP-4452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Migrate url-handler x-module

packages/_vue3-migration-test/src/components/index.ts, packages/_vue3-migration-test/src/components/test-base-switch.vue, packages/_vue3-migration-test/src/router.ts, packages/x-components/src/components/__tests__/base-switch.spec.ts, packages/x-components/src/components/base-switch.vue
While trying to fix the test for the `BaseSwitch` I realized it was not fully migrated to Vue3 as fails to implement correctly the use of the `v-model` directive.
In this PR I migrated correctly following [the official documentation](https://v3-migration.vuejs.org/breaking-changes/v-model.html) not creating a Breaking Change in the `BaseSwitch` component.
Also, a warning with the `aria-checked` was removed, the test was fixed, and a demo component has been created.
=> refactor(base-switch): migrate component to Vue3

packages/x-tailwindcss/src/x-tailwind-plugin/components/facet-filter/default.ts
Facets' icons are misaligned in Firefox.
Check the filters in the facets panel in the Firefox browser.
[EMP-4657]: https://searchbroker.atlassian.net/browse/EMP-4657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(design-system): facet alignment in firefox

packages/x-components/src/x-modules/query-suggestions/config.types.ts, packages/x-components/src/x-modules/query-suggestions/store/__tests__/getter.spec.ts, packages/x-components/src/x-modules/query-suggestions/store/getters/query-suggestions.getter.ts, packages/x-components/src/x-modules/query-suggestions/store/module.ts, packages/x-components/src/x-modules/query-suggestions/store/types.ts, packages/x-components/src/x-modules/query-suggestions/wiring.ts
[EMP-4713]
Make QuerySuggestions configurable to hide queries that match with any session query.
In PopularSearches and NextQueries modules we already have a [parameter](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/popular-searches/store/module.ts#L23) to manage when to hide queries if they match any session query. 
So we should replicate that logic in the QuerySuggestions module.
1) search for `midi dress`
2) clear query
3) search for `dress`
`midi dress` should not appear as a suggestion
[EMP-4713]: https://searchbroker.atlassian.net/browse/EMP-4713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-4713]: https://searchbroker.atlassian.net/browse/EMP-4713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> feat: hide suggestions that match with any session query

renovate.json
Use `github>empathyco/.github:frontend` https://github.com/empathyco/.github/blob/main/frontend.json config
=> chore(renovate): use github>empathyco/.github:frontend config

packages/x-adapter-platform/src/endpoint-adapters/related-prompts.endpoint-adapter.ts
Point to the correct endpoint.
=> fix: change related prompts endpoint

packages/x-components/src/x-modules/queries-preview/index.ts, packages/x-components/src/x-modules/queries-preview/utils/get-hash-from-query-preview.ts, packages/x-components/src/x-modules/queries-preview/utils/index.ts
Export get-hash-from-queries-preview functionality to use it in setups.
=> feat: export get-hash-from-query-preview functionality

packages/x-components/src/components/panels/__tests__/base-header-toggle-panel.spec.ts, packages/x-components/src/components/scroll/__tests__/base-scroll.spec.ts, packages/x-components/src/shims-vue.d.ts, packages/x-components/src/types/animation-prop.ts
Try to avoid this kind of type errors
=> fix(define-component): relax definecomponent type to avoid type collisions

packages/x-components/src/x-modules/next-queries/index.ts
We need to have this type accessible for customers setups
=> feat: export NextQueriesGroup type

packages/x-components/src/x-modules/related-prompts/events.types.ts
=> feat: add related prompts selection events

packages/x-components/src/components/page-selector.vue, packages/x-components/src/x-modules/search/store/__tests__/actions.spec.ts, packages/x-components/src/x-modules/search/store/actions/fetch-and-save-search-response.action.ts
Otherwise it starts at page 24, so we are not seeing the first 24 results.
=> fix(page-selector): request should start at 0

packages/x-adapter-platform/src/endpoint-adapters/related-prompts.endpoint-adapter.ts, packages/x-adapter-platform/src/mappers/url.utils.ts, packages/x-adapter-platform/src/schemas/models/related-prompt.schema.ts, packages/x-adapter-platform/src/types/models/related-prompt.model.ts, packages/x-components/src/__stubs__/related-prompts-stubs.factory.ts, packages/x-components/src/components/result/base-result-add-to-cart.vue, packages/x-components/src/types/origin.ts, packages/x-components/src/views/home/Home.vue, packages/x-components/src/views/home/display-click-provider.vue, packages/x-components/src/x-modules/related-prompts/components/related-prompts-tag-list.vue, packages/x-components/src/x-modules/related-prompts/events.types.ts, packages/x-components/src/x-modules/tagging/store/module.ts, packages/x-components/src/x-modules/tagging/wiring.ts, packages/x-types/src/query-signals/related-prompt.model.ts, packages/x-types/src/schemas/related-prompt.schema.ts
We should launch different taggings according to this confluence page https://searchbroker.atlassian.net/wiki/spaces/AG/pages/5028085781/Related+Prompts+Tagging
To test it search for `jamon` in X demo.
=> feat: related-prompts tooling tagging

packages/x-components/src/components/display-click-provider.vue, packages/x-components/src/components/index.ts, packages/x-components/src/views/home/Home.vue
=> feat: change display-click-provider component location

packages/x-components/src/x-modules/search/store/actions/save-search-response.action.ts
EMP-4743
Selected Filters are not cleared when there are no results.
This behavior can be reproduced in current customers: 
**example 1**:
* Go to [https://x.staging.empathy.co/x-fredmeyer/index.html?](https://x.staging.empathy.co/x-fredmeyer/index.html?) and search for `pearl`
* Filter using price range inputs & set them to min 450 and max 450.
* Then, the fallback disclaimer message appears, but selected filters are not removed from the state (they should be removed, and the fallback message should appear and then disappear to show results without filters again).
**example 2**:
* Example with the link already selected:
* https://x.staging.empathy.co/x-carrefour/index.html?env=live&filter=price%3A149571-149571.99&query=lavadora
Tests performed according to [testing …
=> fix: Remove selected filters from state when there are no results

packages/x-components/src/components/base-teleport.vue
[RST-3386](https://searchbroker.atlassian.net/browse/RST-3386)
[RST-3386]: https://searchbroker.atlassian.net/browse/RST-3386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RST-3386]: https://searchbroker.atlassian.net/browse/RST-3386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: implement target presence observable in BaseTeleport

packages/x-components/src/components/base-teleport.vue
`window`, `document`, `MutationObserver`, ... they are not defined in SSR build
Not tested :/
=> feat(base-teleport): support SSR ensuring DOM existence

.github/actions/install/action.yml, package.json, packages/deep-merge/package.json, packages/jest-utils/package.json, packages/storage-service/package.json, packages/x-adapter-platform/package.json, packages/x-adapter/package.json, packages/x-archetype-utils/package.json, packages/x-svg-converter/package.json, packages/x-tailwindcss/package.json, packages/x-translations/package.json, packages/x-utils/package.json
Doing `pnpm install` is very slow because a chain of:
- `preinstall`: check its pnpm
- `installl` (what we really want → 1 second)
- `postinstall`: build all packages (several minutes)
- `prebuild`: cleanup files (more time...)
- `build`: Slow slow ...
- `postbuild`: pack all packages (more time...)
splitting it allow us to install deps without waiting several minutes
also removed `postci` script as it is not used right?
=> chore: remove the install-build-pack chain
